#!/usr/bin/env python3
"""Render local static readers from the source register and verified figure list."""
import csv, html, json
from pathlib import Path
P=Path(__file__).resolve().parent
sources={r['id']:r for r in csv.DictReader((P/'sources.tsv').open(),delimiter='\t')}
H=html.escape
STYLE='''<style>:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f6f4ee;color:#142a36;font:17px/1.55 system-ui,-apple-system,sans-serif}header{background:#123f52;color:#fff;padding:3rem max(1.5rem,calc((100vw - 1140px)/2))}header h1{font:700 clamp(2.2rem,5vw,4rem)/1.08 Georgia,serif;max-width:900px;margin:.4rem 0}header p{max-width:850px;color:#d9e9e8}main{max-width:1140px;margin:auto;padding:2rem 1.5rem 5rem}nav{display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0}a{color:#086b83}header a{color:#d8f5fd}section{margin:3rem 0}h2{font:700 2rem Georgia,serif;margin:0 0 1rem}h3{font:700 1.28rem Georgia,serif}p{max-width:90ch}.lead{font-size:1.15rem}.callout{border-left:5px solid #d08439;background:#fff;padding:1.2rem 1.5rem;margin:2rem 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(350px,1fr));gap:1.4rem}.card{background:white;border:1px solid #dce3e0;border-radius:8px;box-shadow:0 4px 22px #183e5212;overflow:hidden}.card figure{margin:0}.card img{width:100%;height:auto;display:block}.card figcaption{padding:1rem 1.3rem 1.4rem}.meta{font-size:.84rem;letter-spacing:.04em;text-transform:uppercase;color:#5b7175}.card h3{margin:.35rem 0}.card p{margin:.55rem 0}.links{font-size:.88rem}.pill{display:inline-block;padding:.2rem .65rem;border-radius:1rem;background:#dfebe9;font-size:.8rem;margin-right:.4rem}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;background:white}th,td{padding:.75rem;border-bottom:1px solid #d9e1df;vertical-align:top;text-align:left}th{background:#e6eeeb;position:sticky;top:0}input{width:100%;padding:.8rem 1rem;font:inherit;border:1px solid #72939e;border-radius:5px;margin:.7rem 0 1.4rem}footer{padding:2rem 1.5rem;background:#dce8e4;color:#2c4e52}small{font-size:.85rem}@media(max-width:700px){.grid{grid-template-columns:1fr}header{padding:2rem 1.5rem}}</style>'''

def page(title,body,subtitle):
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+H(title)+'</title>'+STYLE+'</head><body><header><div class="meta" style="color:#a9dbdf">Portland small-business investigation · evidence cutoff 30 September 2026</div><h1>'+H(title)+'</h1><p>'+H(subtitle)+'</p><nav><a href="visual-atlas.html">Visual atlas</a><a href="source-explorer.html">Source explorer</a><a href="dossier.md">Dossier</a><a href="methodology.md">Methods</a><a href="gdp-feasibility.md">GDP memo</a></nav></header><main>'+body+'</main><footer>Local research artifact. Measurements are labeled by geography and year; source and calculation files are linked from each figure.</footer></body></html>'

FIGS=[
('03-city-small-jobs','A rare city-level small-business series','Incorporated Portland city · 2019 and 2024 · reported QCEW small-business jobs, 108,785 and 112,411 (+3.3%). Values transcribed from Prosper Figure 1.06.','prosper-insights','city-small-employment-report-2019-2024.csv','Report calls the band 1–20 in its text but 1–19 elsewhere. QCEW standard size classes are establishment based; underlying city table and unit need confirmation. Do not compare directly with SUSB enterprise shares.'),
('01-metro-size-jobs','How many jobs sit at each firm size?','Portland–Vancouver–Hillsboro MSA · 2022 · thousands of SUSB mid-March employer jobs. Bins are nonoverlapping enterprise sizes; all employer jobs = 1,084,535.','susb-msa-2022','metro-size-2022.csv','Employer establishments only. Not incorporated Portland city.'),
('02-metro-contributions','A different answer for jobs, pay and sales','Portland metro · 2022 · percent of SUSB employer-business jobs, annual payroll and gross receipts. Under 20: 18.8%, 13.3%, 11.9%; under 500: 50.2%, 41.0%, 35.4%.','susb-msa-2022','metro-size-2022.csv','Thresholds overlap and are not additive. Receipts are not profit or GDP; payroll is not value added.'),
('04-peer-under500-jobs','Portland against selected peers','Nine selected MSAs · 2022 · percentage of SUSB mid-March employer jobs at enterprises under 500. Portland 50.2%; Sacramento 50.4%; Salt Lake City 42.0%.','susb-msa-2022','metro-size-2022.csv','Selected peers, not an exhaustive ranking. Industry mix, geography and firm age are unadjusted.'),
('05-peer-under20-jobs','Micro-employer exposure differs','Nine selected MSAs · 2022 · percentage of SUSB employer jobs at enterprises under 20. Portland 18.8%; Sacramento 19.0%.','susb-msa-2022','metro-size-2022.csv','Employer jobs only; excludes solo nonemployers and is not a city measure.'),
('06-payroll-per-job','Pay measure needs care','Portland metro · 2022 · annual SUSB payroll divided by mid-March employer jobs, thousands of dollars, by enterprise size.','susb-msa-2022','metro-size-2022.csv','Not individual earnings, hourly wages or benefits. Industry, occupation and hours differ across sizes.'),
('07-sector-jobs','The economy extends beyond storefronts','Portland metro · 2022 · thousands of SUSB employer jobs, top 12 two-digit NAICS sectors. Health care 165,698; retail 121,817; manufacturing 113,841.','susb-msa-2022','metro-sectors-2022.csv','Includes large firms and institutions. Employer jobs; not city counts.'),
('08-sector-firms','Firm counts tell a different story','Portland metro · 2022 · thousands of SUSB employer firms, top 12 broad sectors. Professional services 8,870; construction 8,366.','susb-msa-2022','metro-sectors-2022.csv','Firms can have multiple establishments; this is not a count of storefronts or nonemployers.'),
('09-sector-under500','Small-firm dependence varies by sector','Portland metro · 2022 · share of each shown sector’s SUSB employer jobs at enterprises under 500. Denominator: all employer jobs in that sector.','susb-msa-2022','metro-sectors-2022.csv','Sector shares do not establish productivity, wages, local ownership or causal policy effect.'),
('10-sector-change','Where county jobs changed after 2019','Multnomah County · 2019 to 2025 · percent change in QCEW private annual-average covered jobs by broad sector, where 2019 jobs ≥1,000.','qcew-2025','qcew-sectors-2019-2025.csv','QCEW is not a firm-size table; private covered jobs exclude most proprietors. Changes are not attributed to City policy.'),
('11-nonemployers','The businesses missing from employer charts','Multnomah County · 2023 · thousands of Census NES tax-reporting businesses with no paid employees, top 12 broad sectors. County total 77,829.','nes-2023','nonemployer-sectors-2023.csv','Mailing/tax address may differ from operating site; a business may be part-time. Gross receipts are not owner income.'),
('12-osb-industries','OSB clients are not the city economy','Portland city OSB first year, approximately May 2025–May 2026 · percentage of businesses served in published industry categories; food 33%, retail 15%.','osb-2026',None,'Reported categories shown sum to 91%; remaining categories/rounding are not resolved here. Client mix is selected, not population mix.'),
('13-osb-services','Resources and referrals are the main recorded service','Portland city OSB first year · percentage of service categories: Prosper resources 50%, community connections 18%, other 14%, city bureaus 11%, capital 7%.','osb-2026',None,'These are reported classifications, not completed resolutions or outcomes.'),
('14-osb-intake','How OSB inquiries arrived','Portland city OSB first year · percentage of inquiries by reported source; liaison 30%, appointment 25%, Prosper website 19%.','osb-2026',None,'An inquiry channel says little about awareness among eligible nonusers or program impact.'),
('15-osb-district-gap','A visible reconciliation question','Portland city OSB first year · reported district business counts 103, 182, 154, 142, summing to 581; citywide unique count 759; difference 178.','osb-2026',None,'The 178 is an arithmetic gap, not a known “unassigned district” count. Different definitions or missing locations could explain it; request reconciliation.'),
('16-bds-entry-exit','Opening and closure both shape the economy','Portland–Vancouver–Hillsboro MSA · 2019–2023 · Census BDS establishment entry and exit rates. In 2023, 6,911 establishments entered and 6,588 exited.','bds-msa-2023','bds-metro-2019-2023.csv','Establishment entries include new sites of existing firms; exits need not be firm deaths or city closures. Rates are not survival probabilities.')]

cards=[]
for i,(slug,title,caption,sid,data,lim) in enumerate(FIGS,1):
 src=sources[sid]
 links='<a href="'+H(src['url'])+'">Original source</a> · <a href="visuals/'+slug+'.svg">SVG</a> · <a href="visuals/'+slug+'.png">PNG</a>'
 if data:links+=' · <a href="data/'+data+'">Underlying CSV</a>'
 else:links+=' · <a href="'+H(sources['osb-2026']['url'])+'">OSB pages 2 and 4</a>'
 cards.append('<article class="card"><figure><img loading="lazy" src="visuals/'+slug+'.svg" alt="'+H(title+'. '+caption+' Limitation: '+lim)+'"><figcaption><div class="meta">Figure '+str(i)+' · '+H(src['publisher'])+'</div><h3>'+H(title)+'</h3><p>'+H(caption)+'</p><p><strong>Read with care:</strong> '+H(lim)+'</p><div class="links">'+links+'</div></figcaption></figure></article>')
body='<p class="lead">These 16 figures answer what public data can measure now, and show where a credible Portland-city investigation still needs records and fieldwork.</p><aside class="callout"><strong>The GDP answer is unresolved.</strong> The employer-firm shares below are not a Portland city GDP split. Business size, geography, year and economic concept remain separate. <a href="gdp-feasibility.md">Read the feasibility memo</a>.</aside><section><h2>Scale, composition and change</h2><div class="grid">'+''.join(cards[:11]+cards[15:])+'</div></section><section><h2>Support activity and its missing denominator</h2><p>The OSB report describes service activity, not counterfactual economic impact. Its district arithmetic and engagement terms require clarification.</p><div class="grid">'+''.join(cards[11:15])+'</div></section><section class="callout"><h2>Figures we cannot responsibly draw yet</h2><p>Owner take-home income; within-industry worker benefits; city firm survival by age; eligible-to-served program funnel; actual cost per resolved problem; and city size-specific GDP. These are explicit acquisition questions in the <a href="fieldwork-kit.md">fieldwork kit</a>, not zeros on a chart.</p></section>'
(P/'visual-atlas.html').write_text(page('The small-business economy, in evidence',body,'Sixteen sourced figures on firm size, industry, peers, job change and the limits of reported support activity.'))
rows=[]
for r in sources.values():
 rows.append('<tr><td><code>'+H(r['id'])+'</code></td><td>'+H(r['family'])+'</td><td><a href="'+H(r['url'])+'">'+H(r['title'])+'</a><br><small>'+H(r['publisher'])+'</small></td><td>'+H(r['geography'])+'</td><td>'+H(r['reference_period'])+'</td><td><span class="pill">'+H(r['status'])+'</span><br><small>Access: '+H(r['access_status'])+'</small></td><td>'+H(r['research_questions'])+'<details><summary>Methods and provenance</summary><p>'+H(r['methodology_note'])+'</p><p><b>Interest:</b> '+H(r['funding_interest'])+'</p><p><b>Evidence:</b> '+H(r['evidence_locations'])+'</p><p><b>SHA-256:</b> <code>'+H(r['sha256'] or 'not archived')+'</code></p></details></td></tr>')
source_body='<p class="lead">Search '+str(len(sources))+' registered sources. “Screened” means discovered and triaged; it does not imply an audited finding. Check <a href="crawl-log.json">the crawl log</a> for archive hashes and access failures. <a href="claims.tsv">The claim ledger</a> links conclusions to exact rows or pages.</p><label for="filter">Filter by title, publisher, family, geography, status or note</label><input id="filter" type="search" placeholder="Try SUSB, permit, AI, or archived-reviewed" aria-controls="sources"><p id="count" role="status"></p><div class="table-wrap"><table id="sources"><thead><tr><th>ID</th><th>Family</th><th>Source</th><th>Geography</th><th>Period</th><th>Status</th><th>Use / caveat</th></tr></thead><tbody>'+''.join(rows)+'</tbody></table></div><script>const input=document.getElementById("filter"),rows=[...document.querySelectorAll("#sources tbody tr")],count=document.getElementById("count");function update(){let q=input.value.toLocaleLowerCase();let n=0;rows.forEach(r=>{let on=r.textContent.toLocaleLowerCase().includes(q);r.hidden=!on;if(on)n++});count.textContent=n+" of "+rows.length+" sources shown"}input.addEventListener("input",update);update()</script>'
(P/'source-explorer.html').write_text(page('Source explorer',source_body,'A searchable audit trail for the first-pass literature and dataset map.'))
print(json.dumps({'figures':len(FIGS),'sources':len(sources),'outputs':['visual-atlas.html','source-explorer.html']}))
