import Link from 'next/link';
import gaps from '@/lib/campaign-finance/gaps.json';
import manifest from '@/lib/campaign-finance/editorial-manifest.json';
import {BASE} from '@/lib/campaign-finance/filters';
import {Shell,Notice,styles} from '@/components/deep-dives/campaign-finance/Shared';
export default function Methodology(){return <Shell><header className={styles.profileHeader}><h1>What this record can—and cannot—tell us</h1><p>Reproducible accounting, cautious identities, explicit uncertainty.</p></header><Notice/>
  <section className={styles.section}><h2>Source audit</h2><div className={styles.prose}><p>The frozen snapshot contains 316,926 unique current transaction IDs from 1,888 filing committees. The raw acquisition contains 116 export workbooks. The audit checks their SHA-256 hashes, row counts, original 45-field schema, merged 46-field row widths, original-version IDs and complete nonoverlapping date partitions in each transaction family.</p><p>Matching the source’s reported count is one check, not proof that every required transaction was filed, every field is accurate or all recent activity is visible. Deleted records and superseded amendment versions are excluded.</p></div><div className={styles.tableScroll} role="region" aria-label="Snapshot checksums" tabIndex={0}><table><thead><tr><th>Dataset</th><th>Rows</th><th>SHA-256</th></tr></thead><tbody>{manifest.source_files.map(s=><tr key={s.sha256}><td>{s.name}</td><td>{s.rows.toLocaleString()}</td><td className={styles.code}>{s.sha256}</td></tr>)}</tbody></table></div></section>
  <section className={styles.section}><h2>Accounting rules</h2><div className={styles.prose}><p>Amounts are parsed as exact integer cents. Cash contributions, cash payments, in-kind support, loans, loan payments, forgiveness, obligations, refunds, cancellations and adjustments have distinct definitions. The export’s Aggregate Amount is not added to transaction Amount.</p><p>An account payable and its cash settlement describe different stages of one purchase. We do not sum them as two purchases. Loan principal and interest are not silently separated when the source does not provide an allocation. Refunds remain explicit; without a verified association, they are not arbitrarily deducted from a particular donor.</p><p>Cash effects are not bank balances. Beginning cash is not zero by default. An official summary can refer to a calendar year and a later live state; it must be reconciled with the fixed snapshot before supporting a reserve or debt claim.</p><p><a href="https://sos.oregon.gov/elections/documents/orestartransfiling.pdf">Official transaction filing manual</a> · <a href="https://sos.oregon.gov/elections/documents/campaign-finance.pdf">Campaign finance manual</a>.</p></div></section>
  <section className={styles.section}><h2>Identity and disclosure rules</h2><div className={styles.prose}><p>ORESTAR committee IDs are authoritative identifiers. Other counterparties are grouped using strict matching rules by normalized name, reported type and address fields; this is a fingerprint, not independent identity verification. Original names, aliases and observed dates remain available. Similar names are review candidates and are not automatically merged.</p><p>Miscellaneous and anonymous categories are scoped to the filing committee. Blank counterparties receive transaction-specific unknown keys. Neither category contributes to unique-donor counts or bridges between campaigns. We publish geographic summaries, not residential-address maps.</p><p>The 69,613 groups in the earlier entity index are provisional and are not used as a verified population of people or organizations. Employer fields do not convert an employee’s personal contribution into company funding.</p></div></section>
  <section className={styles.section}><h2>Transfers and network inference</h2><div className={styles.prose}><p>A strict transfer requires reciprocal committee IDs, the same positive amount and the same transaction date, with exactly one candidate on either side within seven days. Wider or nonunique matches stay in a review table. Both source filings are retained. A committee outside the observed filer set is different from a counterparty with no reported committee ID.</p><p>Shared-donor tests use a selected 30-committee bipartite graph. Swaps preserve both sets of observed degrees. Two seeds each generate 199 draws after 10 edge-counts of successful burn-in swaps, with one edge-count of swaps between draws. The 435-pair hypothesis family receives Benjamini–Hochberg adjustment. Markov-chain mixing, entity resolution and unobserved donors remain limitations; p-values are exploratory.</p><p>Financial connectivity is not coordination. Commingled funds admit possible allocation paths, not unique donor-to-vendor tracing.</p></div></section>
  <section className={styles.section}><h2>Uncertainty, comparisons and outcomes</h2><div className={styles.prose}><p>Exact reported totals are a census of this snapshot, so we do not attach artificial sampling confidence intervals. Concentration estimates are conditional on entity rules and identified amounts. Disclosure sensitivity ranges are scenarios, not probabilistic confidence intervals.</p><p>Any election-result model requires certified completed outcomes, pre-election financial windows, complete race rosters and validation across races or time. Multi-seat ranked-choice races cannot be treated as ordinary single-winner contests. The November 2026 election is pending. This edition does not estimate causal effects of contributions on elections or government decisions.</p></div></section>
  <section className={styles.section}><h2>Failure and gap register</h2><p><a href="/data/campaign-finance/failure-register.json">Collection summary and unresolved coverage</a> are summarized publicly; detailed operational logs remain in the private research archive. Existing raw downloads include 19 recovered request failures in the non-contribution collection. Enrichment failures and incomplete coverage remain separate from zeros.</p><div className={styles.tableScroll} role="region" aria-label="Unresolved research gaps" tabIndex={0}><table><thead><tr><th>Gap</th><th>Why the answer is unavailable</th><th>Required evidence</th></tr></thead><tbody>{gaps.map(g=><tr key={g.id}><td><Link href={`${BASE}/questions#${g.questionId}`}>{g.id} · {g.track}</Link></td><td>{g.description}</td><td>{g.requiredEvidence}</td></tr>)}</tbody></table></div></section>
  <section className={styles.section}><h2>Reproduction and edition boundary</h2><div className={styles.prose}><p>Acquisition, normalization, enrichment, analysis and publication are separate stages. The project-local Python environment pins DuckDB, numerical and network libraries. TypeScript browser collectors retain raw evidence, checksums, immutable acquisition partitions and bounded retries. Local analysis is limited to two numerical threads and a bounded-memory DuckDB configuration.</p><p>The explorer opens the checksum-verified database read-only, validates every filter and returns snapshot and metric versions. CSV exports stream in bounded chunks. No database or residential-address graph is sent to the browser.</p><p>This edition starts in January 2025. Earlier history and unresolved research questions remain future work; they are not implied to be complete.</p></div></section>
</Shell>;}
