import Link from 'next/link';
import gaps from '@/lib/campaign-finance/gaps.json';
import manifest from '@/lib/campaign-finance/editorial-manifest.json';
import {BASE} from '@/lib/campaign-finance/filters';
import {Shell,Notice,styles} from '@/components/deep-dives/campaign-finance/Shared';
import {governor,governorCandidate,longDate,wholeDollars,GOVERNOR_PATH} from '@/lib/campaign-finance/governor';
const drazanAccount=governorCandidate('christine-drazan')!.account;
export default function Methodology(){return <Shell><header className={styles.profileHeader}><h1>What this record can—and cannot—tell us</h1><p>Reproducible accounting, cautious identities, explicit uncertainty.</p></header><Notice/>
  <section className={styles.section}><h2>Source audit</h2><div className={styles.prose}><p>The frozen snapshot contains 316,926 unique current transaction IDs from 1,888 filing committees. The raw acquisition contains 116 export workbooks. The audit checks their SHA-256 hashes, row counts, original 45-field schema, merged 46-field row widths, original-version IDs and complete nonoverlapping date partitions in each transaction family.</p><p>Matching the source’s reported count is one check, not proof that every required transaction was filed, every field is accurate or all recent activity is visible. Deleted records and superseded amendment versions are excluded.</p></div><div className={styles.tableScroll} role="region" aria-label="Snapshot checksums" tabIndex={0}><table><thead><tr><th>Dataset</th><th>Rows</th><th>SHA-256</th></tr></thead><tbody>{manifest.source_files.map(s=><tr key={s.sha256}><td>{s.name}</td><td>{s.rows.toLocaleString()}</td><td className={styles.code}>{s.sha256}</td></tr>)}</tbody></table></div></section>
  <section className={styles.section}><h2>Accounting rules</h2><div className={styles.prose}><p>Amounts are parsed as exact integer cents. Cash contributions, cash payments, in-kind support, loans, loan payments, forgiveness, obligations, refunds, cancellations and adjustments have distinct definitions. The export’s Aggregate Amount is not added to transaction Amount.</p><p>An account payable and its cash settlement describe different stages of one purchase. We do not sum them as two purchases. Loan principal and interest are not silently separated when the source does not provide an allocation. Refunds remain explicit; without a verified association, they are not arbitrarily deducted from a particular donor.</p><p>Cash effects are not bank balances. Beginning cash is not zero by default. An official summary can refer to a calendar year and a later live state; it must be reconciled with the fixed snapshot before supporting a reserve or debt claim.</p><p><a href="https://sos.oregon.gov/elections/documents/orestartransfiling.pdf">Official transaction filing manual</a> · <a href="https://sos.oregon.gov/elections/documents/campaign-finance.pdf">Campaign finance manual</a>.</p></div></section>
  <section className={styles.section}><h2>Identity and disclosure rules</h2><div className={styles.prose}><p>ORESTAR committee IDs are authoritative identifiers. Other counterparties are grouped using strict matching rules by normalized name, reported type and address fields; this is a fingerprint, not independent identity verification. Original names, aliases and observed dates remain available. Similar names are review candidates and are not automatically merged.</p><p>Miscellaneous and anonymous categories are scoped to the filing committee. Blank counterparties receive transaction-specific unknown keys. Neither category contributes to unique-donor counts or bridges between campaigns. We publish geographic summaries, not residential-address maps.</p><p>The 69,613 groups in the earlier entity index are provisional and are not used as a verified population of people or organizations. Employer fields do not convert an employee’s personal contribution into company funding.</p></div></section>
  <section className={styles.section}><h2>Transfers and network inference</h2><div className={styles.prose}><p>A strict transfer requires reciprocal committee IDs, the same positive amount and the same transaction date, with exactly one candidate on either side within seven days. Wider or nonunique matches stay in a review table. Both source filings are retained. A committee outside the observed filer set is different from a counterparty with no reported committee ID.</p><p>Shared-donor tests use a selected 30-committee bipartite graph. Swaps preserve both sets of observed degrees. Two seeds each generate 199 draws after 10 edge-counts of successful burn-in swaps, with one edge-count of swaps between draws. The 435-pair hypothesis family receives Benjamini–Hochberg adjustment. Markov-chain mixing, entity resolution and unobserved donors remain limitations; p-values are exploratory.</p><p>Financial connectivity is not coordination. Commingled funds admit possible allocation paths, not unique donor-to-vendor tracing.</p></div></section>
  <section className={styles.section}><h2>Uncertainty, comparisons and outcomes</h2><div className={styles.prose}><p>Exact reported totals are a census of this snapshot, so we do not attach artificial sampling confidence intervals. Concentration estimates are conditional on entity rules and identified amounts. Disclosure sensitivity ranges are scenarios, not probabilistic confidence intervals.</p><p>Any election-result model requires certified completed outcomes, pre-election financial windows, complete race rosters and validation across races or time. Multi-seat ranked-choice races cannot be treated as ordinary single-winner contests. The November 2026 election is pending. This edition does not estimate causal effects of contributions on elections or government decisions.</p></div></section>
  <section className={styles.section}><h2>Failure and gap register</h2><p><a href="/data/campaign-finance/failure-register.json">Collection summary and unresolved coverage</a> are summarized publicly; detailed operational logs remain in the private research archive. Existing raw downloads include 19 recovered request failures in the non-contribution collection. Enrichment failures and incomplete coverage remain separate from zeros.</p><div className={styles.tableScroll} role="region" aria-label="Unresolved research gaps" tabIndex={0}><table><thead><tr><th>Gap</th><th>Why the answer is unavailable</th><th>Required evidence</th></tr></thead><tbody>{gaps.map(g=><tr key={g.id}><td><Link href={`${BASE}/questions#${g.questionId}`}>{g.id} · {g.track}</Link></td><td>{g.description}</td><td>{g.requiredEvidence}</td></tr>)}</tbody></table></div></section>
  <section className={styles.section} id="governor"><h2>Governor’s race edition</h2><div className={styles.prose}>
    <p>The <Link href={GOVERNOR_PATH}>governor’s race investigation</Link> is its own dated edition. It reads the same ledger as the explorer, covers January 1, 2025 through {longDate(governor.end)}, and was reviewed on {longDate(governor.reviewedAt)}. It does not change when the ledger is refreshed; it is rebuilt and reread as a whole.</p>
    <p>Two committees are linked to candidates. Each link rests on the committee’s ORESTAR statement of organization, retrieved {longDate(governorCandidate('tina-kotek')!.linkRetrievedAt)}, which names the candidate and the office of governor for the 2026 general election. No committee naming the third candidate appears among filers with transactions, and that is reported as missing coverage.</p>
    <p>Sources are grouped first by the contributor type on each filing: individuals, businesses, labor organizations and combined entries of $100 or less. Committees and associations that gave {wholeDollars(governor.context.sourceKindMinimumCents)} or more to either campaign are then grouped by sponsor where the name, the committee’s own filings or a cited source make the sponsor clear. Every reviewed grouping and its basis is listed under the first chart and in the evidence download. Committees below that amount stay under other committees, so union and trade totals are minimums.</p>
    <p>Gift-size groups use each source’s total to one campaign since January 2025. The count under the 2027 limits compares individuals and businesses against twice the per-election cap, because the primary and the general are separate elections.</p>
    <p>State totals use the address reported for each contributor. County totals cover named individuals only. A gift is placed in a county by its ZIP code using the Census Bureau’s 2020 ZIP-area-to-county file, and a ZIP area that crosses a county line goes to the county holding most of its land. Post office box ZIP codes have no Census area, so those gifts go to the county where at least 80% of the same city’s placed gifts sit, and otherwise stay unplaced. ZIP codes and street addresses are used for this step only and are never published.</p>
    <p>The committee-funding table reads each donor committee’s own cash receipts in the same period. It names a funder only when that funder is an organization supplying at least 5% of the committee’s receipts.</p>
    <p>Cash left on the comparison date is a calculation: the committee’s official opening balance for 2026 plus every filed cash movement through the last day on which both committees have payments on file. Official summaries were retrieved {longDate(drazanAccount.retrievedAt)}. Kotek’s reconciled to the ledger exactly; Drazan’s 2026 summary showed {wholeDollars(drazanAccount.paymentDifferenceCents)} more in payments than the ledger, which is unresolved and too small to change any figure shown.</p>
  </div></section>
  <section className={styles.section}><h2>Reproduction and edition boundary</h2><div className={styles.prose}><p>Acquisition, normalization, enrichment, analysis and publication are separate stages. The project-local Python environment pins DuckDB, numerical and network libraries. TypeScript browser collectors retain raw evidence, checksums, immutable acquisition partitions and bounded retries. Local analysis is limited to two numerical threads and a bounded-memory DuckDB configuration.</p><p>The explorer opens the checksum-verified database read-only, validates every filter and returns snapshot and metric versions. CSV exports stream in bounded chunks. No database or residential-address graph is sent to the browser.</p><p>This edition starts in January 2025. Earlier history and unresolved research questions remain future work; they are not implied to be complete.</p></div></section>
</Shell>;}
