export const LESSON_DATE = "2026-09-27";
export const LESSON_SOURCES = {
  behavior: { title: "OSU Extension · Fire behavior", url: "https://extension.oregonstate.edu/catalog/em-9341-fire-behavior", locator: "What is fire behavior?; fuel, topography and weather" },
  ecology: { title: "OSU Extension · Ecological effects of fire", url: "https://extension.oregonstate.edu/catalog/em-9340-ecological-effects-fire", locator: "Fire regimes and ecosystem-specific effects" },
  history: { title: "OSU · Western Cascades fire-history research", url: "https://news.oregonstate.edu/news/western-cascades-landscapes-oregon-historically-burned-more-often-previously-thought", locator: "Research summary and link to the underlying study; sampled Oakridge-area landscapes" },
  stewardship: { title: "Oregon Department of Education · Tribal History/Shared History", url: "https://www.oregon.gov/ode/educator-resources/standards/science/Pages/SB13_Science.aspx", locator: "Historical and contemporary natural resource management; land management and partnerships" },
  adaptation: { title: "Prichard and colleagues · Ten questions about western forests", url: "https://research.fs.usda.gov/treesearch/63624", locator: "2021 review; climate adaptation, fire exclusion, treatment and post-fire choices" },
  planning: { title: "OSU Extension · Planning a prescribed burn", url: "https://extension.oregonstate.edu/catalog/pub/em-9343-planning-prescribed-burn", locator: "Objectives, planning and implementation" },
  woodpecker: { title: "OSU · Woodpecker: Fire with a purpose", url: "https://www.forestry.oregonstate.edu/news/fire-purpose", locator: "April 3, 2026 account of the October 2025 burns" },
  synthesis: { title: "Davis and colleagues · Review of 40 treatment studies", url: "https://research.fs.usda.gov/download/treesearch/67659.pdf", locator: "2024; sections 2.1–2.2 and 3.2.1; Figure 3. Relative effects on severity in treated areas subsequently reached by wildfire" },
  egley: { title: "Dodge and colleagues · Egley Fire Complex study", url: "https://research.fs.usda.gov/download/treesearch/59149.pdf", locator: "2019; abstract, methods and one-/nine-year field observations. Reported percentage/hectare denominators require clarification" },
  economics: { title: "Thompson and colleagues · Treatment encounters and suppression costs", url: "https://research.fs.usda.gov/download/treesearch/55535.pdf", locator: "2017; Sierra National Forest modeling study, sections 3–4; encounters and annual savings distributions" },
  costs: { title: "Bayham and colleagues · Economics of wildfire", url: "https://research.fs.usda.gov/treesearch/65524", locator: "2022 literature-review catalog and abstract" },
  smoke: { title: "ODF · 2025 Smoke Management report", url: "https://www.oregon.gov/odf/fire/Documents/smr2025.pdf", locator: "2025 at a glance (page 2); program scope and accomplishment definitions" },
  nasa: { title: "NASA · Oregon’s 2020 fire scars", url: "https://modis.gsfc.nasa.gov/gallery/individual.php?db_date=2020-09-29", locator: "Terra MODIS false-color observation and original explanation" },
  mtbs: { title: "MTBS · Assessment methods and coverage", url: "https://www.mtbs.gov/faqs", locator: "Severity, mapping thresholds and limitations" },
  homes: { title: "NIST · How fire spreads into communities", url: "https://www.nist.gov/el/fire/resources/hazard-mitigation-methodology-hmm/how-fire-spreads-wui", locator: "Direct flame, radiant heat, ember exposure and structure-to-structure ignition" },
  finley: { title: "US Fish & Wildlife Service · Finley refuge management", url: "https://www.fws.gov/refuge/william-l-finley/what-we-do", locator: "Prairie and oak habitat management and prescribed burning" },
  sage: { title: "US Forest Service · Sagebrush treatment review", url: "https://research.fs.usda.gov/treesearch/67664", locator: "2024 review abstract; treatment, fuels and invasive annual grass tradeoffs" },
  cwpp: { title: "Oregon Explorer · Community Wildfire Protection Plans", url: "https://hub.oregonexplorer.info/content/oregon-cwpp-planning-tool", locator: "Community planning tool and local priorities" },
} as const;
export type LessonSource = keyof typeof LESSON_SOURCES;
export type FireLesson = {
  slug: string; anchor: string; label: string; title: string;
  paragraphs: string[]; takeaway: string; transition: string;
  sources: LessonSource[];
  detail: { title: string; paragraphs: string[] }[];
  question: string;
};

export const FIRE_LESSONS: FireLesson[] = [
  {
    slug: "how-fire-moves", anchor: "how-fire-moves", label: "The mechanics", title: "Start at the ground. Follow the flames.",
    paragraphs: [
      "Dead needles, grass, branches and shrubs can all burn. In a forest, a surface fire moves through fuel near the ground. Small trees and low branches can give it a path into taller trees. Wind can also carry burning embers ahead of the flames.",
      "That is why the arrangement of plants matters as well as the amount of fuel. Moisture, wind and slope influence how a fire behaves. People can change some fuels and choose the conditions for a planned burn; a wildfire arrives on its own timetable.",
    ],
    takeaway: "Two different questions: how does the fire behave, and what does it change?",
    transition: "Now put that fire in a different landscape. The same process can have a very different result.",
    sources: ["behavior", "homes"], question: "How could fire reach a tree’s crown without burning its trunk all the way to the top?",
    detail: [
      { title: "Fuel is an arrangement, not just a pile", paragraphs: ["Fine, dry fuels can ignite readily. Larger pieces behave differently and may keep smoldering after a flame front passes. Surface fuels, low branches and tree crowns occupy different positions. A project can reduce connections between them without removing every tree.", "In planning, look for what was actually changed: surface material, small trees, crown spacing or a combination. Thinning and dealing with the material left on the ground are separate steps. An activity called thinning does not tell you how those surface fuels were handled."] },
      { title: "Weather and terrain still matter", paragraphs: ["Fuel moisture affects how readily vegetation burns. Wind influences flames and can transport embers to new locations. Slope changes how heat reaches unburned vegetation uphill. A fuel treatment changes part of this system; it does not set the weather.", "A useful diagram explains these relationships. Predicting a spread rate or flame length for an actual place requires measured inputs and an appropriate fire-behavior model."] },
      { title: "Intensity and severity answer different questions", paragraphs: ["Intensity describes energy released by a fire. Severity describes effects on vegetation, soil or other ecosystem components. The length of time heat remains in a place matters too. A short-lived flame and prolonged smoldering can have different effects.", "Satellite severity products measure particular kinds of change using defined methods. Their colors need a legend, an assessment date and the landscape’s ecological context."] },
      { title: "Embers connect the forest to the neighborhood", paragraphs: ["Burning material can be carried beyond the flame front and ignite other fuels. NIST describes several routes into a community, including direct flames, heat radiation, embers and fire spreading from one building to another.", "This is why preparing a forest and reducing ignition vulnerabilities around buildings address different parts of the problem. Both belong in a discussion of community protection."] },
    ],
  },
  {
    slug: "different-landscapes", anchor: "understand", label: "The place", title: "Oregon has more than one relationship with fire.",
    paragraphs: ["In many dry pine forests, recurring surface fires helped keep stands open. In oak and prairie habitat, fire can help keep shrubs and trees from taking over. Some wetter forests have long fire intervals; western Oregon also contains places with much more frequent fire histories.", "Sagebrush adds another complication: invasive annual grasses can encourage repeated fire and change habitat. Choosing what to do starts with the plants, local history and conditions of the place—not a rule for the whole state."],
    takeaway: "Choose the habitat and the outcome before choosing the treatment.",
    transition: "To understand the conditions we see today, we also need to understand how they developed.",
    sources: ["ecology", "history", "finley", "sage"], question: "Why might keeping a prairie open and keeping a forest’s large trees alive call for different measures of success?",
    detail: [
      { title: "Dry pine and southwest mixed conifer", paragraphs: ["Recurring fire helped shape many seasonally dry forests. Where small trees and surface fuels have accumulated, reducing fuels and using fire may support goals such as retaining large trees or reducing later fire severity. The mix of species, current condition and previous land use still matter.", "Southwest mixed-conifer forests are not interchangeable with every east-side pine forest. A local project needs its own vegetation description, history and objectives."] },
      { title: "Western forests have varied histories", paragraphs: ["A wet regional climate does not tell the whole fire history of a site. OSU’s Western Cascades research summary describes tree-ring evidence from sampled landscapes near Oakridge that complicates a simple picture of infrequent western fire.", "That finding needs its geography attached. It is not a schedule for all western forests. Local moisture, vegetation, terrain, stewardship and changing climate matter when choosing a present-day strategy."] },
      { title: "Prairie, oak and sagebrush", paragraphs: ["At Finley, the refuge program describes maintaining prairie and oak habitat through several tools, including fire. A larger tree count would not automatically indicate success if the objective is an open native prairie.", "In sagebrush, treatment can trade reduced woody fuel against changes in herbaceous fuel and invasive plants. The relevant question is how the plant community responds, including after repeated fire. Acres treated alone do not answer that question."] },
      { title: "History informs a choice; objectives define it", paragraphs: ["Historical fire intervals describe patterns inferred for particular landscapes and periods. Present choices also need to consider people, climate, smoke, habitat, legal authority and implementation capacity.", "The landscape groups in this guide introduce differences. They are not an exhaustive vegetation classification or a management prescription for every parcel."] },
    ],
  },
  {
    slug: "how-we-got-here", anchor: "landscape-history", label: "The history", title: "Today’s landscape has a history.",
    paragraphs: ["Lightning and Indigenous burning have long shaped Oregon landscapes. Indigenous stewardship includes deliberate choices about plants, habitat and cultural relationships. Colonization disrupted that stewardship; grazing, logging, roads, settlement and fire suppression also changed many places.", "Those histories interact with today’s climate and weather. The useful question is not simply whether a forest looks denser than an old photograph. It is what changed at this particular place, why it changed, and which conditions we can influence now."],
    takeaway: "A photograph shows a view. Tree rings, land-use records and local knowledge help explain its history.",
    transition: "History helps explain the problem. A present-day objective tells us what the work is meant to achieve.",
    sources: ["stewardship", "history", "adaptation"], question: "What additional evidence would you need before attributing a change between two photographs to fire suppression?",
    detail: [
      { title: "Stewardship is historical and contemporary", paragraphs: ["Indigenous fire is connected to people, knowledge, sovereignty and specific purposes. It should not be reduced to an anonymous technique that can be separated from its practitioners.", "Oregon’s Tribal History/Shared History science resources include historical and contemporary natural resource management and partnerships. For local cultural-fire accounts, interpretation and publication should be developed with the relevant people and programs."] },
      { title: "Several changes can occur together", paragraphs: ["Changes in land use can alter vegetation and fuels. Excluding recurring fire can matter in forests adapted to frequent fire, while logging, grazing, roads and settlement can also influence conditions. The appropriate explanation depends on the place and evidence.", "Climate and weather shape what can burn and the conditions when it burns. A useful account connects these drivers without treating one history as an explanation for every Oregon landscape."] },
      { title: "Read a photograph carefully", paragraphs: ["A repeat photograph needs matched geography, dates, viewpoints and original captions. Season, image quality and camera position can change what appears visible. Separate observations about plant cover, size and location from an explanation of their causes.", "The original Horse Canyon pair in our deeper story offers a method example from Utah. Oregon’s history requires Oregon evidence: located photographs, sampled fire histories, records and relevant knowledge."] },
      { title: "A past condition is not an automatic target", paragraphs: ["Tree-ring and photograph studies help reconstruct particular past conditions. The future can differ because of climate, development, invasive plants and other changes.", "A project should explain its desired future condition and why that objective is appropriate. Ask which historical evidence was used, which present constraints were considered and what will be measured afterward."] },
    ],
  },
  {
    slug: "choosing-the-work", anchor: "burn-windows", label: "The choices", title: "A prescribed burn starts with a purpose.",
    paragraphs: ["Managers choose a desired outcome, then plan how to reach it. The work might involve cutting small trees, handling branches left on the ground, preparing boundaries, or burning under selected conditions. A burn needs suitable weather, fuels, smoke conditions, people and equipment.", "At OSU’s McDonald-Dunn Research Forest, the October 2025 Woodpecker burns had two different goals: supporting oak and madrone in one unit, and Willamette Valley ponderosa pine in another. The reason for burning was tied to the vegetation managers wanted to keep."],
    takeaway: "Planning, preparation, ignition and follow-up are different parts of the work.",
    transition: "Having a purpose does not establish a result. The next question is what the evidence shows after the work.",
    sources: ["planning", "woodpecker", "smoke"], question: "Why could a manager postpone a well-prepared burn even when the ecological objective remains the same?",
    detail: [
      { title: "Start with a measurable objective", paragraphs: ["A purpose such as reducing fuel or restoring habitat needs a more specific project objective. Which trees or plants should benefit? What should change on the ground? How will the result be checked?", "Woodpecker’s published account supplies two vegetation objectives and describes planning and implementation. Unit boundaries, itemized costs and repeat monitoring are additional records we still seek for a fuller dossier."] },
      { title: "Preparation and burning are distinct", paragraphs: ["Mechanical work can change tree density and fuel arrangement. Material left after cutting may still need treatment. Pile burning concentrates cut material; broadcast or understory burning carries fire over a unit in a different way.", "Treatment records should retain that sequence. A planned polygon, a mechanical activity and a completed burn are not three interchangeable accomplishments."] },
      { title: "The burn window is a set of conditions", paragraphs: ["Weather, moisture, smoke transport, staffing and preparation must fit the plan. The same objective can remain valid when a particular day is unsuitable. Choosing another day is part of carrying out the work.", "Permits, smoke registrations and authorizations have different roles. A permitted or registered unit does not establish that it was ignited or completed."] },
      { title: "One unit can have several ignitions", paragraphs: ["ODF’s 2025 Smoke Management report records 2,717 burned units and 3,941 ignitions, with 179,230 acres reported. Those measures describe different aspects of its forestland program.", "An ignition count is not a count of distinct units. Repeated operations, partial work, burn method and acreage definitions should remain visible when comparing accomplishments."] },
    ],
  },
  {
    slug: "does-treatment-work", anchor: "fire-stories", label: "The evidence", title: "Does earlier work change a later wildfire?",
    paragraphs: ["Researchers can compare treated and untreated areas reached by wildfire. A 2024 review combined evidence from 40 studies in western US conifer forests. Several treatments involving burning were associated with substantially lower subsequent severity in the analyzed seasonally dry forests.", "These findings concern what happened where wildfire reached the work. They do not mean that the same percentage of fires was prevented. Treatment type, age, study methods and the landscape matter when interpreting the result."],
    takeaway: "Lower fire severity is a measured effect. Its value depends on the trees, habitat and people we are trying to protect.",
    transition: "A fire’s immediate effects are only part of the story. We need to revisit the place afterward.",
    sources: ["synthesis", "egley"], question: "Why does a reduction in severity within treated areas not establish the number of homes saved across a region?",
    detail: [
      { title: "What the synthesis compared", paragraphs: ["Davis and colleagues reviewed 40 studies with treated and untreated observations after wildfire, comprising 172 sites and 256 observations. The analysis combines several severity measures using relative effect sizes.", "The main-page bars show reported mean reductions for three treatment categories. They are not individual site forecasts. The paper’s Figure 3 and methods supply uncertainty and the treatment-age comparisons needed for a fuller interpretation."] },
      { title: "Interpret the averages without turning them into a ranking", paragraphs: ["The review reports average reductions of 72% for thinning plus prescribed burning, and 62% for thinning plus pile burning or prescribed burning alone. It did not establish statistically different overall effects among these three categories.", "These relative effects on severity measures apply to the analyzed settings where wildfire followed treatment. They are not percentages of acreage restored, fires prevented or money saved. Selection of a method also involves ecological objectives and feasibility."] },
      { title: "The work changes over time", paragraphs: ["Across the review’s treatment and forest categories, average reduction was 66% when wildfire occurred within ten years and 28% when it occurred more than ten years later. Those groups summarize observations; they do not define a universal ten-year reburn deadline.", "Maintenance and repeated activities belong in both the ecological explanation and the cost account. A treatment’s date helps interpret what it could influence when a later fire arrived."] },
      { title: "An Oregon study, with several treatment histories", paragraphs: ["The Egley study examined the 2007 fire complex in Oregon and returned to field sites one and nine years afterward. Its treatments included harvest, thinning, piling/burning and prescribed fire; they cannot all be relabeled prescribed burns.", "The study found lower initial severity in treated areas and differences in later fuels and vegetation. Its reported percentage/hectare totals contain a denominator discrepancy that needs clarification, so this guide does not derive a new acreage estimate from those figures."] },
    ],
  },
  {
    slug: "after-the-fire", anchor: "through-time", label: "The aftermath", title: "A fire ends. Its effects keep unfolding.",
    paragraphs: ["An outline on a map shows the extent of an event. Inside it, some ground may remain unburned, some trees may survive, and other patches may change greatly. Severity assessments help describe that pattern.", "Later, plants return, dead wood changes, and habitat develops. A greener satellite image does not tell us which plants returned or whether a project met its goals. Repeated observations of trees, soils, habitat and affected communities make the picture more useful."],
    takeaway: "Read three layers together: where the fire was, what changed, and what happened later.",
    transition: "Once we know which outcomes matter, we can ask what reaching them costs.",
    sources: ["mtbs", "nasa", "egley"], question: "Could two sites look equally green from space while having very different numbers of surviving large trees?",
    detail: [
      { title: "A perimeter is a boundary", paragraphs: ["An incident perimeter outlines an event; it is not a measurement that every acre inside burned. A treatment-unit boundary describes planned or recorded work, which is another kind of geography.", "For border-crossing fires, the whole incident’s reported acreage differs from its mapped area within Oregon. Label these separately. Repeated or overlapping events also require care before adding area totals."] },
      { title: "Severity describes particular effects", paragraphs: ["MTBS uses defined satellite assessment methods and maps a subset of larger fires. Coverage thresholds mean many small fires and treatments are absent. Unassessed and unavailable pixels are different from unburned or low-severity pixels.", "A severity color alone cannot decide whether an outcome was ecologically desirable. Read its definition, timing and landscape context alongside project objectives and field observations."] },
      { title: "Use a common place and dated observations", paragraphs: ["The main page compares the same western Oregon extent in Terra MODIS imagery before and after the September 2020 fires. False color helps reveal landscape changes; clouds, season and other dark surfaces affect interpretation.", "For quantitative summaries, use reviewed source products and appropriate masks and methods. The displayed images are observations, not a calculation of burned acreage or habitat recovery."] },
      { title: "Follow more than greenness", paragraphs: ["Egley’s one- and nine-year field visits examined vegetation and fuels as well as satellite signals. Useful outcome measures can include surviving trees, regeneration, invasive plants and habitat condition, chosen for the site’s objective.", "Community outcomes require their own evidence: smoke observations, water-system impacts, damage records or other documented effects. They do not follow automatically from a forest severity map."] },
    ],
  },
  {
    slug: "costs-and-choices", anchor: "costs-and-choices", label: "The economics", title: "What does spending ahead buy us?",
    paragraphs: ["Preventive work costs money now, and keeping it effective can require more work later. A future wildfire may or may not reach the treated area. If it does, changed fire effects may reduce some losses or make response easier. Ecological benefits can also occur without a later wildfire.", "A fair comparison puts feasible choices in the same place over the same period. It separates actual spending from possible savings, and asks who pays for the work, who experiences the smoke, and who receives the benefits."],
    takeaway: "Compare the full choices over time: initial work, upkeep, response and consequences.",
    transition: "These choices are made by people and institutions. The last step is finding the decisions that matter where you live.",
    sources: ["economics", "costs"], question: "If a treatment costs money and no wildfire reaches it, what outcomes could still make it worthwhile?",
    detail: [
      { title: "First establish what was actually spent", paragraphs: ["A useful project account separates planning, preparation, implementation, monitoring and maintenance. It identifies the year, accounting period, geographic scope, payer and whether the figure is an expense, budget, grant or estimate.", "Incident cost reports may be cumulative estimates. Adding successive cumulative reports double counts spending; a projected final amount is not money already spent. Record the reporting date and status with every amount."] },
      { title: "Then compare possible futures", paragraphs: ["A treatment can affect loss only in circumstances where its effects are relevant. A financial scenario needs the probability of those circumstances and an estimate of the difference in loss with and without the strategy.", "The simple teaching calculation on the main page multiplies encounter probability by conditional damage avoided. Its numbers are invented. An actual Oregon analysis also needs maintenance, timing, multiple outcomes, treatment risks and a consistent baseline strategy."] },
      { title: "Average benefits and a typical year can differ", paragraphs: ["Thompson and colleagues modeled treatments in the Sierra National Forest. Fire-treatment encounters were uncommon and median suppression savings were zero, while extreme years could produce much larger savings.", "That illustrates why probability matters. It does not supply Oregon’s probabilities, prove that every treatment pays for itself or account for every ecological and community benefit."] },
      { title: "Keep the public budget and wider outcomes visible", paragraphs: ["Firefighting expenditure is one part of the account. Property loss, health impacts, water systems and habitat outcomes involve other people and measures. Some can be valued in dollars with appropriate methods; others should be reported in their original units.", "This atlas does not yet have verified itemized costs and counterfactual loss estimates for a complete Oregon project comparison. We seek those records and will distinguish recorded expenditure, modeled estimates and observed outcomes as they are added."] },
    ],
  },
  {
    slug: "living-with-fire", anchor: "what-success-means", label: "The decisions", title: "There is work to do at every scale.",
    paragraphs: ["On the landscape, managers choose habitat and fuel objectives. Around buildings, people can reduce vulnerabilities to embers and nearby flames. Communities plan for smoke, emergency communication and evacuation. Firefighters respond to the conditions that actually occur.", "Those efforts fit together. Start with a place you know: its vegetation, land managers, nearby projects and community plan. Ask what the work is intended to change, how it is funded, and what observations will show whether it helped."],
    takeaway: "The goal is a place better prepared for fire, with outcomes we can explain and check.",
    transition: "You now have the questions to bring to the records. Choose a place and investigate the evidence below.",
    sources: ["homes", "cwpp", "planning"], question: "Which decisions belong to a homeowner, which to a land manager, and which require community action?",
    detail: [
      { title: "The landscape and the neighborhood", paragraphs: ["Landscape treatments address vegetation, habitat and potential fire effects. Structure and parcel work address routes by which embers, flames or heat can cause ignition. Nearby buildings and other fuels can influence exposure.", "An intervention at one scale does not describe the whole system. Use NIST’s community guidance alongside local fire-program advice and the actual conditions of the site."] },
      { title: "Find the public decisions", paragraphs: ["A Community Wildfire Protection Plan can identify local priorities and proposed work. Read its adoption date, geographic scope and implementation status. A priority area does not by itself prove why a particular burn unit was selected.", "A project’s decision documents explain stated objectives and considered alternatives. Public budgets and grants describe parts of its funding. Monitoring records help check its outcomes."] },
      { title: "Plans, operations and evidence", paragraphs: ["Distinguish a planned unit from a permitted unit and both from confirmed completed work. Keep mechanically treated areas separate from burn accomplishments. Ask whether a source reports a boundary, an occurrence, an ignition or an observation.", "The atlas preserves source links and dates so you can inspect the record. Coverage remains uneven, especially for local permits and ecological burning outside the federal inventories."] },
      { title: "Bring a specific question", paragraphs: ["When discussing a project, ask: why this place; what should change; what preparation is required; what happened; and what follow-up exists? For money, ask what an amount includes and whether it was spent or estimated.", "For current emergencies and smoke, use official alerts and air-quality information. The educational atlas supplies history and interpretation; emergency conditions require the current official sources linked below."] },
    ],
  },
];

export const TREATMENT_REVIEW = {
  source: "synthesis" as const, year: 2024, studies: 40,
  metric: "Reported mean reduction in subsequent wildfire severity",
  scope: "Analyzed seasonally dry western US conifer forests; treated areas subsequently reached by wildfire",
  values: [
    { method: "Prescribed burning", value: 62 },
    { method: "Thinning + pile burning", value: 62 },
    { method: "Thinning + prescribed burning", value: 72 },
  ],
};
