import type { FireSource } from "./types";

// Verification refers to the 2026-09-11 audit, not live availability.
const odfFields = [
  "OBJECTID",
  "DistrictName",
  "County",
  "RegistrationNumber",
  "TRS",
  "Elevation",
  "Ownership",
  "SaleName",
  "AcresPlanned",
  "Plan_Types",
  "TotalTonsBurned",
  "PlannedIgnitionTime",
  "ActualIgnitionTime",
  "BurnType",
  "UnitAcres",
  "LandingAcres",
  "PileAcres",
  "BroadcastAcres",
];
export const FIRE_SOURCES: FireSource[] = [
  {
    id: "blm",
    name: "BLM prescribed fire treatments",
    agency: "BLM",
    url: "https://gbp-blm-egis.hub.arcgis.com/datasets/BLM-EGIS::blm-or-prescribed-fire-treatments-polygon-hub",
    endpoint:
      "https://services1.arcgis.com/KbxwQRRfWyEYLgp4/arcgis/rest/services/BLM_OR_Prescribed_Fire_Treatments_Polygon_Hub/FeatureServer/1",
    fields: [
      "OBJECTID",
      "TRT_GUID",
      "GlobalID",
      "TRT_NAME",
      "PROJ_NAME",
      "UNIT_NUM",
      "BURN_TYPE",
      "TRT_STATUS",
      "TRT_DATE",
      "TRT_FY",
      "TRT_DATE_ACC",
      "BLM_ORG_CD",
      "PLANID",
      "REASON",
      "REASON2",
      "TRT_ACRES",
      "GIS_ACRES",
      "COORD_SRC",
      "ACCURACY_FT",
    ],
    cadenceHours: 168,
    coverage:
      "Historical treatment units on BLM lands; Oregon-intersecting features from the OR/WA service.",
    limitations:
      "Treatment polygons are not observed burned footprints. Planning-document identifiers are often missing. Repeat treatments remain separate.",
    verification: "queried",
    role: "primary",
  },
  {
    id: "facts",
    name: "USFS FACTS fire treatments",
    agency: "USFS",
    url: "https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_HazardousFuelsTreatments_01/MapServer/3",
    endpoint:
      "https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_HazardousFuelsTreatments_01/MapServer/3",
    where: "state_abbr='OR'",
    fields: [
      "objectid",
      "suid",
      "facts_id",
      "activity_cn",
      "activity_unit_cn",
      "activity",
      "activity_unit_name",
      "fs_unit_name",
      "nepa_project_id",
      "nepa_doc_name",
      "purpose_code",
      "date_completed",
      "date_planned",
      "fiscal_year_completed",
      "uom",
      "nbr_units_accomplished",
      "gis_acres",
      "accuracy",
      "etl_modified_date_haz",
      "ownership_code",
    ],
    cadenceHours: 168,
    coverage:
      "Oregon hazardous-fuels fire treatment records on national forests.",
    limitations:
      "Includes planned treatments consumed by wildfire. Purpose codes are administrative; they do not fully explain site selection. Accomplished treatment acres do not measure fire footprint.",
    verification: "queried",
    role: "primary",
  },
  {
    id: "pnw",
    name: "PNW prescribed fire tracker",
    agency: "USFS / partners",
    url: "https://experience.arcgis.com/experience/55ce8bfdea4345b6a06ae81d67e7d411",
    endpoint:
      "https://services1.arcgis.com/gGHDlz6USftL5Pau/arcgis/rest/services/PNW_Planned_Rx_Polygon_Public/FeatureServer/1",
    fields: [
      "OBJECTID",
      "GlobalID",
      "ACTIVITY_UNIT_NAME",
      "BURN_STATUS",
      "NBR_UNITS_PLANNED",
      "DATE_COMPLETED",
      "NBR_UNITS_ACCOMPLISHED",
      "AGENCY_NAME",
      "DISTRICT_NAME",
      "ACTIVITY",
      "Season",
      "Dateplanned",
    ],
    cadenceHours: 6,
    coverage:
      "Oregon-intersecting units in the regional planning and accomplishment tracker.",
    limitations:
      "Contains planned, in-progress, monitoring, and completed statuses. In Progress does not establish that ignition has occurred. Units can disappear without cancellation.",
    verification: "queried",
    role: "primary",
  },
  ...[0, 1, 2, 3].map((layer): FireSource => ({
    id: `odf-${layer}`,
    name: `ODF ${layer < 2 ? "daily" : "three-day"} ${layer % 2 ? "accomplishments" : "plans"}`,
    agency: "ODF / registrants",
    url: "https://www.oregon.gov/odf/fire/pages/burn.aspx",
    endpoint: `https://gis.odf.oregon.gov/odfags/rest/services/Fire/Fire_Smoke_Management/FeatureServer/${layer}`,
    fields: odfFields,
    cadenceHours: 6,
    coverage:
      "Rolling forest-management smoke records; public locations are points.",
    limitations:
      "Not all Oregon burning or all burn permits. A unit may have multiple ignitions. Empty responses do not establish no burning. Daily feeds enrich the three-day feeds and are not counted again.",
    verification: "queried",
    role: layer < 2 ? "enrichment" : "primary",
  })),
  {
    id: "wfigs-perimeters",
    spatialEnvelope: [-124.9, 41.8, -116.3, 46.4],
    name: "WFIGS recent wildfire perimeters",
    agency: "NIFC",
    url: "https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/WFIGS_Interagency_Perimeters_YearToDate/FeatureServer/0",
    endpoint: "https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/WFIGS_Interagency_Perimeters_YearToDate/FeatureServer/0",
    where: `attr_IncidentTypeCategory = 'WF' AND attr_FireDiscoveryDateTime >= TIMESTAMP '${new Date().getFullYear()}-01-01 00:00:00'`,
    fields: ["OBJECTID", "GlobalID", "poly_IncidentName", "poly_GISAcres", "poly_DateCurrent", "poly_IRWINID", "attr_FireDiscoveryDateTime", "attr_FireOutDateTime", "attr_IncidentTypeCategory", "attr_POOState", "attr_POOLandownerCategory"],
    cadenceHours: 6,
    coverage: "Year-to-date wildfire perimeters intersecting Oregon; previous successful snapshots retained.",
    limitations: "Provisional boundaries can include unburned islands. Not all fires have a perimeter. Boundaries do not measure burn severity or ecological benefit.",
    verification: "queried",
    role: "primary",
  },
  ...[0, 1].map((layer): FireSource => ({
    id: `explorer-${layer}`,
    name: `Oregon Explorer ${layer ? "early" : "recent"} wildfire perimeters`,
    agency: "OSU INR",
    url: "https://services1.arcgis.com/CD5mKowwN6nIaqd8/arcgis/rest/services/library_env_or_wildfire_perimeter_history/FeatureServer",
    endpoint: `https://services1.arcgis.com/CD5mKowwN6nIaqd8/arcgis/rest/services/library_env_or_wildfire_perimeter_history/FeatureServer/${layer}`,
    cadenceHours: 720,
    coverage: layer
      ? "Historical perimeters before 2000."
      : "Compiled Oregon wildfire perimeters through 2025.",
    limitations:
      "Perimeter coverage is incomplete, especially for small and older fires. Perimeters and occurrence records are different views of fires, not additive counts.",
    verification: "queried",
    role: "primary",
  })),
  {
    id: "fod",
    name: "FPA FOD · seventh edition",
    agency: "USFS Research",
    url: "https://www.fs.usda.gov/rds/archive/catalog/RDS-2013-0009.7",
    coverage: "Cross-agency wildfire occurrences, 1992–2024; Oregon subset.",
    limitations:
      "Occurrence points can be approximate. The catalog map-service link still serves edition six; this importer requires the seventh-edition SQLite download.",
    verification: "queried",
    role: "primary",
  },
  {
    id: "wfigs",
    name: "WFIGS recent wildfire occurrences",
    agency: "NIFC / IRWIN",
    url: "https://data-nifc.opendata.arcgis.com/",
    endpoint:
      "https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/WFIGS_Incident_Locations_YearToDate/FeatureServer/0",
    where: "POOState='US-OR' AND IncidentTypeCategory='WF'",
    fields: [
      "OBJECTID",
      "IrwinID",
      "IncidentName",
      "IncidentTypeCategory",
      "FireDiscoveryDateTime",
      "FireOutDateTime",
      "ContainmentDateTime",
      "ControlDateTime",
      "IncidentSize",
      "DailyAcres",
      "CalculatedAcres",
      "POOCounty",
      "POOProtectingAgency",
      "POOJurisdictionalAgency",
      "ModifiedOnDateTime_dt",
      "IsValid",
      "IsQuarantined",
      "IsCpxChild",
      "CpxID",
    ],
    cadenceHours: 6,
    coverage:
      "Year-to-date wildfire occurrence reports; retained snapshots preserve our observed history.",
    limitations:
      "Operational records are provisional, not a complete statewide count. Fire points are not perimeters. Historical years after FOD coverage require additional archives.",
    verification: "queried",
    role: "primary",
  },
  {
    id: "sds",
    name: "ODF Smoke Data System history",
    agency: "ODF",
    url: "https://www.oregon.gov/odf/fire/pages/burn.aspx",
    coverage:
      "Historical registrations, authorizations and individual accomplishments to request.",
    limitations:
      "Export has not been received. No coverage inferred from annual totals.",
    verification: "discovered",
    role: "requested",
  },
  {
    id: "deq",
    name: "DEQ ecological burn permits",
    agency: "DEQ",
    url: "https://www.oregon.gov/deq/aq/pages/burning-101.aspx",
    coverage: "Habitat and wetland restoration permit records.",
    limitations:
      "Permit approval is not evidence a burn occurred. Records not yet obtained.",
    verification: "discovered",
    role: "requested",
  },
  {
    id: "lrapa",
    name: "LRAPA / Rivers to Ridges",
    agency: "LRAPA",
    url: "https://www.lrapa-or.gov/air-quality-protection/community-center/prescribed-burns/",
    coverage: "Lane County ecological burn permits and unit map.",
    limitations:
      "Underlying GIS and historical accomplishments not yet imported.",
    verification: "discovered",
    role: "requested",
  },
  {
    id: "oda",
    name: "Agricultural field burns",
    agency: "ODA",
    url: "https://www.oregon.gov/oda/agriculture-services/smoke-burning/pages/grower-resources.aspx",
    coverage:
      "Willamette Valley field registrations, daily permits and accomplishments.",
    limitations:
      "Records not yet obtained; not a statewide agricultural-burning census.",
    verification: "discovered",
    role: "requested",
  },
];
export const SOURCE_BY_ID = Object.fromEntries(
  FIRE_SOURCES.map((s) => [s.id, s]),
);
export const WOODPECKER = {
  title: "Two small burns. Two different restoration goals.",
  url: "https://www.forestry.oregonstate.edu/news/fire-purpose",
  attribution: "Oregon State University College of Forestry · April 3, 2026",
  body: "In October 2025, students burned two units in the Woodpecker Harvest at McDonald-Dunn Research Forest. One was selected to release Oregon white oak and Pacific madrone; the other supported Willamette Valley ponderosa pine. OSU describes patchy burning in damp fuels and the importance of planning with nearby residents. This is a documented site-selection explanation—not just a general purpose code.",
};
