/**
 * Where every table behind /dashboard/homelessness comes from, and how to refresh it.
 *
 * This is the registry the freshness check reads (check-freshness.ts). Update an
 * entry whenever a table is reloaded: `loadedThrough` is the newest period in the
 * database, `refreshedOn` the date it was loaded. Human-readable version, with
 * the refresh steps: SOURCES.md in this folder.
 */

export type Cadence = "nightly" | "monthly" | "quarterly" | "annual" | "biennial" | "irregular";

export type Dataset = {
  table: string;
  what: string;
  publisher: string;
  /** The exact page or file the figures are read from. */
  url: string;
  format: string;
  cadence: Cadence;
  /** Months between the end of a period and its publication, roughly. */
  publicationLagMonths: number;
  /** SQL expression giving the newest period in the table, as text. Null when the table has no period column. */
  periodSql: string | null;
  /** Newest period loaded, as last recorded by hand. */
  loadedThrough: string;
  refreshedOn: string;
  /** How to refresh: a script, or "manual" with the steps in SOURCES.md. */
  refresh: string;
  notes?: string;
};

export const DATASETS: Dataset[] = [
  {
    table: "homelessness.pit_counts",
    what: "Point-in-Time count, OR-501 (Multnomah County), full-count years only",
    publisher: "HUD (from Multnomah County's submission)",
    url: "https://files.hudexchange.info/reports/published/CoC_PopSub_CoC_OR-501-{YEAR}_OR_{YEAR}.pdf",
    format: "PDF, 'Homeless Populations and Subpopulations'",
    cadence: "biennial",
    publicationLagMonths: 11,
    periodSql: "max(year)::text",
    loadedThrough: "2025",
    refreshedOn: "2026-10-07",
    refresh: "manual: add the year's row to PIT_FULL_COUNTS in ingest/fix-homelessness-pit-2026-10.ts and run it with --apply",
    notes: "Full counts in odd years (2022 also). Sheltered-only years (2020, 2021, 2024) are excluded because HUD carries the unsheltered figure forward. Next full count: January 2027; HUD report usually posted by the following December.",
  },
  {
    table: "homelessness.by_name_list",
    what: "Multnomah County by-name list, monthly total",
    publisher: "Multnomah County Homeless Services Department",
    url: "https://hsd.multco.us/data-dashboard/",
    format: "Tableau Public dashboard (downloads disabled); values read from the published edition",
    cadence: "monthly",
    publicationLagMonths: 2,
    periodSql: "to_char(max(month), 'YYYY-MM')",
    loadedThrough: "2026-03",
    refreshedOn: "2026-10-07",
    refresh: "manual: transcribe the new edition's monthly totals into BY_NAME_TOTALS in ingest/fix-homelessness-pit-2026-10.ts and run with --apply",
    notes: "January 2024 to October 2025 come from the county's October 2025 dashboard edition; March 2026 (18,480) from the county's June 2026 KPI deck (ingest/homelessness/refresh-2026-10-07.ts). Offline for maintenance as of 2026-10-07; HSD was asked on 2026-10-08 when it returns and how often it will update. The county will restate the series back to January 2024 under a 60-to-90-day inactivity rule (about 20% lower); replace every month when it returns. Each edition can change earlier months.",
  },
  {
    table: "homelessness.statewide_pit_by_county",
    what: "2025 Point-in-Time count by Oregon county",
    publisher: "PSU Homelessness Research & Action Collaborative",
    url: "https://pdxscholar.library.pdx.edu/hrac_pub/53/",
    format: "PDF report (PDXScholar download is bot-gated; read from pdx.edu summaries and the report when available)",
    cadence: "biennial",
    publicationLagMonths: 12,
    periodSql: "max(year)::text",
    loadedThrough: "2025",
    refreshedOn: "before 2026-09-06",
    refresh: "manual: ingest/seed-statewide-homelessness.ts",
    notes: "Also feeds shelter_bed_inventory, racial_disparities, statewide_unsheltered_change and several context_stats rows. HRAC's Multnomah shelter-bed figure (4,008) differs from HUD's 2025 Housing Inventory Count (4,187); unresolved.",
  },
  {
    table: "homelessness.irp_campsite_reports",
    what: "City of Portland campsite reports (Impact Reduction Program)",
    publisher: "City of Portland, PortlandMaps open data",
    url: "https://www.portlandmaps.com/od/rest/services/COP_OpenData_Miscellaneous/MapServer/1396/query",
    format: "ArcGIS REST feature service",
    cadence: "nightly",
    publicationLagMonths: 0,
    periodSql: "to_char(max(item_date), 'YYYY-MM-DD')",
    loadedThrough: "2026-10-06",
    refreshedOn: "2026-10-07",
    refresh: "automated: /api/cron/sync-campsites (daily 05:45 UTC); manual: ingest/sync-irp-campsites.ts; full rebuild: ingest/rebuild-irp-campsites-2026-10.ts",
    notes: "Keyed on report_id. The feed's OBJECTID is renumbered when the city republishes; tracking progress by it stopped all loading from April 15 to October 7, 2026. The feed holds reports from December 31, 2024 on; older rows are not republished.",
  },
  {
    table: "homelessness.eviction_filings",
    what: "Eviction cases filed by month: Multnomah, Washington, Clackamas, Oregon",
    publisher: "Evicted in Oregon (PSU), from Oregon Judicial Department circuit-court records",
    url: "https://datawrapper.dwcdn.net/0Ofed/",
    format: "Datawrapper CSV, newest version via the unversioned URL; months dated from the period on the chart page",
    cadence: "monthly",
    publicationLagMonths: 2,
    periodSql: "to_char(max(month), 'YYYY-MM')",
    loadedThrough: "2026-08",
    refreshedOn: "2026-10-07",
    refresh: "script: npx tsx ingest/fetch-hsd-dashboard.ts --apply (dry run without --apply)",
    notes: "Updated around the 15th of each month; recent months get revised, so each run rewrites the whole twelve-month window. Full calendar years: --calendar-year (chart vlDrt). Rows before Oct. 7, 2026 were one month late from a parsing bug; Jan. 2025 on were reloaded. Circuit courts only (about 90% of cases). The annual filing rate per 100 rental units is a separate chart (cbJjQ) and is not stored per month.",
  },
  {
    table: "homelessness.shelter_capacity",
    what: "Average county-funded shelter capacity and occupancy, by fiscal quarter",
    publisher: "Multnomah County Homeless Services Department, quarterly data dashboard",
    url: "https://hsd.multco.us/quarterly-data-dashboard/",
    format: "Chart.js data embedded in the page (chart-1324 capacity, chart-1370 occupancy)",
    cadence: "irregular",
    publicationLagMonths: 0,
    periodSql: "max(quarter)",
    loadedThrough: "FY2024 Q4 (Apr-Jun 2024)",
    refreshedOn: "2026-10-07",
    refresh: "manual: ingest/homelessness/refresh-2026-10-07.ts holds the series; extend it if the dashboard ever updates",
    notes: "The dashboard has not changed since April 16, 2025. Newer shelter figures exist only in other measures (SHS-funded units in the quarterly SHS reports at https://hsd.multco.us/reports/; the county's 1,742 units or 1,667 beds after the FY2027 cuts), so they are not mixed into this series.",
  },
  {
    table: "homelessness.housing_placements",
    what: "People placed into housing per fiscal year, system-wide, with SHS-funded PSH and RRH",
    publisher: "Multnomah County (annual release) and HSD SHS annual report",
    url: "https://hsd.multco.us/reports/",
    format: "PDF annual report and news release",
    cadence: "annual",
    publicationLagMonths: 5,
    periodSql: "max(fiscal_year)",
    loadedThrough: "FY2025",
    refreshedOn: "2026-10-07",
    refresh: "manual: add the fiscal year's row from the November annual report",
    notes: "FY2026 final numbers are due in November 2026 (preliminary SHS placements: 1,390 people).",
  },
  {
    table: "homelessness.shs_funding",
    what: "Supportive Housing Services tax: regional gross collections and regional county program spending, by fiscal year (year = the June it ends)",
    publisher: "Metro",
    url: "https://www.oregonmetro.gov/what-metro-does/housing-and-homelessness/supportive-housing-services/funding",
    format: "PDF annual reports, quarterly financial reports and the September year-end memo",
    cadence: "annual",
    publicationLagMonths: 3,
    periodSql: "max(year)::text",
    loadedThrough: "2026",
    refreshedOn: "2026-10-07",
    refresh: "manual: ingest/homelessness/refresh-2026-10-07.ts (SHS_FUNDING); replace FY2026 with audited figures from the next annual report",
    notes: "FY2026 collections ($357.3M) are unaudited and include about $36M of one-time late payments; FY2026 spending is preliminary. Every figure is regional (three counties).",
  },
  {
    table: "homelessness.overdose_deaths",
    what: "Deaths of people experiencing homelessness, overdose and fentanyl deaths",
    publisher: "Multnomah County Health Department, Domicile Unknown",
    url: "https://multco.us/info/domicile-unknown",
    format: "PDF annual report",
    cadence: "annual",
    publicationLagMonths: 12,
    periodSql: "max(year)::text",
    loadedThrough: "2024",
    refreshedOn: "before 2026-09-06",
    refresh: "manual: ingest/seed-homelessness.ts (overdose rows)",
    notes: "The 2025 report is expected about December 2026.",
  },
  {
    table: "homelessness.affordable_housing_vacancy",
    what: "Home Forward (Portland's housing authority) vacancy",
    publisher: "Home Forward performance dashboard; earlier figures from reporting",
    url: "https://www.homeforward.org/performance-dashboard/",
    format: "Power BI dashboard (needs a browser); current value only, so each reading must be saved to keep history",
    cadence: "monthly",
    publicationLagMonths: 1,
    periodSql: "to_char(max(as_of), 'YYYY-MM')",
    loadedThrough: "2026-10",
    refreshedOn: "2026-10-07",
    refresh: "manual: read the dashboard in a browser, save a screenshot to the source archive, add a row",
    notes: "The dashboard reports occupancy; vacancy is stored as 100 minus occupancy.",
  },
  {
    table: "homelessness.doubled_up",
    what: "People doubled up (ACS-based estimate)",
    publisher: "PSU HRAC, from Census ACS 1-year microdata",
    url: "https://www2.census.gov/programs-surveys/acs/data/pums/2025/1-Year/",
    format: "Census PUMS microdata; HRAC method",
    cadence: "annual",
    publicationLagMonths: 21,
    periodSql: "max(year)::text",
    loadedThrough: "2024",
    refreshedOn: "before 2026-09-06",
    refresh: "manual: ingest/seed-statewide-homelessness.ts",
    notes: "The 2025 ACS 1-year release is delayed (Commerce disclosure-avoidance order); watch for the PUMS folder to stop returning 404.",
  },
  {
    table: "homelessness.shs_by_county",
    what: "SHS allocation, spending and households placed, by county and fiscal year",
    publisher: "Metro and the three counties' SHS reports",
    url: "https://www.oregonmetro.gov/what-metro-does/housing-and-homelessness/supportive-housing-services/funding",
    format: "PDF reports",
    cadence: "annual",
    publicationLagMonths: 5,
    periodSql: "max(fiscal_year)",
    loadedThrough: "FY2026",
    refreshedOn: "before 2026-09-06",
    refresh: "manual: ingest/seed-homelessness.ts",
    notes: "Not re-checked in the October 2026 refresh.",
  },
  {
    table: "homelessness.shs_spending_by_type",
    what: "SHS spending and placements by intervention type",
    publisher: "Multnomah County HSD SHS annual report",
    url: "https://hsd.multco.us/reports/",
    format: "PDF annual report",
    cadence: "annual",
    publicationLagMonths: 5,
    periodSql: "max(fiscal_year)",
    loadedThrough: "FY2025",
    refreshedOn: "before 2026-09-06",
    refresh: "manual: ingest/seed-homelessness.ts",
    notes: "Not re-checked in the October 2026 refresh; FY2026 annual report due November 2026.",
  },
  {
    table: "homelessness.student_homelessness",
    what: "K-12 students experiencing homelessness by county (McKinney-Vento)",
    publisher: "Oregon Department of Education",
    url: "https://www.oregon.gov/ode/schools-and-districts/reportcards/",
    format: "Spreadsheet",
    cadence: "annual",
    publicationLagMonths: 6,
    periodSql: null,
    loadedThrough: "2024-25 school year",
    refreshedOn: "before 2026-09-06",
    refresh: "manual: ingest/seed-statewide-homelessness.ts",
  },
  {
    table: "homelessness.racial_disparities, shelter_bed_inventory, statewide_unsheltered_change",
    what: "2025 statewide tables from HRAC's statewide estimates",
    publisher: "PSU Homelessness Research & Action Collaborative",
    url: "https://pdxscholar.library.pdx.edu/hrac_pub/53/",
    format: "PDF report",
    cadence: "biennial",
    publicationLagMonths: 12,
    periodSql: null,
    loadedThrough: "2025",
    refreshedOn: "before 2026-09-06",
    refresh: "manual: ingest/seed-statewide-homelessness.ts",
    notes: "HRAC's Multnomah shelter-bed figure (4,008) differs from HUD's 2025 inventory (4,187); not yet reconciled.",
  },
  {
    table: "homelessness.context_stats",
    what: "Single figures quoted on the page (51 metrics), each with its own source and date",
    publisher: "Various; each row names its source",
    url: "(per row)",
    format: "Hand-entered",
    cadence: "irregular",
    publicationLagMonths: 0,
    periodSql: null,
    loadedThrough: "per row (as_of_date)",
    refreshedOn: "2026-10-07 (city_overnight_beds only)",
    refresh: "manual: ingest/seed-homelessness.ts, ingest/seed-statewide-homelessness.ts; one-off fixes in refresh scripts",
    notes: "Audit row by row when time allows. city_overnight_beds held the city's 1,566-bed goal until October 7, 2026.",
  },
  {
    table: "homelessness.data_sources, data_disputes",
    what: "The page's own list of data sources and their update dates, and the city-county data dispute",
    publisher: "Portland Civic Lab",
    url: "(this registry)",
    format: "Hand-entered",
    cadence: "irregular",
    publicationLagMonths: 0,
    periodSql: null,
    loadedThrough: "2026-10-07",
    refreshedOn: "2026-10-07",
    refresh: "manual: ingest/seed-data-transparency.ts; keep last_updated and next_expected in step with the rows above",
  },
];
