import { test, expect } from "@playwright/test";
for (const district of [3, 4]) {
  test(`district ${district}: mobile sections, profiles and browser Back keep context`, async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`/voters-guide/portland-district-${district}`);
    await page.getByRole("button", { name: "Meet all candidates", exact: true }).click();
    const navigation = page.getByRole("navigation", { name: "Race guide sections" });
    await expect(navigation).toBeInViewport({ ratio: 1 });
    await expect(page.locator("#compare")).toBeHidden();
    await expect(page.locator("#disagreements")).toBeHidden();
    await expect(page.locator("article:visible")).toHaveCount(0);
    await expect(page.locator("[data-candidate]:visible")).toHaveCount(4);
    await page.getByRole("navigation", { name: "Candidate pages", exact: true }).getByRole("button", { name: "Next →" }).click();
    const names = await page.locator("[data-candidate] h3").allTextContents();
    const link = page.locator("[data-candidate]").first().getByRole("link", { name: "Full profile & record →" });
    const id = await link.getAttribute("href");
    await link.click();
    await expect(page.locator("article:visible")).toHaveCount(1);
    await expect(page.locator(id!)).toBeVisible();
    await expect(page.locator("#find-candidates")).toBeHidden();
    await page.goBack();
    await expect(page.locator("#find-candidates")).toBeVisible();
    expect(await page.locator("[data-candidate] h3").allTextContents()).toEqual(names);
    await navigation.getByRole("link", { name: "Compare", exact: true }).click();
    await expect(page.locator("#compare")).toBeVisible();
    await expect(page.locator("#find-candidates")).toBeHidden();
    await navigation.getByRole("link", { name: "Council record" }).click();
    await expect(page.locator("#disagreements")).toBeVisible();
    await expect(page.locator("#compare")).toBeHidden();
    await navigation.getByRole("link", { name: "About", exact: true }).click();
    await expect(page.locator("#about-guide")).toBeVisible();
    await expect(page.locator("#disagreements")).toBeHidden();
    await expect(navigation).toBeInViewport({ ratio: 1 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.goto(`/voters-guide/portland-district-${district}${id}`);
    await expect(page.locator(id!)).toBeVisible();
    await expect(page.locator("article:visible")).toHaveCount(1);
    await page.emulateMedia({ media: "print" });
    await expect(page.locator("article:visible")).toHaveCount(district === 3 ? 21 : 12);
    await expect(page.locator("#disagreements")).toBeVisible();
    await expect(page.locator("#about-guide")).toBeVisible();
    await expect(navigation).toBeHidden();
  });
}
test("persistent Compare carries selections without browser storage and controls do not overlap", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 700 });
  await page.addInitScript(() => Object.defineProperty(window, "sessionStorage", { get() { throw new Error("disabled"); } }));
  await page.goto("/voters-guide/portland-district-4");
    await page.getByRole("button", { name: "Meet all candidates", exact: true }).click();
  const guide = page.locator("#find-candidates");
  await guide.getByRole("button", { name: /Select .* for quick comparison/ }).first().click();
  await guide.getByRole("button", { name: /Select .* for quick comparison/ }).first().click();
  const action = guide.getByRole("button", { name: "Compare these two →" });
  const nav = page.getByRole("navigation", { name: "Race guide sections" });
  await expect(action).toBeInViewport({ ratio: 1 });
  const actionBox = (await action.boundingBox())!;
  const navBox = (await nav.boundingBox())!;
  expect(actionBox.y + actionBox.height).toBeLessThanOrEqual(navBox.y);
  await nav.getByRole("link", { name: "About", exact: true }).click();
  await nav.getByRole("link", { name: "Compare", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Candidate 1", exact: true })).not.toHaveValue("");
  await expect(page.getByRole("combobox", { name: "Candidate 2", exact: true })).not.toHaveValue("");
  await expect(page.locator("#compare").getByRole("region", { name: /comparison$/ })).toHaveCount(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("button", { name: "+ Add a third candidate" }).click();
  await page.getByRole("combobox", { name: "Candidate 3", exact: true }).selectOption("olivia-clark");
  await nav.getByRole("link", { name: "About", exact: true }).click();
  await nav.getByRole("link", { name: "Compare", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Candidate 3", exact: true })).toHaveValue("olivia-clark");
  await page.setViewportSize({ width: 1365, height: 900 });
  await expect(nav).toBeInViewport({ ratio: 1 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
