import {
  candidate as c,
  electionSource,
  officialSources,
  pamphletSource as p,
  type Candidate,
  type Geography,
  type Race,
} from "./types";
const m = (n: number) => [p("multnomah", n)];
const w = (n: number) => [p("washington", n)];
const k = (n: number) => [p("clackamas", n)];
const certified = (city: string) =>
  `https://www.washingtoncountyor.gov/elections/documents/city-${city}-certified-candidates-nov-2026/download?inline`;
const gresham = "https://www.greshamoregon.gov/government/elections/";
const oregonCity = "https://www.orcity.org/3547/Current-Candidates";
function missing(name: string, url: string): Candidate {
  return {
    ...c(
      name,
      "Listed by the city’s election authority.",
      "A current policy brief has not yet been completed.",
      [],
      "The absence of a reviewed statement is a research gap, not evidence that this candidate lacks positions.",
      "What changes would you make, what would they cost, and how would residents measure the result?",
      [electionSource("Official candidate list", url)],
    ),
    missing:
      "No candidate statement was found in the pamphlet pages reviewed. Campaign, interview and public-record research remains open.",
  };
}
function cityRace(
  id: string,
  title: string,
  geography: Geography,
  jurisdiction: string,
  rosterUrl: string,
  comparison: string,
  candidates: Candidate[],
  seats = 1,
): Race {
  return {
    id,
    title,
    geography,
    jurisdiction,
    candidates,
    seats,
    method: `Vote for ${seats === 1 ? "one" : `up to ${seats}`}`,
    authority:
      "The mayor and council set city policy, adopt the budget and oversee the city manager. One member cannot enact a proposal alone. Schools, transit and county health services involve separate governing bodies.",
    stakes:
      "Housing and development, public safety, streets, utilities, parks and the cost and accountability of city services.",
    comparison,
    rosterStatus: "Official list checked",
    rosterSource: electionSource(
      "City election authority · qualified candidates",
      rosterUrl,
    ),
  };
}
export const cityRaces: Race[] = [
  cityRace(
    "gresham-mayor",
    "Gresham Mayor",
    "Multnomah",
    "City of Gresham",
    gresham,
    "Both candidates prioritize police, fire and business growth. Stovall emphasizes continuing investments and youth programs; Piazza emphasizes a leadership change, spending scrutiny and limiting fees.",
    [
      c(
        "Travis Stovall",
        "Incumbent mayor and business owner.",
        "Supports continued public-safety investment, youth opportunities, housing-focused outreach and attracting family-wage employers.",
        [
          "Support police and fire capacity.",
          "Expand youth mentoring and employment opportunities.",
          "Connect unhoused people with shelter and mental-health care while maintaining public spaces.",
        ],
        "He seeks continuity around investment and partnerships. Claimed reductions in poverty and other outcomes require independent checks before assigning credit.",
        "Which investments would your next budget prioritize, and how would you measure their results?",
        m(41),
      ),
      c(
        "Sue Piazza",
        "City councilor, business coach and travel consultant.",
        "Emphasizes public safety, spending discipline and creating conditions for local businesses to grow.",
        [
          "Reduce unnecessary costs and fees.",
          "Prioritize police and fire services and address encampments in public spaces.",
          "Attract employers and good-paying jobs.",
        ],
        "Her program places more emphasis on management change and cost control. The statement does not specify the savings or service tradeoffs.",
        "Which fees and expenditures would you reduce, and what services would be protected?",
        m(41),
      ),
    ],
  ),
  cityRace(
    "gresham-position-2",
    "Gresham Council · Position 2",
    "Multnomah",
    "City of Gresham",
    gresham,
    "Compare how the candidates would combine public-safety spending, housing development and budget discipline.",
    [
      c(
        "Heather Coleman-Cox",
        "Network engineer; school-board director and city advisory-committee leader.",
        "Proposes public-safety investment, neighborhood redevelopment and more opportunities for local businesses.",
        [
          "Put vacant properties back into use and expand housing choices.",
          "Invest in utilities and parks.",
          "Support first responders and community approaches to safety.",
        ],
        "She connects housing and infrastructure investment to economic opportunity. Implementation requires choices among competing capital needs.",
        "Which vacant-property or infrastructure initiative would you prioritize and fund first?",
        m(42),
      ),
      c(
        "Will DelPlato",
        "Retired nurse, healthcare leader and Army veteran.",
        "Proposes early spending adjustments and more efficient permitting, alongside support for first responders.",
        [
          "Review programs for efficiency and accountability.",
          "Streamline permitting for businesses.",
          "Prioritize affordability, safety and economic growth.",
        ],
        "His central premise is that earlier, smaller budget changes can prevent larger future cuts. The statement does not quantify those adjustments.",
        "What specific budget changes would you propose in your first year?",
        m(42),
      ),
    ],
  ),
  cityRace(
    "gresham-position-4",
    "Gresham Council · Position 4",
    "Multnomah",
    "City of Gresham",
    gresham,
    "The candidates share broad affordability goals but emphasize different tools: infrastructure planning, emergency resilience, recovery services, and workforce pathways.",
    [
      c(
        "Gregory Schroeder",
        "Infrastructure program manager and planning commissioner.",
        "Connects housing, transportation, jobs and natural spaces through long-term planning.",
        [
          "Attract jobs that let residents work near home.",
          "Combine housing growth with transportation, parks and neighborhood investment.",
          "Strengthen youth opportunities.",
        ],
        "He emphasizes coordination across systems and the long-term consequences of development decisions.",
        "Which infrastructure investment would produce the greatest near-term benefit, and how would it be paid for?",
        m(43),
      ),
      c(
        "Krestina Aziz",
        "Court interpreter and business owner with architecture and engineering experience.",
        "Emphasizes emergency resilience, better public information and carefully timed development.",
        [
          "Improve hazardous-material and earthquake preparedness.",
          "Increase transparency around the water-system transition.",
          "Support higher-wage jobs and development at an appropriate scale.",
        ],
        "Her statement makes resilience and communication central tests of city performance.",
        "What preparedness gaps would you address first, and what public reporting would you require?",
        m(43),
      ),
      c(
        "Joshua Al-jaouni",
        "Pastor and small-business owner with nonprofit and youth-mentoring experience.",
        "Supports limiting unnecessary costs, strengthening first responders and expanding treatment and recovery.",
        [
          "Keep additional fees and costs off working households where possible.",
          "Support treatment and pathways to self-sufficiency.",
          "Promote local businesses and tourism.",
        ],
        "The program combines growth and enforcement with support services. Specific funding mechanisms remain to be established.",
        "How would you expand services while limiting fees, and which results would determine continued funding?",
        m(44),
      ),
      c(
        "Teo Ramirez",
        "Local-government analyst and former Gresham community-engagement coordinator.",
        "Emphasizes workforce pathways, housing stability and accountability for city programs.",
        [
          "Expand apprenticeships and youth opportunities.",
          "Support small businesses and responsible local investment.",
          "Involve residents earlier and measure program results.",
        ],
        "He treats employment access and accountable implementation as connected parts of economic stability.",
        "Which program would you expand first, with what cost and public performance measure?",
        m(44),
      ),
    ],
  ),
  cityRace(
    "gresham-position-6",
    "Gresham Council · Position 6",
    "Multnomah",
    "City of Gresham",
    gresham,
    "Gladfelter emphasizes continuity in public safety, outreach and economic development. Miller’s policy brief remains incomplete.",
    [
      c(
        "Janine Gladfelter",
        "Incumbent councilor and business relationship manager.",
        "Supports public-safety capacity, housing-focused outreach with code enforcement, and redevelopment of underused areas.",
        [
          "Restore specialty public-safety teams.",
          "Strengthen seven-day housing outreach.",
          "Support small businesses and growth that preserves trees and neighborhood quality.",
        ],
        "Her case emphasizes continuity during city leadership changes. The campaign’s staffing and levy claims need separate verification.",
        "How would you measure the combined effects of outreach and enforcement, and fund continued staffing?",
        m(45),
      ),
      missing("Daniel Miller", gresham),
    ],
  ),
  cityRace(
    "beaverton-position-1",
    "Beaverton Council · Position 1",
    "Washington",
    "City of Beaverton · November runoff",
    officialSources.washington,
    "Both candidates favor housing choices and safer streets. Kocher also specifies tax referendums and removing Flock cameras; Philip stresses budget oversight and resilient infrastructure.",
    [
      c(
        "Evelyn Kocher",
        "Latino Network communications manager; former Oregon Student Association director.",
        "Supports mixed-use housing near transit, stronger protections for immigrants and changes to local surveillance and taxation.",
        [
          "Streamline multifamily development near MAX.",
          "Put new council tax proposals to voters.",
          "Remove Flock cameras and expand South Cooper Mountain transit access.",
        ],
        "The platform combines more housing and transit with explicit limits on surveillance and how new taxes are adopted. Transit expansion also requires regional partners.",
        "How would you replace any affected public-safety tools and fund transit expansion?",
        w(9),
      ),
      c(
        "Rachel Philip",
        "Software developer and former auditor; city budget and neighborhood-committee experience.",
        "Emphasizes housing choice, safer streets, fiscal oversight and preparedness for climate-related emergencies.",
        [
          "Expand apartments, townhomes and starter homes.",
          "Prioritize safe school routes and traffic calming.",
          "Protect essential services, trees and green spaces.",
        ],
        "Her approach puts infrastructure and budget management at the center of affordability and safety.",
        "Which street and housing investments would receive priority, and how would you cover their costs?",
        w(9),
      ),
    ],
  ),
  cityRace(
    "hillsboro-ward-1",
    "Hillsboro Council · Ward 1, Position A",
    "Washington",
    "City of Hillsboro",
    certified("hillsboro"),
    "A central distinction is how candidates would condition industrial growth: measurable community benefits, resource stewardship, infrastructure cost recovery, or ending data-center tax breaks.",
    [
      c(
        "Cristian Salgado",
        "Appointed city councilor and small-business owner.",
        "Supports investment conditioned on neighborhood, infrastructure and affordability benefits.",
        [
          "Scrutinize data-center impacts and utility costs.",
          "Invest in safe streets and reliable services.",
          "Connect growth with local jobs, training and small businesses.",
        ],
        "He supports growth while calling for stronger tests of who benefits. The enforceable conditions matter more than the general label of responsible growth.",
        "Which conditions would you require of a new data center, and what would cause you to reject it?",
        w(15),
      ),
      c(
        "Luis Garcia",
        "Health-information systems designer with technology and volunteer experience.",
        "Emphasizes sound infrastructure, resource protection and decisions grounded in scientific and financial evidence.",
        [
          "Prioritize roads, water and affordable housing.",
          "Protect farmland from semiconductor and data-center impacts.",
          "Improve accountability and planning for growth.",
        ],
        "The platform stresses decision quality and stewardship rather than a categorical prohibition on development.",
        "What evidence and thresholds would determine your vote on a major industrial project?",
        w(15),
      ),
      c(
        "Sarah Marugg",
        "Revenue and tax specialist with municipal compliance experience.",
        "Supports housing growth while requiring large industries to cover impacts and protecting natural resources.",
        [
          "Require data centers to pay their infrastructure and service costs.",
          "Protect farmland, wetlands, air and water.",
          "Improve pedestrian safety, accessibility and civil-rights protections.",
        ],
        "Her approach makes cost recovery and environmental protection conditions of growth. The level and legal mechanism of charges remain important details.",
        "How would you calculate a data center’s full public cost and enforce payment?",
        w(16),
      ),
      c(
        "Diana Jackson",
        "Public-defense legal assistant and planning commissioner.",
        "Emphasizes renter affordability, small-business development and opposition to data-center tax breaks.",
        [
          "Support housing affordability as a basic need.",
          "Redirect economic-development attention toward small businesses.",
          "Close service-access gaps and protect immigrant residents.",
        ],
        "She questions the distribution of the benefits of industrial growth. Her statement does not yet supply a detailed housing financing plan.",
        "Which housing and incentive changes would you enact first, and what would replace foregone investment or revenue?",
        w(16),
      ),
    ],
  ),
  cityRace(
    "hillsboro-ward-2",
    "Hillsboro Council · Ward 2, Position A",
    "Washington",
    "City of Hillsboro",
    certified("hillsboro"),
    "Pantoja emphasizes schools, employers and family stability. Delgado calls for specific changes to corporate incentives, immigrant services and public participation.",
    [
      c(
        "Ivette Pantoja",
        "Preschool owner and former Hillsboro school-board chair.",
        "Emphasizes affordable homes, employment, small-business opportunity and safety for families.",
        [
          "Support employers and jobs that benefit working households.",
          "Expand access to affordable homes.",
          "Protect residents’ safety and dignity.",
        ],
        "She offers education and childcare experience as preparation for council service. Claimed school outcomes are campaign assertions pending independent review.",
        "Which city housing and childcare measures would you prioritize, and how would you fund them?",
        w(17),
      ),
      c(
        "Karim Delgado",
        "Business owner, former teacher and Marine veteran.",
        "Wants public incentives tied to greater public benefits and more direct support for immigrant residents.",
        [
          "Fund legal and emergency aid and establish a Human Rights Office.",
          "Enforce local sanctuary protections.",
          "Hold weekly town halls and virtual office hours.",
        ],
        "His approach would condition business incentives more tightly and expand city support services. His numerical claims about tax exemptions and utility impacts need separate checks.",
        "What enforceable public benefits would you require for incentives, and what would the new office cost?",
        w(17),
      ),
    ],
  ),
  cityRace(
    "hillsboro-ward-3",
    "Hillsboro Council · Ward 3, Position A",
    "Washington",
    "City of Hillsboro",
    certified("hillsboro"),
    "Wallace emphasizes jobs, housing and infrastructure. Russell foregrounds youth stability, worker benefits and limits on industrial impacts. Culbertson’s substantive brief remains open.",
    [
      c(
        "Titonian Wallace Sr.",
        "Small-business owner, rideshare driver and former community-college instructor.",
        "Supports local economic development, housing opportunities and investment in safe neighborhoods.",
        [
          "Connect development with jobs benefiting current residents.",
          "Improve transportation and public spaces.",
          "Expand housing options for families and seniors.",
        ],
        "The statement gives a broad direction for growth and affordability but few detailed financing or regulatory proposals.",
        "Which housing and infrastructure changes would you prioritize in the next budget?",
        w(18),
      ),
      c(
        "Dorian Russell",
        "HomePlate Youth Services executive director; education-service board member.",
        "Connects affordability and youth wellbeing with worker benefits, environmental protection and civil rights.",
        [
          "Protect farms, nature and residents from unchecked data-center expansion.",
          "Support living wages and stable benefits.",
          "Make local government responsive to community needs and immigrant protections.",
        ],
        "Russell asks whether economic growth produces material security for residents. Specific legal and budget mechanisms still need fuller review.",
        "What data-center conditions and youth-service investments would you propose first?",
        w(18),
      ),
      missing("Kimberly Culbertson", certified("hillsboro")),
    ],
  ),
  cityRace(
    "tigard-mayor",
    "Tigard Mayor",
    "Washington",
    "City of Tigard",
    certified("tigard"),
    "Hu emphasizes continuity after leadership and budget changes. Monahan argues the city needs a different approach to facilities planning and affordability.",
    [
      c(
        "Yi-Kang Hu",
        "Incumbent mayor and attorney; former research scientist.",
        "Supports more housing choices, easier business processes and reliable city services.",
        [
          "Control resident costs through budgeting.",
          "Revitalize downtown and commercial districts.",
          "Improve transportation safety, parks and library services.",
        ],
        "He presents continuity and regional relationships as tools for implementation. Claims about closing the budget gap require checking against adopted financial records.",
        "What recurring budget choices would sustain services without new shortfalls?",
        w(35),
      ),
      c(
        "Bill Monahan",
        "Former Tigard and Milwaukie city manager; attorney and consultant.",
        "Calls for less expensive police-facility solutions, transparent financial analysis and core-service affordability.",
        [
          "Reassess police-facility plans.",
          "Tie project decisions to reliable needs and cost estimates.",
          "Improve council, staff and community relationships.",
        ],
        "His case centers on changing how major capital commitments are planned and explained. His criticism of previous decisions is attributed to his statement, not independently adjudicated here.",
        "What facility alternative would you propose, and what is its full construction and operating cost?",
        w(35),
      ),
    ],
  ),
  cityRace(
    "tigard-council",
    "Tigard City Council",
    "Washington",
    "City of Tigard · three seats",
    certified("tigard"),
    "Look beyond shared affordability language: candidates propose different combinations of spending limits, housing rules, public-land partnerships, street investments and service protection.",
    [
      c(
        "John Goodhouse",
        "Insurance-business owner and former councilor.",
        "Emphasizes business activity, police, more efficient homebuilding and transportation connections.",
        [
          "Streamline housing development.",
          "Support downtown events and businesses.",
          "Improve sidewalks, cycling connections and traffic movement.",
        ],
        "His approach links economic activity and development efficiency to affordability and city revenues.",
        "Which permitting changes would reduce costs without shifting infrastructure costs onto existing residents?",
        w(36),
      ),
      c(
        "Sue Garino",
        "Retired Tigard police-department employee and former union board member.",
        "Prioritizes essential services, restrained costs and more responsive city administration.",
        [
          "Limit growth in taxes, fees and spending.",
          "Avoid financing ongoing programs with one-time money.",
          "Improve accessible housing and transportation for older residents.",
        ],
        "Her program emphasizes recurring financial sustainability and service delivery. Specific spending reductions remain to be identified.",
        "Which spending would you reduce first, and what level of service would residents receive?",
        w(36),
      ),
      c(
        "Gabriel Elijio Velasquez",
        "Healthcare worker and Town Center Advisory Commission chair.",
        "Supports stronger limits on corporate homebuying, connected streets and redevelopment of underused parking.",
        [
          "Expand restrictions on corporate purchases of single-family homes.",
          "Build protected cycling routes and continuous sidewalks.",
          "Allow more housing and small-business uses on underused lots.",
        ],
        "He combines restrictions on housing ownership with more flexible development rules. The legal scope and practical effects of the proposed purchase limits need scrutiny.",
        "What purchase restriction is legally available to the city, and how would you measure its effect on prices?",
        w(37),
      ),
      c(
        "Jeff Darland",
        "Former engineering leader and city budget-committee member.",
        "Proposes clearer financial information, permanently affordable housing and development that covers its infrastructure costs.",
        [
          "Explain utility rates and debt in plain language.",
          "Use public-land partnerships and community land trusts.",
          "Require growth to contribute its share of public costs.",
        ],
        "He distinguishes lasting affordability from simply adding units and emphasizes transparent allocation of development costs.",
        "Which public land and financing would support a land-trust project, and at what scale?",
        w(37),
      ),
      c(
        "Tom Anderson",
        "City councilor and real-estate broker.",
        "Supports entry-level housing, workforce development, better roads and sustained public services.",
        [
          "Encourage starter and middle housing.",
          "Pursue transfer and improvement of Hall Boulevard.",
          "Improve emergency-service facilities and sustain parks funding.",
        ],
        "The program links growth with capital and service investment. Road transfers and funding require agreement from other governments.",
        "What would the city pay to take responsibility for Hall Boulevard and maintain it over time?",
        w(38),
      ),
      c(
        "Yousef K. Allouzi",
        "Data analyst with budget-committee and court-system experience.",
        "Emphasizes affordable multigenerational housing and public spaces designed around residents.",
        [
          "Improve crossings and safe routes to schools and services.",
          "Support housing that allows residents to remain in Tigard.",
          "Use evidence and public accountability in city decisions.",
        ],
        "His statement establishes broad priorities; detailed housing tools, targets and funding remain less developed in the reviewed source.",
        "What housing policies would you adopt first, and how would you assess their affordability effects?",
        w(38),
      ),
      c(
        "Kate Ristau",
        "Nonprofit executive, author and library-board chair.",
        "Proposes protecting community services while expanding housing, safer connections and downtown activity.",
        [
          "Invest in library and recreation services.",
          "Support starter homes and workforce housing.",
          "Improve key corridors and streamline business permitting.",
        ],
        "She emphasizes the public services accompanying growth. The budget tradeoffs between services and new infrastructure require detail.",
        "Which services and capital projects would take priority if revenues fall short?",
        w(39),
      ),
      missing("Shawne Martinez", certified("tigard")),
    ],
    3,
  ),
  {
    ...cityRace(
      "lake-oswego-council",
      "Lake Oswego City Council",
      "Clackamas",
      "City of Lake Oswego · portions of all three counties",
      certified("lake-oswego"),
      "Compare the approaches to state housing requirements, infrastructure costs, neighborhood character and accessibility. Four seats are being filled, with different term lengths.",
      [
        c(
          "Bryan Guiney",
          "HUD Oregon field-office director; former Marine officer and state development official.",
          "Emphasizes fiscal discipline, sustainable growth, business activity and infrastructure.",
          [
            "Improve mobility, traffic safety and connectivity.",
            "Support commercial districts.",
            "Make city administration responsive and transparent.",
          ],
          "He offers public-resource management experience as a way to balance growth and service needs.",
          "Which infrastructure projects would you prioritize, and what financial limits would guide them?",
          m(46),
        ),
        c(
          "Suzanne Miles",
          "Attorney, law professor and former federal prosecutor.",
          "Prioritizes school partnerships, first responders, environmental protection and local business.",
          [
            "Strengthen city partnerships with schools.",
            "Support police and firefighters.",
            "Protect natural resources and commercial activity.",
          ],
          "Her approach emphasizes existing institutions and community partnerships. School policy itself belongs to a separate elected board.",
          "Which school partnership can the city fund and deliver, with what measurable benefit?",
          m(46),
        ),
        c(
          "Peren Tiemann",
          "Law clerk and city diversity, equity and inclusion advisory-board chair.",
          "Supports more accessible housing, transit and public programs, alongside climate and emergency preparedness.",
          [
            "Expand housing and transit choices.",
            "Plan for climate impacts and emergencies.",
            "Make city resources accessible to more residents.",
          ],
          "The program emphasizes who can use and afford city amenities, as well as long-term resilience.",
          "Which accessibility or housing change would you deliver first, and how would it be financed?",
          m(47),
        ),
        c(
          "Neil Tunmore",
          "Retired Intel executive.",
          "Emphasizes capital-project discipline, neighborhood character and long-term infrastructure planning.",
          [
            "Keep major capital projects on schedule and budget.",
            "Improve safe routes near schools.",
            "Implement state requirements in ways consistent with local building standards.",
          ],
          "He puts management discipline and local discretion at the center of growth policy. The city must still comply with applicable state law.",
          "Which local standards would you retain or change while meeting state housing requirements?",
          m(47),
        ),
        c(
          "Heather Ramsey",
          "Executive coach and local chamber-board chair.",
          "Supports business development, reliable capital-project delivery and growth that preserves valued community features.",
          [
            "Keep infrastructure projects on budget and schedule.",
            "Balance housing requirements with local needs.",
            "Protect parks and waterways and support emergency readiness.",
          ],
          "Her program stresses execution and balancing growth with preservation; the specific housing and budget choices need further detail.",
          "What would you change when housing goals conflict with existing neighborhood preferences?",
          m(48),
        ),
        missing("Patrick Walsh", certified("lake-oswego")),
      ],
      4,
    ),
    method:
      "Vote for up to four · top three receive four-year terms; fourth receives a two-year term",
  },
  cityRace(
    "oregon-city-mayor",
    "Oregon City Mayor",
    "Clackamas",
    "City of Oregon City",
    oregonCity,
    "Mabee emphasizes parks and budget reprioritization; Marl emphasizes housing, safety and infrastructure; La Barr emphasizes reducing development costs and using growth to support services.",
    [
      c(
        "Damon Mabee",
        "Former city commissioner and planning commissioner; retired educator and naval officer.",
        "Makes parks investment his first priority and calls for a close review of the budget and economic-development choices.",
        [
          "Find budget resources to repair parks and trails.",
          "Improve local recreation access.",
          "Consider industries that allow residents to work near home.",
        ],
        "He proposes redirecting resources toward parks rather than presenting a specific new revenue plan.",
        "What spending would you reduce or reallocate to restore parks, and how much would that raise?",
        k(37),
      ),
      c(
        "Adam Marl",
        "City commissioner and state land-use agency legislative coordinator.",
        "Supports public safety, homeownership, road improvements and conditions for small businesses to grow.",
        [
          "Improve streets and safe school routes.",
          "Expand homeownership opportunities.",
          "Coordinate regionally on homelessness and oppose tolling.",
        ],
        "His program uses infrastructure and economic development to support affordability. Past funding and tax claims remain candidate assertions pending review.",
        "Which housing and road changes would you deliver first without weakening the city’s finances?",
        k(37),
      ),
      c(
        "Rodney La Barr",
        "Facilities safety technician with building-trades experience.",
        "Argues that lower permitting, regulatory and fee burdens would revive properties and expand housing.",
        [
          "Reduce unnecessary construction and business barriers.",
          "Encourage housing of several types.",
          "Use growth-related revenue for services and parks without raising taxes.",
        ],
        "The proposed chain is lower costs, more activity and then more public revenue. The size and timing of that revenue are assumptions needing evidence.",
        "Which requirements would you remove, and how would you fund infrastructure before growth revenue arrives?",
        k(38),
      ),
    ],
  ),
  {
    ...cityRace(
      "oregon-city-commission",
      "Oregon City Commission",
      "Clackamas",
      "City of Oregon City · two seats",
      oregonCity,
      "Candidates differ on urban renewal, development incentives, parks and administrative changes. Compare the mechanism and funding behind each promise.",
      [
        c(
          "Betty Mumm",
          "Former city commissioner and small-business owner.",
          "Emphasizes core services, cautious consideration of higher resident costs and business growth.",
          [
            "Protect public safety, parks, streets and library services.",
            "Attract another hotel and strengthen the tax base.",
            "Improve public involvement and regional cooperation.",
          ],
          "Her approach relies on prudent budgeting and economic growth; the statement does not specify an incentive package or service tradeoff.",
          "Which development incentives would be justified, and what return would the city require?",
          k(39),
        ),
        c(
          "James Nicita",
          "Historian, retired attorney and former city commissioner.",
          "Proposes changes to urban renewal, city legal services and economic development, with historic preservation and opposition to data centers.",
          [
            "Redirect urban-renewal tax resources toward police or smaller public-designed projects.",
            "Create an independent charter office of city attorney.",
            "Explore a food hub, solar district and Metro partnership for Water Board Park.",
          ],
          "His agenda changes both development priorities and governance. Charter changes and regional partnerships require authority beyond an individual commissioner.",
          "Which proposal comes first, and how would you handle existing urban-renewal obligations?",
          k(39),
        ),
        c(
          "Paul Espe",
          "Urban planner and planning-commission chair.",
          "Supports business growth and tourism, better services, disaster preparation and resource protection.",
          [
            "Use incentives to attract and retain taxable businesses.",
            "Maintain and improve parks and other services.",
            "Evaluate government performance and strengthen emergency planning.",
          ],
          "He expects business growth to support service capacity. Incentive costs and resulting revenue need to be evaluated together.",
          "Which incentives would generate a net public benefit, and how would you demonstrate it?",
          k(40),
        ),
        c(
          "Gordon J Lawrence",
          "Contracting-business owner and civic volunteer.",
          "Emphasizes fewer business barriers, stronger regional partnerships, housing and investment in parks.",
          [
            "Encourage new businesses and investment.",
            "Improve housing opportunities and support services.",
            "Connect historic preservation with revitalization and tourism.",
          ],
          "The statement describes a collaborative growth agenda but leaves specific regulatory and financing decisions open.",
          "What barriers would you remove first, and how would you measure whether residents benefit?",
          k(40),
        ),
      ],
      2,
    ),
    method:
      "Two commission seats · follow the official ballot’s voting instructions",
  },
];
