/** Plain-language summaries of the existing record. Original research and sources
 * remain unchanged in council-record-accounts, council-history and council-coverage.
 * Read each card on its own: name the proposal, money and service before shorthand.
 */
export type ReaderCard = { headline: string; text: string };
export type ReaderTopic = { context: string; contrast: string; takeaway: string; readings: Record<string, ReaderCard> };
const names = ["Tiffany Koyama Lane", "Angelita Morillo", "Steve Novick", "Mitch Green", "Olivia Clark", "Eric Zimmerman"] as const;
const card = (headline: string, ...paragraphs: string[]): ReaderCard => ({ headline, text: paragraphs.join("\n\n") });
const six = (...cards: [ReaderCard, ReaderCard, ReaderCard, ReaderCard, ReaderCard, ReaderCard]) => Object.fromEntries(names.map((name, i) => [name, cards[i]]));
const all = (value: ReaderCard, exceptions: Partial<Record<(typeof names)[number], ReaderCard>> = {}) => Object.fromEntries(names.map((name) => [name, exceptions[name] ?? value]));

export const councilReaderVersion = "2026-09-19-context-1";
export const councilReaderCopy: Record<string, ReaderTopic> = {
  "supplemental-budget": {
    context: "In May 2025, Council moved about $1.9 million in proposed new police funding to park maintenance. In June and July 2026, the debates concerned restoring jobs and services facing cuts. Funding could come from interest earned by the climate fund, expected unspent police-oversight money, or reserves set aside for unexpected costs. July’s smaller plan used about $12.2 million in one-time money to preserve 30 positions and restore services.",
    contrast: "The councilors disagreed about which services to restore and which money should pay for them. Their votes also changed between the larger and smaller proposals.",
    takeaway: "Compare both the services and the funding source. Supporting park maintenance, police services or climate spending did not put a councilor on the same side of every budget vote.",
    readings: six(
      card("Favored restoring more services; rejected July’s smaller plan", "In 2025, supported moving about $1.9 million in proposed new police funding to park maintenance.", "In 2026, backed using climate-fund interest to restore parks, fire rescue, unarmed police support and other city jobs. Opposed using money expected to go unspent by the police-accountability office, which oversees police misconduct.", "In July, supported the larger plan to restore services. When it failed, voted against the smaller plan funded with reserves and other one-time money."),
      card("Favored restoring more services while keeping police-oversight money", "In 2025, supported moving proposed new police funding to park maintenance.", "In June 2026, helped propose Services First: a plan using about $16 million in climate-fund interest, plus other money, to restore parks, fire rescue, unarmed police support and other city jobs. Opposed using money budgeted for investigating police misconduct that the accountability office was expected not to spend.", "In July, backed the larger plan, then the smaller plan using reserves and other one-time money. Warned against later paying for it with police-oversight money."),
      card("Supported several ways to pay for a smaller set of services", "In 2025, supported moving proposed new police funding to park maintenance.", "In June 2026, opposed the larger plan to restore parks, fire rescue, unarmed police support and other city jobs. Proposed using $8.42 million in climate-fund interest for a smaller mix of services and a business-tax reserve. Also supported using money expected to go unspent by the police-accountability office for police and fire services.", "In July, supported the smaller plan to restore services using reserves and other one-time money."),
      card("Favored restoring more services, then accepted a smaller plan", "In 2025, supported moving proposed new police funding to park maintenance.", "In June 2026, helped propose Services First: a plan using about $16 million in climate-fund interest, plus other money, to restore parks, fire rescue, unarmed police support and other city jobs. Opposed using money budgeted for investigating police misconduct that the accountability office was expected not to spend.", "In July, supported the larger plan to restore services. After it failed, supported the smaller plan funded with reserves and other one-time money."),
      card("Favored police and fire services, using expected police-oversight savings", "In 2025, opposed moving proposed new police funding to park maintenance.", "In June 2026, proposed $7.68 million for police support, training and fire rescue. Her plan would use reserves first, then repay them with expected unspent money from the office overseeing police misconduct. Those savings were a forecast, not money already available.", "Opposed both June alternatives using climate-fund interest to restore parks, public-safety support and other services. In July, supported the smaller plan to restore services using reserves and other one-time money."),
      card("Kept the proposed police increase; opposed the overall annual budget", "In 2025, opposed moving proposed new police funding to park maintenance.", "In June 2026, supported using money expected to go unspent by the police-accountability office for police and fire services. Opposed both June alternatives using climate-fund interest to restore parks, public-safety support and other services, and voted against the overall 2026–27 budget.", "In July, supported the smaller plan to restore services using reserves and other one-time money."),
    ),
  },
  zenith: {
    context: "Zenith operates a fuel terminal in Northwest Portland. Its agreement with the City allows fuel pipelines in public streets and sets conditions on that use. Council considered investigating how the agreement was granted, allowing residents to sue over violations, and transferring the agreement to a new owner. These were three separate decisions.",
    contrast: "Koyama Lane, Morillo and Green supported giving residents a right to enforce the pipeline agreement in court. Novick, Clark and Zimmerman opposed that condition and supported the ownership transfer.",
    takeaway: "The City’s February 2026 investigation and outside legal review found no basis to revoke the agreement. The transfer vote failed on September 16; reconsideration was scheduled for September 23 as of this guide’s September 18 review. None of these votes closed the terminal.",
    readings: six(
      card("Supported an investigation and a right for residents to sue", "Supported investigating Zenith’s pipeline agreement in 2025. In 2026, supported allowing residents to sue to enforce its conditions. After that condition failed, opposed transferring the agreement to the new owner."),
      card("Helped propose a right for residents to enforce the agreement", "Supported investigating Zenith’s pipeline agreement. With Green, proposed allowing residents to sue over violations of its conditions. After Council rejected that condition, opposed transferring the agreement to the new owner."),
      card("Opposed the investigation; supported the transfer", "In 2025, sought to remove disputed introductory language and attachments, then opposed investigating Zenith’s pipeline agreement. In 2026, opposed giving residents an added right to sue over its conditions and supported transferring the agreement to the new owner."),
      card("Helped propose a right for residents to enforce the agreement", "Supported investigating Zenith’s pipeline agreement. With Morillo, proposed allowing residents to sue over violations of its conditions. After Council rejected that condition, opposed transferring the agreement to the new owner."),
      card("Supported investigating the agreement, but opposed the right to sue", "Sought changes to the 2025 proposal to investigate Zenith’s pipeline agreement, then supported the investigation. In 2026, opposed giving residents an added right to sue over its conditions and supported transferring the agreement to the new owner."),
      card("Supported investigating the agreement, but opposed the right to sue", "Sought changes to the 2025 proposal to investigate Zenith’s pipeline agreement, then supported the investigation. In 2026, opposed giving residents an added right to sue over its conditions and supported transferring the agreement to the new owner."),
    ),
  },
  water: {
    context: "Portland is building a filtration system for its Bull Run drinking-water supply. Council voted separately on borrowing money for construction and increasing annual water charges. A third vote set sewer and stormwater charges. A vote for borrowing does not tell you how someone voted on customer bills.",
    contrast: "Green opposed borrowing for the water project but supported higher water charges. Koyama Lane and Zimmerman supported the borrowing but opposed the higher charges.",
    takeaway: "Read the construction and customer-bill votes together. Morillo opposed both water measures but supported the separate sewer and stormwater charges.",
    readings: six(
      card("Supported construction borrowing; opposed higher utility charges", "Approved borrowing through bonds for the Bull Run water-filtration project. Opposed the annual water-rate increase and the separate sewer and stormwater charges."),
      card("Opposed the water borrowing and higher water charges", "Opposed borrowing through bonds for the Bull Run water-filtration project and the annual water-rate increase. Supported the separate sewer and stormwater charges."),
      card("Supported water-project borrowing and the annual utility charges", "Approved borrowing through bonds for the Bull Run water-filtration project. Also supported the annual water-rate increase and the separate sewer and stormwater charges."),
      card("Opposed construction borrowing; supported the annual charges", "Opposed borrowing through bonds for the Bull Run water-filtration project. Supported the annual water-rate increase and the separate sewer and stormwater charges."),
      card("Supported water-project borrowing and the annual utility charges", "Approved borrowing through bonds for the Bull Run water-filtration project. Also supported the annual water-rate increase and the separate sewer and stormwater charges."),
      card("Supported construction borrowing; opposed higher utility charges", "Approved borrowing through bonds for the Bull Run water-filtration project. Opposed the annual water-rate increase and the separate sewer and stormwater charges, citing the combined burden of rising living costs."),
    ),
  },
  transportation: {
    context: "Council considered a new monthly transportation fee to help pay for street maintenance and safety. Separate votes concerned a plan for sidewalks and annual parking and permit charges. The debate involved both raising money and deciding how that money would be spent.",
    contrast: "Five of the six supported the new monthly street fee; Zimmerman opposed it. Novick opposed the earlier sidewalk-planning proposal but supported the fee.",
    takeaway: "A councilor could oppose a new charge while still helping decide how its revenue should be used. These votes concern different proposals, not a single yes-or-no choice about repairing streets.",
    readings: six(
      card("Supported the street fee and set priorities for spending it", "Supported the sidewalk plan, annual parking and permit charges, and the new monthly transportation fee. With Zimmerman, secured a requirement directing the new fee’s money toward maintenance and safety."),
      card("Supported new street funding and the sidewalk plan", "Supported the sidewalk plan, annual parking and permit charges, and the new monthly transportation fee. The fee adds a recurring charge to help pay for road repairs and safety work."),
      card("Supported the street fee; opposed the earlier sidewalk plan", "Opposed the 2025 proposal to organize a sidewalk program. Supported the 2026 monthly transportation fee and annual parking and permit charges. His vote against that sidewalk proposal was not a vote against all street spending."),
      card("Supported the fee and reconsidering how businesses are charged", "Supported the sidewalk plan, annual parking and permit charges, and the new monthly transportation fee. With Clark, added a process to review how commercial properties would be charged, because utility use and road use are different."),
      card("Supported a steady source of money for street repairs", "Supported the sidewalk plan, annual parking and permit charges, and the new monthly transportation fee. Helped lead the fee proposal and argued that delaying maintenance would leave future residents with higher repair costs."),
      card("Opposed the new charges, but helped direct the spending", "Supported the sidewalk plan but opposed the new monthly transportation fee and annual parking and permit charges. Before the fee passed, worked with Koyama Lane to direct its money toward maintenance and safety."),
    ),
  },
  "street-response": {
    context: "Portland Street Response sends unarmed mental-health and medical responders to certain emergencies. Council considered expanding its role and creating a community committee to help guide it. Voting for that direction and later choosing committee members were separate decisions.",
    contrast: "Clark opposed the final June 2025 plan to expand the service; the other five supported it. All six later supported appointing the community committee.",
    takeaway: "Zimmerman opposed advancing an earlier version from committee, then supported the revised plan. Clark opposed the plan but later supported filling the committee’s seats.",
    readings: six(
      card("Supported expanding unarmed response and appointing its advisers", "Supported the June 2025 plan to expand Portland Street Response, which sends unarmed mental-health and medical responders to certain crises. In December, supported appointing its community advisory committee."),
      card("Supported expansion while protecting the service’s unarmed role", "Supported the plan to expand Portland Street Response and later appoint its community advisers. In an earlier joint statement, warned that police involvement could weaken trust in this unarmed crisis-response service."),
      card("Supported the expansion plan and community advisers", "Supported advancing the Portland Street Response proposal from committee, adopting the final plan to expand unarmed crisis response, and later appointing its community advisory committee."),
      card("Supported expansion while protecting the service’s unarmed role", "Supported the plan to expand Portland Street Response and later appoint its community advisers. In an earlier joint statement, favored keeping the service unarmed while expanding the situations its mental-health and medical responders could handle."),
      card("Opposed the expansion plan; supported appointing the advisers", "Opposed the June 2025 plan to expand Portland Street Response, the unarmed crisis-response service. In December, supported appointing the community committee that would help guide it."),
      card("Opposed an earlier version, then supported the revised plan", "In April 2025, opposed advancing the Portland Street Response proposal from committee. In June, supported the revised plan to expand unarmed crisis response. In December, supported appointing its community advisory committee."),
    ),
  },
  "police-accountability": {
    context: "Portland’s police-accountability board is part of its system for investigating police misconduct. Council voted on its members and on whether money budgeted for oversight, but expected to go unspent, should pay for police and fire services instead. Two separate removal votes concerned member Schuyler (Hugh) Halsey’s eligibility and alternate Bob Weinstein’s conduct.",
    contrast: "All six supported the first board appointments. They split over removing members and using the oversight office’s expected unspent money for other services.",
    takeaway: "Council rejected the proposed eligibility-based removal of Halsey but approved removing Weinstein. Those are separate decisions from establishing the board or funding its work.",
    readings: six(
      card("Supported the board and keeping its budgeted money for oversight", "Supported the first board appointments and later replacements. Opposed removing Halsey over eligibility, but supported removing alternate member Bob Weinstein over his conduct. Opposed using money the police-accountability office was expected not to spend for police and fire services instead."),
      card("Supported the board and keeping its budgeted money for oversight", "Supported the first board appointments and later replacements. Opposed removing Halsey over eligibility, but supported removing alternate member Bob Weinstein over his conduct. Opposed using money the police-accountability office was expected not to spend for police and fire services instead."),
      card("Supported both removals and using expected savings for services", "Supported board appointments and both proposed removals: Halsey over eligibility and alternate member Bob Weinstein over his conduct. Also supported Clark’s plan to use money expected to go unspent by the police-accountability office for police and fire services."),
      card("Supported the board and keeping its budgeted money for oversight", "Supported the first board appointments and later replacements. Opposed removing Halsey over eligibility, but supported removing alternate member Bob Weinstein over his conduct. Opposed using money the police-accountability office was expected not to spend for police and fire services instead."),
      card("Split on board membership; proposed using expected savings", "Supported the first board appointments and removing Halsey over eligibility. Opposed removing alternate member Bob Weinstein over his conduct and opposed the later replacement appointments. Proposed using reserves for police and fire services, then repaying them with money the police-accountability office was expected not to spend."),
      card("Split on board membership; supported using expected savings", "Supported the first board appointments and removing Halsey over eligibility. Opposed removing alternate member Bob Weinstein over his conduct and opposed the later replacement appointments. Supported Clark’s plan to use money expected to go unspent by the police-accountability office for police and fire services."),
    ),
  },
  "climate-fund": {
    context: "The Portland Clean Energy Community Benefits Fund pays for climate-related projects. Council voted on changes to its investment plan and, separately, on moving interest earned by the fund into the City’s general budget. Later budget votes proposed additional uses of that interest to restore jobs and services.",
    contrast: "Morillo and Green opposed the final investment-plan changes. Morillo was the only one of these six to oppose the May interest transfer. Their votes on later uses of interest differed again.",
    takeaway: "Using interest for one purpose does not establish support for every use of the fund. The budget comparison names the services and funding sources in the later proposals.",
    readings: six(
      card("Supported the climate plan and transferring interest to city services", "Approved changes to the climate fund’s investment plan and the May transfer of audited interest earnings into the City’s general budget. Later supported using additional climate-fund interest to restore jobs and services facing cuts."),
      card("Opposed these two measures; later supported a different use of interest", "Opposed the final climate-investment changes and the May transfer of interest to the general budget. Later helped propose using climate-fund interest specifically to restore parks, fire rescue, unarmed police support and other city jobs."),
      card("Supported the plan and using interest for selected services", "Approved the climate-investment changes and the May interest transfer to the general budget. Later proposed a smaller plan using climate-fund interest for selected services and a business-tax reserve, while opposing the larger proposal for parks, fire rescue, unarmed police support and other city jobs."),
      card("Opposed the investment-plan changes; supported transferring interest", "Opposed the final changes to the climate fund’s investment plan but supported the May transfer of interest to the general budget. Later backed using additional interest to restore parks, fire rescue, unarmed police support and other city jobs."),
      card("Supported the climate plan and the May interest transfer", "Approved the climate-investment changes and the May transfer of interest to the general budget. Later proposed restoring police and fire services with money expected to go unspent by the police-accountability office, and backed July’s smaller plan using reserves and other one-time money."),
      card("Supported the climate plan and the May interest transfer", "Approved the climate-investment changes and the May transfer of interest to the general budget. Opposed the later Services First proposal to use additional interest for parks, fire rescue, unarmed police support and other city jobs."),
    ),
  },
  "parks-trees": {
    context: "Council voted on asking voters to renew and increase a parks property tax, planning for tree care, rejecting a power-line proposal in Forest Park, and selling Sellwood Community House to its nonprofit operator. A disputed change to the tree plan made clear that the City taking on more tree-care responsibility depended on a future decision to carry it out.",
    contrast: "Koyama Lane and Morillo opposed weakening the commitment to plan for City responsibility for street trees. The other four supported that wording change. All six supported the final forest plan.",
    takeaway: "The parks vote put a tax proposal on the ballot; it did not itself approve the tax. The tree plan did not immediately shift residents’ maintenance duties to the City. The Sellwood sale required the property to keep serving a public benefit.",
    readings: six(
      card("Supported a parks-tax vote and a firmer commitment on tree care", "Supported putting a five-year parks property tax before voters and adopting the forest plan. Opposed wording that made future City responsibility for street trees more conditional. Supported overturning approval of the Forest Park power-line proposal. Was absent from the Sellwood Community House sale vote."),
      card("Supported a parks-tax vote and a firmer commitment on tree care", "Supported putting a five-year parks property tax before voters and adopting the forest plan. Opposed wording that made future City responsibility for street trees more conditional. Supported overturning the Forest Park power-line approval and selling Sellwood Community House to its nonprofit operator, with a public-benefit requirement."),
      card("Supported the parks-tax vote and leaving tree-care changes conditional", "Supported putting a five-year parks property tax before voters. Backed the forest plan and wording that left expanded City responsibility for street trees dependent on future implementation. Supported overturning the Forest Park power-line approval and selling Sellwood Community House to its nonprofit operator, with a public-benefit requirement."),
      card("Supported the parks-tax vote and leaving tree-care changes conditional", "Supported putting a five-year parks property tax before voters. Backed the forest plan and wording that left expanded City responsibility for street trees dependent on future implementation. Supported overturning the Forest Park power-line approval and selling Sellwood Community House to its nonprofit operator, with a public-benefit requirement."),
      card("Supported the forest plan and Sellwood sale; missed the parks-tax vote", "Supported the forest plan and wording that left expanded City responsibility for street trees dependent on future implementation. Supported overturning the Forest Park power-line approval and selling Sellwood Community House to its nonprofit operator, with a public-benefit requirement. Was absent when Council put the parks tax before voters."),
      card("Supported the parks-tax vote and leaving tree-care changes conditional", "Supported putting a five-year parks property tax before voters. Backed the forest plan and wording that left expanded City responsibility for street trees dependent on future implementation. Supported overturning the Forest Park power-line approval and selling Sellwood Community House to its nonprofit operator, with a public-benefit requirement."),
    ),
  },
  governance: {
    context: "Portland’s new Council voted on money for its offices, how to organize policy committees, and a yearly process for setting priorities. It also considered a public inquiry into unspent money from the rental-registration program and how city administrators had told Council about that money during budget discussions.",
    contrast: "Koyama Lane, Morillo and Green supported the public housing-funds inquiry. Novick, Clark and Zimmerman opposed it; Novick and Clark had supported a different investigation or audit approach.",
    takeaway: "The inquiry vote concerned how to obtain and examine information; it was not a finding of wrongdoing. Office budgets, committee structure and the inquiry were separate decisions.",
    readings: six(
      card("Supported more office resources and a public housing-funds inquiry", "Supported increasing Council office budgets, replacing eight policy committees with five, and creating an annual priority-setting process. Also supported a public inquiry into unspent rental-registration money and how administrators informed Council about it."),
      card("Supported more office resources and a public housing-funds inquiry", "Supported increasing Council office budgets, setting annual priorities, and a public inquiry into unspent rental-registration money and how administrators informed Council about it. Was absent from the vote to replace eight policy committees with five."),
      card("Opposed higher office spending and preferred a different inquiry", "Opposed increasing Council office budgets and the annual priority-setting process, but supported replacing eight policy committees with five. Supported an alternative investigation by administrators or the Auditor into the rental-registration money, then opposed the final public-inquiry proposal."),
      card("Supported more office resources and a public housing-funds inquiry", "Supported increasing Council office budgets, replacing eight policy committees with five, and creating an annual priority-setting process. Also supported a public inquiry into unspent rental-registration money and how administrators informed Council about it."),
      card("Supported office resources; preferred a different investigation", "Supported increasing Council office budgets, reorganizing policy committees, and setting annual priorities. Supported an alternative investigation by administrators or the Auditor into unspent rental-registration money, then opposed the final public-inquiry proposal."),
      card("Supported office resources; opposed the committee change and inquiry", "Supported increasing Council office budgets and setting annual priorities. Opposed replacing eight policy committees with five and opposed the final public inquiry into unspent rental-registration money and how administrators informed Council about it."),
    ),
  },
  sanctuary: {
    context: "Sanctuary policies limit the City’s role in federal immigration enforcement. All six supported Portland’s October 2025 protections. A later proposal required visible law-enforcement identification, restricted facial coverings and set procedures for checking officers’ claimed authority. Council voted separately on fees for privately owned detention facilities.",
    contrast: "Novick joined Koyama Lane, Morillo and Green in supporting the officer-identification rules. Clark and Zimmerman opposed those rules despite supporting the earlier sanctuary measures.",
    takeaway: "These votes distinguish specific local responses to immigration enforcement. Agreement on sanctuary protections did not settle the separate choices about officer identification or detention-facility fees.",
    readings: six(
      card("Supported sanctuary protections and officer-identification rules", "Supported the October measures limiting the City’s role in federal immigration enforcement. Later supported rules on visible officer identification, facial coverings and checking claimed law-enforcement authority."),
      card("Supported sanctuary protections, identification rules and detention fees", "Supported the October sanctuary measures and later rules on visible officer identification, facial coverings and checking claimed authority. Also sponsored the separate proposal to charge qualifying private detention facilities for local impacts."),
      card("Supported officer-identification rules; opposed detention-facility fees", "Supported sanctuary protections and later rules on officer identification, facial coverings and checking claimed authority. Opposed the separate detention-facility fees because of the precedent for charging landlords for protest-related costs."),
      card("Supported sanctuary protections, identification rules and detention fees", "Supported sanctuary protections and later rules on officer identification, facial coverings and checking claimed authority. Also supported the separate fees for qualifying privately owned detention facilities."),
      card("Supported sanctuary protections; opposed officer-identification rules", "Supported the October sanctuary measures and the separate detention-facility fees. Opposed the later rules on visible officer identification, facial coverings and checking claimed law-enforcement authority."),
      card("Supported sanctuary protections; opposed officer-identification rules", "Supported the October sanctuary measures but opposed the later rules on visible officer identification, facial coverings and checking claimed authority. Was absent from the final vote on the separate detention-facility fees."),
    ),
  },
  economy: {
    context: "Council considered exempting more small businesses from the business-license tax, a plan to help struggling storefronts, investment in the Cully neighborhood, and possible ethical standards for investing City money. Cully’s plan uses growth in designated property-tax revenue for local housing, anti-displacement work and other neighborhood priorities.",
    contrast: "All six supported the larger business-tax exemption. Morillo opposed accepting the storefront-support report. Zimmerman opposed the investment-policy resolution that called for ethical-investment options.",
    takeaway: "Accepting a plan does not fund every project in it. The investment vote requested options considering human rights, labor, environmental and consumer impacts; it did not create a list of companies the City must stop investing in.",
    readings: six(
      card("Supported business-tax relief, neighborhood investment and ethical options", "Supported exempting more small businesses from the business-license tax, accepting a storefront-support plan, and Cully’s investment plan for housing and neighborhood needs. Also supported developing ethical options for investing City money."),
      card("Supported business-tax relief; opposed the storefront-support report", "Supported the larger small-business tax exemption, Cully’s housing and neighborhood investment plan, and work on ethical options for investing City money. Opposed accepting the report proposing responses to vacant storefronts and business-support needs."),
      card("Supported business-tax relief, neighborhood investment and ethical options", "Supported exempting more small businesses from the business-license tax, accepting a storefront-support plan, and Cully’s investment plan for housing and neighborhood needs. Also supported developing ethical options for investing City money."),
      card("Supported the final measures, including a revised position on Cully", "Supported the small-business tax exemption, storefront-support plan, Cully investment plan and work on ethical options for investing City money. Earlier opposed advancing the Cully plan from committee, then supported the final neighborhood plan."),
      card("Supported tax relief and local investment; missed the investment-policy vote", "Supported the larger small-business tax exemption, storefront-support plan, and Cully’s housing and neighborhood investment plan. Was absent from the final vote on developing ethical options for investing City money."),
      card("Supported business-tax relief; opposed the investment-policy resolution", "Co-sponsored the larger small-business tax exemption and supported accepting the storefront-support report. Opposed the resolution calling for ethical options for investing City money. Was absent from the final vote on Cully’s housing and neighborhood investment plan."),
    ),
  },
  "camp-removal": {
    context: "In November 2025, Council considered moving about $4.3 million from the program that clears homeless camps into a package supporting city personnel, housing, food and immigration services. The proposal failed. It would have changed spending, not repealed the criminal camping ban.",
    contrast: "Morillo proposed the change; Koyama Lane and Green supported it. Novick opposed it. Clark and Zimmerman were absent.",
    takeaway: "All six also supported the broader housing strategy and City–County homelessness plan. Their agreement on those goals did not resolve how much to spend on clearing camps.",
    readings: six(
      card("Supported moving camp-removal money to other services", "Supported Morillo’s proposal to move about $4.3 million from clearing homeless camps into a package supporting personnel, housing, food and immigration services. The proposal failed."),
      card("Proposed moving camp-removal money to other services", "Proposed moving about $4.3 million from clearing homeless camps into a package supporting personnel, housing, food and immigration services. Argued that repeated removals and overnight shelter were not enough. The proposal failed."),
      card("Opposed moving the camp-removal money in this proposal", "Opposed moving about $4.3 million from camp removals to personnel and social-service support. Said five days was too little time to consider a major policy change and wanted a fuller debate before cutting the program."),
      card("Supported moving camp-removal money to other services", "Supported moving about $4.3 million from clearing homeless camps into a package supporting personnel, housing, food and immigration services. Argued that removals were ineffective and harmed people living outside. The proposal failed."),
      card("Absent from the camp-removal spending vote", "Was absent when Council voted on moving about $4.3 million from camp removals to personnel and social-service support. This roll call records no position for or against that proposal."),
      card("Absent from the camp-removal spending vote", "Was absent when Council voted on moving about $4.3 million from camp removals to personnel and social-service support. This roll call records no position for or against that proposal."),
    ),
  },
  "rental-pricing": {
    context: "Council voted on restricting software that helps landlords coordinate rents, temporarily waiving some fees builders pay for public infrastructure, and removing the buyer-income limit for certain homes that already qualified for an affordable-housing fee exemption. The last change applied to homes permitted before 2026; buyers still had to live in them and meet the sale-price rules.",
    contrast: "Koyama Lane, Morillo and Green supported the rent-software restriction; Clark opposed it. On the separate buyer-income rule, Morillo, Novick, Green and Clark supported removing the limit; Koyama Lane and Zimmerman opposed removing it.",
    takeaway: "These policies affect different parts of housing costs. Support for reducing construction fees does not predict a councilor’s position on rent-setting software or who should qualify for an affordable-housing benefit.",
    readings: six(
      card("Supported restricting rent-setting software", "Co-sponsored and supported the restriction on software that lets landlords coordinate rents. Also supported the temporary housing-construction fee waiver, but opposed removing the buyer-income limit for certain homes already receiving an affordable-housing fee exemption."),
      card("Introduced the rent-software restriction; supported the income-rule change", "Introduced the restriction on software that lets landlords coordinate rents, revising it to exempt affordable housing and landlords with fewer than six units. Also supported the construction-fee waiver and removing the buyer-income limit for certain previously approved, fee-exempt homes."),
      card("Missed the rent-software vote; supported the two fee-related changes", "Was absent from the final vote on restricting landlords’ rent-setting software. Supported temporarily waiving housing-construction fees and removing the buyer-income limit for certain homes already receiving an affordable-housing fee exemption."),
      card("Supported restricting rent-setting software and the income-rule change", "Co-sponsored and supported the restriction on software that lets landlords coordinate rents. Also supported the construction-fee waiver and removing the buyer-income limit for certain homes already receiving an affordable-housing fee exemption."),
      card("Opposed the rent-software restriction; supported the income-rule change", "Opposed restricting landlords’ rent-setting software, citing housing-investment and lawsuit concerns. Was absent from the final construction-fee waiver vote. Supported removing the buyer-income limit for certain homes already receiving an affordable-housing fee exemption."),
      card("Missed the rent-software vote; opposed removing the buyer-income limit", "Was absent from the final vote on restricting landlords’ rent-setting software. Supported the temporary construction-fee waiver, but opposed removing the buyer-income limit for certain homes already receiving an affordable-housing fee exemption."),
    ),
  },
  moda: {
    context: "Council approved proposed negotiating terms for the Moda Center arena: $120 million for renovation and $275 million for future building needs over 20 years. These were non-binding terms, not a final construction contract. A separate vote advanced plans for a new performing-arts venue at Portland State University and a smaller Keller Auditorium.",
    contrast: "Koyama Lane, Morillo and Green opposed the arena terms; Novick, Clark and Zimmerman supported them. Green joined the latter three in supporting the separate performing-arts planning proposal.",
    takeaway: "Compare what each vote actually committed the City to. The arena vote set negotiating terms; the performing-arts vote authorized planning rather than a full construction budget.",
    readings: six(
      card("Rejected the arena terms after seeking stronger financial conditions", "Supported charging the arena tenant more rent and requiring a report on what other public spending might be displaced by the deal. Then opposed the proposed Moda Center terms. Also opposed the separate plan for a new Portland State University performing-arts venue and a smaller Keller Auditorium."),
      card("Sought more financial safeguards before an arena commitment", "Helped propose a report on what other public spending might be displaced by the Moda Center deal. That requirement failed; she opposed the arena terms, saying the City needed to know the funding source and public return. Also opposed the separate Portland State University and Keller Auditorium planning proposal."),
      card("Raised the proposed arena rent, then supported the terms", "Won a change raising the arena tenant’s proposed annual rent from $2 million to $3.17 million, then supported the Moda Center negotiating terms. Also supported planning a new Portland State University performing-arts venue and a smaller Keller Auditorium."),
      card("Rejected the arena cost; supported performing-arts planning", "Tried to remove the proposed $275 million commitment for future Moda Center building needs. After that change failed, opposed the arena terms. Supported the separate planning proposal for a new Portland State University performing-arts venue and a smaller Keller Auditorium."),
      card("Supported the arena terms while opposing the higher proposed rent", "Opposed increasing the arena tenant’s proposed annual rent from $2 million to $3.17 million, then supported the revised Moda Center terms. Emphasized the opportunity for state matching investment. Also supported the separate Portland State University and Keller Auditorium performing-arts planning proposal."),
      card("Supported the arena terms while opposing the higher proposed rent", "Opposed increasing the arena tenant’s proposed annual rent from $2 million to $3.17 million, then supported the revised Moda Center terms. Previously argued that the state investment could support jobs and events. Also supported the separate Portland State University and Keller Auditorium performing-arts planning proposal."),
    ),
  },
  "detention-fees": {
    context: "Council considered charging owners of qualifying private detention facilities for local impacts and setting rules to address harms such as chemical contamination. The lease-related fee would apply when a lease was renewed. The ordinance did not close the federal Immigration and Customs Enforcement facility, commonly called ICE.",
    contrast: "Koyama Lane, Morillo, Green and Clark supported the fees and rules. Novick opposed them. Zimmerman was absent from the final vote.",
    takeaway: "Novick’s stated concern was the precedent for charging landlords for protest-related impacts. This vote concerned a specific local response to detention facilities, not whether a councilor supported federal immigration enforcement.",
    readings: all(card("Supported fees for detention facilities’ local impacts", "Supported charging qualifying private detention facilities for local impacts and adopting rules to address harms such as chemical contamination. The ordinance did not close the ICE facility."), {
      "Angelita Morillo": card("Introduced fees and rules for detention facilities’ local impacts", "Introduced and supported the fees and rules for qualifying private detention facilities. Argued that Portland should use the local tools available to respond to detention-related harms. The ordinance did not close the ICE facility."),
      "Steve Novick": card("Opposed charging detention-facility landlords for these impacts", "Opposed the detention-facility fees and rules. Questioned the precedent of charging landlords for protest-related costs, including whether the same approach would be acceptable outside an abortion clinic."),
      "Eric Zimmerman": card("Absent from the final detention-facility vote", "Was absent from the final vote on fees and rules for qualifying private detention facilities. This roll call records no vote for or against that ordinance."),
    }),
  },
  "shared-ground": {
    context: "All six councilors voted to exempt more small businesses from the business-license tax. They also supported disclosing major data-center inquiries and pursuing restrictions on those facilities. Data centers house large amounts of computing equipment; the vote called for further policy work rather than imposing a ban.",
    contrast: "These final votes show agreement among all six incumbents, despite their disagreements on other issues.",
    takeaway: "The business-tax exemption is based on gross receipts—the money a business receives before subtracting expenses. The data-center resolution did not itself stop new facilities from being approved.",
    readings: all(card("Supported small-business tax relief and data-center disclosure", "Supported exempting more small businesses from the business-license tax. Also supported disclosing major data-center inquiries and pursuing future restrictions. That second vote did not itself ban data centers."), {
      "Eric Zimmerman": card("Helped propose the business-tax relief; supported data-center disclosure", "Co-sponsored the larger business-license-tax exemption and moved an amendment before voting for it. Also supported disclosing major data-center inquiries and pursuing future restrictions, without enacting a ban in that vote."),
    }),
  },
  "arts-tax": {
    context: "The arts tax helps pay for school arts teachers and arts organizations. The proposal increased the individual tax from $35 to $50 while exempting more lower-income residents. New filing thresholds used Oregon taxable income: $20,000 for a single filer and $40,000 for joint filers. It also allowed inflation adjustments.",
    contrast: "Koyama Lane, Morillo and Green supported charging a higher amount while exempting more people. Novick, Clark and Zimmerman opposed that combination.",
    takeaway: "Both parts matter: a higher charge for those who pay, and broader exemptions for lower-income residents. The record does not give a separate stated explanation for Clark’s no vote.",
    readings: six(
      card("Supported a $50 arts tax with more low-income exemptions", "Co-sponsored the change from $35 to $50 and helped advance the revised income thresholds. Supported the final combination of a higher individual tax and exemptions for more lower-income residents."),
      card("Supported a $50 arts tax with more low-income exemptions", "Supported raising the arts tax from $35 to $50 while exempting more lower-income residents. The package was intended to maintain funding for school arts teachers and arts organizations."),
      card("Opposed the revised arts tax", "Opposed the package raising the arts tax from $35 to $50 and expanding low-income exemptions. Earlier criticized the tax’s structure and separate filing burden, saying the changes did not solve those problems."),
      card("Supported a $50 arts tax with more low-income exemptions", "Supported raising the arts tax from $35 to $50 while exempting more lower-income residents. The package was intended to maintain funding for school arts teachers and arts organizations."),
      card("Opposed the revised arts tax", "Opposed the package raising the arts tax from $35 to $50 and expanding low-income exemptions. The roll call establishes her vote; the sources here do not establish a separate stated reason."),
      card("Opposed the higher charge and wanted voters to decide", "Opposed raising the arts tax from $35 to $50 while changing its exemptions. Argued that the higher charge could still burden minimum-wage workers and that voters should decide major changes to the tax."),
    ),
  },
  "police-enforcement": {
    context: "One proposal asked staff to assess police staffing needs and costs. Another changed enforcement rules for properties linked to repeated criminal activity, including trafficking. The staffing vote commissioned an assessment; it did not fund the hiring of 400 officers.",
    contrast: "Novick, Clark and Zimmerman supported both measures. Koyama Lane, Morillo and Green opposed both.",
    takeaway: "These votes concern a particular staffing assessment and property-enforcement rules. They do not establish a position on every police budget or public-safety proposal.",
    readings: six(
      card("Opposed the staffing assessment and property-enforcement changes", "Opposed requesting a police staffing-and-cost assessment and opposed expanding enforcement rules for properties linked to repeated criminal activity. The assessment proposal was a planning step, not an immediate decision to hire more officers."),
      card("Opposed the staffing assessment and property-enforcement changes", "Opposed requesting a police staffing-and-cost assessment and opposed expanding enforcement rules for properties linked to repeated criminal activity. The assessment proposal was a planning step, not an immediate decision to hire more officers."),
      card("Supported the staffing assessment and property-enforcement changes", "Supported assessing police staffing needs and costs, and expanding enforcement rules for properties linked to repeated crime. His case for the property rules emphasized trafficking survivors, students near McDaniel High School and the difficulty of documenting repeated incidents."),
      card("Opposed the staffing assessment and property-enforcement changes", "Opposed requesting a police staffing-and-cost assessment and opposed expanding enforcement rules for properties linked to repeated criminal activity. The assessment proposal was a planning step, not an immediate decision to hire more officers."),
      card("Supported the staffing assessment and property-enforcement changes", "Supported requesting a police staffing-and-cost assessment and expanding enforcement rules for properties linked to repeated criminal activity. The assessment vote did not itself fund new officer positions."),
      card("Supported the staffing assessment and property-enforcement changes", "Supported requesting a police staffing-and-cost assessment and expanding enforcement rules for properties linked to repeated criminal activity. The assessment vote did not itself fund new officer positions."),
    ),
  },
  firearms: {
    context: "The proposal would restrict carrying concealed firearms, even with a license, in specified City buildings used for official meetings. A committee voted to put the proposal on hold. This was not a final Council vote on adopting gun restrictions across Portland.",
    contrast: "Zimmerman voted to put the proposal on hold. Morillo and Novick voted against pausing it. Koyama Lane, Green and Clark were not members of that committee.",
    takeaway: "Here a yes vote means support for pausing the proposal. As of the September 18 review, the full Council had not taken a final vote on adopting it.",
    readings: all(card("Not a member of the committee that voted", "Did not have a vote on whether to pause the proposal restricting licensed concealed carry in specified City buildings. This committee record does not establish a position for or against the gun restrictions."), {
      "Angelita Morillo": card("Voted against putting the gun proposal on hold", "Voted against pausing the proposal to restrict licensed concealed carry in specified City buildings. This was a committee vote about whether work should proceed, not final adoption of the restrictions."),
      "Steve Novick": card("Voted against putting the gun proposal on hold", "Voted against pausing the proposal to restrict licensed concealed carry in specified City buildings. This was a committee vote about whether work should proceed, not final adoption of the restrictions."),
      "Eric Zimmerman": card("Voted to put the gun proposal on hold", "Supported pausing the proposal to restrict licensed concealed carry in specified City buildings. His yes vote was for that pause, not for adopting the gun restrictions."),
    }),
  },
  psychedelics: {
    context: "The proposal would make non-commercial personal use of naturally occurring psychedelic plants and fungi a lower police-enforcement priority and create an advisory commission. Sales, impaired driving and unsafe conduct would remain enforcement concerns. Changing local priorities would not repeal state or federal drug laws.",
    contrast: "Morillo, Novick and Zimmerman supported sending the revised proposal from committee to Council. The other three had no vote in that committee.",
    takeaway: "This was still a pending proposal at the September 18 review. Advancing it from committee did not legalize psychedelics or establish a final Council position.",
    readings: all(card("Not a member of the committee that voted", "Had no committee vote on advancing the proposal to make personal use of natural psychedelics a lower police priority. This record supplies no final position on the proposal."), {
      "Angelita Morillo": card("Supported advancing the lower-enforcement-priority proposal", "Supported sending the revised proposal from committee to Council. It would make non-commercial personal use of natural psychedelics a lower police priority, without repealing state or federal drug laws."),
      "Steve Novick": card("Supported advancing the lower-enforcement-priority proposal", "Supported sending the revised proposal from committee to Council. It would make non-commercial personal use of natural psychedelics a lower police priority, without repealing state or federal drug laws."),
      "Eric Zimmerman": card("Supported advancing the lower-enforcement-priority proposal", "Supported sending the revised proposal from committee to Council. It would make non-commercial personal use of natural psychedelics a lower police priority, without repealing state or federal drug laws."),
    }),
  },
  permitting: {
    context: "Some building projects must also provide public improvements, such as sidewalk ramps and street trees. Council temporarily paused selected requirements to reduce development costs. It separately directed more work to make building rules consistent and improve the permit process.",
    contrast: "All five present supported the temporary pause; Zimmerman had supported advancing it from committee but missed the final vote. All six supported the next phase of permit reform.",
    takeaway: "The pause can lower a developer’s costs while leaving improvements undone or shifting costs to the City. A vote to improve permitting does not prove that permits are already faster or that more homes have been built.",
    readings: all(card("Supported pausing some developer-paid improvements", "Supported temporarily pausing selected requirements for improvements such as sidewalk ramps and street trees associated with development. Also supported further work to make building rules consistent and improve permitting. The pause could shift some improvement costs to the City."), {
      "Eric Zimmerman": card("Supported advancing the pause; missed the final vote", "Supported sending the proposed pause in selected development-upgrade requirements from committee to Council, but was absent from the final vote. Later supported further work to make building rules consistent and improve permitting."),
    }),
  },
  "traffic-transit": {
    context: "Vision Zero is Portland’s effort to prevent traffic deaths and serious injuries. Council renewed that effort and, in a separate vote, approved a route, general station locations and transit type for the 82nd Avenue project. The transit vote allowed further design and funding work.",
    contrast: "All six supported both proposals. Koyama Lane sponsored the traffic-safety resolution; Zimmerman added a requirement to examine traffic deaths among people experiencing homelessness.",
    takeaway: "These were planning and coordination votes. They did not fund every safety project or the full transit construction budget, and they do not show whether traffic deaths have since fallen.",
    readings: all(card("Supported traffic-safety work and the 82nd Avenue transit plan", "Supported renewing Portland’s effort to prevent traffic deaths and serious injuries, including community participation and attention to deaths among homeless residents. Also supported the route, general station locations and transit type chosen for further 82nd Avenue project planning."), {
      "Tiffany Koyama Lane": card("Sponsored traffic-safety work; supported the 82nd Avenue plan", "Sponsored the Vision Zero resolution to prevent traffic deaths and serious injuries, and supported adding community participation. Also supported the route, general station locations and transit type chosen for further 82nd Avenue project planning."),
      "Eric Zimmerman": card("Added attention to homeless residents’ traffic deaths", "Won a change requiring analysis of traffic deaths among people experiencing homelessness, then supported the renewed traffic-safety effort. Also supported the route, general station locations and transit type chosen for further 82nd Avenue project planning."),
    }),
  },
  privacy: {
    context: "City records can contain sensitive information about residents. Council created a central privacy office and adopted rules for managing data sharing, surveillance risks and reuse of information, including by artificial intelligence. A separate proposal concerned public disclosure and possible restrictions on data centers, which house large amounts of computing equipment.",
    contrast: "All six supported the final privacy measures and the data-center resolution. Zimmerman had opposed advancing an earlier version of the privacy rules from committee, then supported the revised final version.",
    takeaway: "Protecting information held by the City is different from regulating private data-center facilities. The data-center vote called for further action; it did not itself ban new facilities.",
    readings: all(card("Supported a central privacy office and rules for City-held information", "Supported creating a privacy office and adopting rules to manage how City departments share and reuse residents’ information, including surveillance and artificial-intelligence risks. Also supported disclosing data-center inquiries and pursuing future restrictions on those facilities."), {
      "Eric Zimmerman": card("Supported the final privacy rules after opposing an earlier version", "Supported creating a central privacy office. Opposed advancing an earlier version of the accompanying privacy rules from committee, then supported the revised final version. Also supported disclosing data-center inquiries and pursuing future restrictions on those facilities."),
    }),
  },
  infrastructure: {
    context: "Portland maintains roads, water systems, buildings and other public property. Different departments track their needs separately. Council requested a citywide plan to compare those needs, identify funding gaps and decide what should be repaired first.",
    contrast: "All six supported developing this citywide repair and investment plan.",
    takeaway: "This vote requested planning, including possible ways to borrow money. It did not approve a new bond or pay for the full repair backlog. Specific borrowing and fee votes appear in the water and street-funding topics.",
    readings: all(card("Supported a citywide plan for repairs and investment", "Supported comparing repair needs across roads, water systems, buildings and other City property, and examining how to pay for them. This was a planning vote; it did not itself authorize new borrowing or fund every repair.")),
  },
  elections: {
    context: "Portland’s Small Donor Elections program uses public money to match qualifying campaign donations. Council voted to revise how that program operates after the 2024 election. A separate vote updated enforcement of campaign-finance rules following a court ruling.",
    contrast: "All six supported the public campaign-financing changes and the final update to campaign-finance enforcement rules.",
    takeaway: "These votes concern election rules. They do not establish whether a particular candidate participates in public financing or has complied with every campaign-finance requirement.",
    readings: all(card("Supported changes to public campaign funding and enforcement", "Supported revising Small Donor Elections, the program that matches qualifying campaign donations with public money. Also supported the final update to enforcement of campaign-finance rules after a court ruling.")),
  },
  labor: {
    context: "Council approves negotiated contracts covering City workers’ pay, benefits and working conditions. It also voted to withdraw the previous Council’s permission for the City Attorney to file a labor-law complaint against AFSCME, a union representing City workers. Contract votes and decisions about how many jobs to fund are separate.",
    contrast: "All six supported the first Professional Workers contract and withdrawing permission to file the complaint. Koyama Lane was absent from three other contract votes; the other five supported those agreements.",
    takeaway: "Approving a contract sets employment terms. Later budgets still determine which jobs are funded. The budget topic explains the disagreements over layoffs and restoring positions.",
    readings: all(card("Supported the worker agreements and withdrawing complaint authority", "Supported the Professional Workers contract and later agreements with AFSCME, trade-union workers and civilian police-review employees. Also supported withdrawing permission for the City Attorney to file the labor-law complaint against AFSCME. These votes were separate from later staffing and layoff decisions."), {
      "Tiffany Koyama Lane": card("Supported the first Professional Workers contract; missed three later votes", "Supported the first Professional Workers contract and withdrawing permission to file the labor-law complaint against AFSCME. Was absent from votes on the AFSCME, trade-union and civilian police-review staff agreements."),
      "Mitch Green": card("Helped withdraw complaint authority and supported the worker agreements", "With Zimmerman, introduced the decision withdrawing permission for the City Attorney to file a labor-law complaint against AFSCME. Supported the Professional Workers, AFSCME, trade-union and civilian police-review staff agreements."),
      "Eric Zimmerman": card("Helped withdraw complaint authority and supported the worker agreements", "With Green, introduced the decision withdrawing permission for the City Attorney to file a labor-law complaint against AFSCME. Supported the Professional Workers, AFSCME, trade-union and civilian police-review staff agreements."),
    }),
  },
  children: {
    context: "The Children’s Levy uses tax revenue to fund organizations providing children’s services. Council first voted on whether to send proposed grant awards back for more work, then later approved roughly $71 million in grants for three years. A vote to reconsider the awards was not a vote to end children’s services.",
    contrast: "Koyama Lane, Morillo and Green supported sending the proposed awards back for reconsideration. Novick, Clark and Zimmerman opposed that delay. All six ultimately supported the grants.",
    takeaway: "The final agreement on funding followed a disagreement about how to choose recipients and when to approve the awards. Both parts belong in the record.",
    readings: six(
      card("Supported reconsidering the grant awards, then funding them", "Supported sending the proposed Children’s Levy grant awards back for more work before approval. Later supported the roughly $71 million package funding children’s services over three years."),
      card("Proposed reconsidering the grant awards, then supported final funding", "Moved to send the Children’s Levy grant recommendations back for more work. Later tried to keep waiting for revised recommendations; that change failed. Ultimately supported the roughly $71 million, three-year grant package."),
      card("Opposed sending the awards back; supported final funding", "Opposed sending the Children’s Levy grant recommendations back for reconsideration. Later supported the roughly $71 million package funding children’s services over three years."),
      card("Helped send the awards back, then supported final funding", "Seconded the proposal to return the Children’s Levy grant recommendations for more work. Later supported the roughly $71 million package funding children’s services over three years."),
      card("Opposed sending the awards back; supported final funding", "Opposed sending the Children’s Levy grant recommendations back for reconsideration. Later supported the roughly $71 million package funding children’s services over three years."),
      card("Opposed sending the awards back; supported final funding", "Opposed sending the Children’s Levy grant recommendations back for reconsideration. Later supported the roughly $71 million package funding children’s services over three years."),
    ),
  },
  "public-memory": {
    context: "Council voted to rename César E. Chávez Boulevard as Campesinos Boulevard, honoring farmworkers as a group. It also decided how to carry out the change, including public notice and new signs. The September 2026 vote came after earlier proposals had been sent back to committee.",
    contrast: "All six supported the final renaming. Koyama Lane co-sponsored it; Novick and Clark also advanced changes during its consideration.",
    takeaway: "This was an adopted street-renaming decision, not a proposal still waiting in committee. The final votes show agreement, with different roles in shaping the measure.",
    readings: all(card("Supported renaming the boulevard to honor farmworkers", "Supported renaming César E. Chávez Boulevard as Campesinos Boulevard and authorizing the City to notify the public and carry out the change. The new name honors farmworkers collectively."), {
      "Tiffany Koyama Lane": card("Helped propose the boulevard’s new name", "Co-sponsored renaming César E. Chávez Boulevard as Campesinos Boulevard to honor farmworkers collectively. Advanced a change accepted unanimously and voted for the final renaming."),
      "Steve Novick": card("Supported the renaming and helped amend the proposal", "Advanced a change accepted unanimously, then supported renaming César E. Chávez Boulevard as Campesinos Boulevard to honor farmworkers collectively."),
      "Olivia Clark": card("Supported the renaming and a quicker implementation process", "Moved the emergency clause to respond to community concerns and help staff carry out the change. Supported renaming César E. Chávez Boulevard as Campesinos Boulevard to honor farmworkers collectively."),
    }),
  },
  "animal-welfare": {
    context: "Council considered banning sales of products made from force-fed birds, including foie gras produced that way. The proposal delayed the start of the sales restrictions so affected businesses could adjust. It did not ban all poultry products.",
    contrast: "Koyama Lane, Morillo, Novick and Green supported the sales restriction. Clark and Zimmerman opposed it.",
    takeaway: "This vote shows a difference over regulating a particular production practice. It does not establish a councilor’s position on every animal-welfare or business regulation.",
    readings: all(card("Supported banning sales of products from force-fed birds", "Supported prohibiting sales of products made from force-fed birds, with a delayed start so affected businesses could adjust."), {
      "Olivia Clark": card("Helped revise the proposal, then opposed the sales ban", "Advanced a change Council accepted, then voted against the final ban on sales of products from force-fed birds. Helping revise the proposal did not change her final no vote."),
      "Eric Zimmerman": card("Opposed the ban on products from force-fed birds", "Voted against the final proposal to prohibit sales of products made from force-fed birds, including foie gras produced that way."),
    }),
  },
};
