import {
  candidate as c,
  electionSource,
  officialSources,
  pamphletSource as p,
  type Geography,
  type Race,
  type Candidate,
} from "./types";
const m = (n: number) => [p("multnomah", n)];
const w = (n: number) => [p("washington", n)];
const k = (n: number) => [p("clackamas", n)];
function race(
  id: string,
  title: string,
  geography: Geography,
  authority: string,
  stakes: string,
  comparison: string,
  candidates: Candidate[],
): Race {
  const key = geography.toLowerCase() as
    "multnomah" | "washington" | "clackamas";
  return {
    id,
    title,
    geography,
    jurisdiction: `${geography} County`,
    seats: 1,
    method:
      geography === "Multnomah" ? "Ranked choice · one seat" : "Vote for one",
    authority,
    stakes,
    comparison,
    candidates,
    rosterSource: electionSource(
      `${geography} County election office · candidate list`,
      officialSources[key],
    ),
    rosterStatus: "Official list checked",
  };
}
const commissioner =
  "Commissioners adopt county budgets and policies. They share authority as a board; one commissioner cannot enact a proposal alone.";
export const countyRaces: Race[] = [
  race(
    "multnomah-chair",
    "Multnomah County Chair",
    "Multnomah",
    "The chair leads county administration and proposes the budget; the county board must approve spending and legislation.",
    "Homelessness services, behavioral health, public health, preschool, and accountability for contracted services.",
    "All three candidates criticize current outcomes. Singleton stresses service-system experience and collaboration; Brim-Edwards stresses implementation, contract accountability and tax relief; Meieran argues for a more fundamental management reset.",
    [
      c(
        "Julia Brim-Edwards",
        "County commissioner; former school-board member and Nike executive.",
        "Promises faster delivery, scrutiny of contractors and a lower burden from local taxes and fees.",
        [
          "Connect people to treatment, recovery housing and shelter.",
          "Require contractors to report spending and results.",
          "Work with labor and business on jobs and affordability.",
        ],
        "Her program combines expanded access to services with fiscal restraint. Her campaign’s claims of results require separate outcome checks.",
        "Which taxes or administrative costs would you reduce, and which services would you protect?",
        m(32),
      ),
      c(
        "Sharon Meieran",
        "Physician, former county commissioner and founder of Fixing Multnomah County.",
        "Argues that the county spends without clear goals and needs a different approach to management and accountability.",
        [
          "Set specific goals and accountability for county spending.",
          "Bring clinical experience to addiction and mental-health policy.",
          "Challenge institutional delays in emergency services.",
        ],
        "Her central argument is that fragmented management undermines services. Her statement’s claims about comparative spending and outcomes are not independently established here.",
        "What authority, staffing and service changes would your first budget propose?",
        m(33),
      ),
      c(
        "Shannon Singleton",
        "County commissioner; social worker, former JOIN executive director and housing-policy director.",
        "Emphasizes practical experience with homelessness and bringing service users and providers into decisions.",
        [
          "Build more effective homelessness-service systems.",
          "Support affordable housing and well-paid union jobs.",
          "Work with providers, businesses, neighbors and people who disagree.",
        ],
        "Her argument is for redesign informed by frontline experience. Collaboration is a means; readers should still ask for measurable deadlines and costs.",
        "Which service outcomes would you publish, and what would trigger a contractor or program change?",
        m(32),
      ),
    ],
  ),
  race(
    "multnomah-district-2",
    "Multnomah Commissioner · District 2",
    "Multnomah",
    commissioner,
    "Housing stability, behavioral health, family services and how county resources reach North and Northeast Portland.",
    "Compare concrete mechanisms: performance contracts, housing-retention reporting, public housing, culturally specific care, and coordination with employers.",
    [
      c(
        "Bruce Broussard",
        "Retired veterans-service nonprofit administrator, veteran and former newspaper publisher.",
        "Emphasizes resource management, veterans and support for low-income residents.",
        [
          "Improve responses to homelessness, mental illness and drug use.",
          "Address living costs that outpace wages.",
          "Apply community and veterans-service experience.",
        ],
        "The statement offers broad priorities and a long service history, but few specified program changes.",
        "Which program would you change first, and what result would you measure?",
        m(34),
      ),
      c(
        "Serena Cruz",
        "Former county commissioner and chief operating officer; nonprofit and construction-business experience.",
        "Wants to align housing, treatment and family services around more effective administration.",
        [
          "Coordinate housing, treatment and supportive services.",
          "Make preschool effective and accessible.",
          "Support small businesses and paths from renting to ownership.",
        ],
        "She presents management experience as a way to deliver social-policy goals. Her statement does not itself verify the outcomes attributed to past programs.",
        "What would change in contracting and oversight compared with your previous county roles?",
        m(35),
      ),
      c(
        "Herman Greene",
        "Pastor, nonprofit leader and former Portland Public Schools board member.",
        "Connects stable housing with employment and measurable service performance.",
        [
          "Use housing-retention targets and performance-based contracts.",
          "Link county investments to jobs and apprenticeships.",
          "Coordinate crisis response, treatment and housing.",
        ],
        "His proposed accountability tools are more specific than a general promise of transparency. Their usefulness depends on targets and consequences.",
        "What would happen to a contract that repeatedly misses its housing-retention target?",
        m(34),
      ),
      c(
        "Nathan Ong Norris",
        "Hazardous-waste technician, union member and community organizer.",
        "Identifies as a democratic socialist and favors expanded public provision and climate accountability.",
        [
          "Support Preschool for All, social housing and libraries.",
          "Implement the Climate Justice Plan and hold polluters accountable.",
          "Reduce CEI Hub risks and prevent expansion.",
        ],
        "He treats public services and climate protection as shared guarantees. The principal implementation question is sustained funding.",
        "What recurring revenue would support expanded services without weakening existing ones?",
        m(36),
      ),
      c(
        "Tony Robertson",
        "BOLI civil-rights division manager with housing and workforce experience.",
        "Wants agencies to coordinate better and demonstrate what taxpayer spending achieves.",
        [
          "Improve housing, homelessness and behavioral-health services.",
          "Strengthen economic opportunity and relationships with small businesses.",
          "Make public spending more transparent.",
        ],
        "He emphasizes operational and civil-rights experience. The reviewed statement identifies priorities without a detailed first-year program.",
        "Which coordination failures would you fix first, and how would the public track progress?",
        m(37),
      ),
      c(
        "Bri Williams",
        "County mental-health consultant and social worker.",
        "Emphasizes prevention and services designed with the communities using them.",
        [
          "Strengthen eviction prevention and affordable housing.",
          "Expand culturally specific behavioral-health services.",
          "Invest in youth, restorative justice and survivor services.",
        ],
        "Her safety approach emphasizes preventing harm and stabilizing families. Funding choices and evidence of outcomes remain central.",
        "How would you evaluate prevention programs and choose between competing service needs?",
        m(35),
      ),
      c(
        "Nabil Zaghloul",
        "County social and economic services program director.",
        "Proposes housing-retention tracking and a public county performance report card.",
        [
          "Publish housing retention at three, six, nine and twelve months.",
          "Combine housing, treatment and employment for sustained recovery.",
          "Introduce homelessness-reduction and accountability legislation.",
        ],
        "His proposals make continued stability, rather than initial placement alone, the test of success. Past program success rates remain candidate claims pending independent verification.",
        "What data would be independently checked, and how would reports protect client privacy?",
        m(36),
      ),
    ],
  ),
  race(
    "multnomah-auditor",
    "Multnomah County Auditor",
    "Multnomah",
    "The auditor independently evaluates county performance and follows up on recommendations; the office does not administer county services.",
    "Timely, independent scrutiny of spending and results.",
    "One named candidate appears on the checked filing list.",
    [
      c(
        "Nicole Pexton",
        "Government performance auditor and chief audit executive.",
        "Proposes shorter, more focused audits and a public report card on recommendations.",
        [
          "Shorten audit timelines and broaden coverage.",
          "Publish what was audited and which recommendations remain open.",
          "Explore early advisory work to identify problems sooner.",
        ],
        "The tradeoff is speed and breadth versus depth; advisory work also needs safeguards for audit independence.",
        "How would you preserve independence when advising programs you may later audit?",
        m(38),
      ),
    ],
  ),
  race(
    "multnomah-sheriff",
    "Multnomah County Sheriff",
    "Multnomah",
    "The sheriff manages county law enforcement and corrections within the county budget and applicable law.",
    "Jail conditions, community safety, staffing, behavioral health and reentry.",
    "One named candidate appears on the checked filing list. An uncontested race still warrants scrutiny of performance.",
    [
      c(
        "Nicole Morrisey O’Donnell",
        "Incumbent sheriff; former undersheriff and law-enforcement and corrections chief deputy.",
        "Emphasizes staffing stability, transparent corrections oversight and community safety.",
        [
          "Maintain safe, accountable corrections operations.",
          "Expand behavioral-health and reentry work.",
          "Strengthen workforce retention and public reporting.",
        ],
        "Her statement attributes improvements to her leadership. Crime trends and staffing outcomes should be evaluated separately from campaign attribution.",
        "Which independent jail-review recommendations remain unfinished, and when will they be completed?",
        m(38),
      ),
    ],
  ),
  race(
    "washington-chair",
    "Washington County Chair · At-large",
    "Washington",
    commissioner,
    "Housing, treatment, public safety, economic development and the county’s fiscal choices.",
    "Both emphasize affordability and safety. Treece puts more emphasis on tax restraint and business growth; Fai highlights housing and treatment investment and a larger contribution from data centers.",
    [
      c(
        "Nafisa Fai",
        "County commissioner with public-health and community-building experience.",
        "Connects affordability and safety with housing, treatment and corporate contributions.",
        [
          "Support housing, eviction prevention and addiction treatment.",
          "Make data centers contribute more fairly.",
          "Protect farmland and invest in transportation and jobs.",
        ],
        "Her account stresses investment and distribution of costs. Claims of past delivery in the pamphlet are campaign claims.",
        "What specific data-center tax or fee changes would you propose, and what revenue would they produce?",
        w(4),
      ),
      c(
        "Pam Treece",
        "County commissioner with economic-development, teaching and small-business experience.",
        "Puts jobs, housing construction and restraint on new taxes at the center of affordability policy.",
        [
          "Support business growth and housing production.",
          "Invest in public safety and congestion reduction.",
          "Protect public health and residents facing federal immigration enforcement.",
        ],
        "She emphasizes economic growth and stable operations. Tax restraint requires explicit choices when service demands exceed revenue.",
        "Which services take priority under a constrained budget, and what would you defer?",
        w(4),
      ),
    ],
  ),
  race(
    "washington-district-4",
    "Washington Commissioner · District 4",
    "Washington",
    commissioner,
    "Western Washington County growth, farmland, data centers, housing and infrastructure.",
    "Sinclair calls for ending data-center tax breaks and halting farmland expansion. Callaway calls for careful evaluation of developments without the same categorical commitment.",
    [
      c(
        "Steve Callaway",
        "Former Hillsboro mayor, school principal and teacher.",
        "Emphasizes experience, affordability, public safety and responsible growth.",
        [
          "Scrutinize budgets and major development impacts.",
          "Protect farmland and natural resources.",
          "Address homelessness, addiction and behavioral health.",
        ],
        "His position leaves more room for project-by-project decisions than Sinclair’s. Careful evaluation is not a promise to prohibit data centers.",
        "What criteria would lead you to reject a data-center development or tax incentive?",
        w(5),
      ),
      c(
        "Kipperlyn Sinclair",
        "Hillsboro councilor and local-food business leader.",
        "Prioritizes farmland protection and ending public subsidies for data-center expansion.",
        [
          "End data-center tax breaks and halt expansion onto farmland.",
          "Support local businesses, farm infrastructure and transit-oriented growth.",
          "Protect due process, privacy and transparency.",
        ],
        "Her development policy is more restrictive toward data centers. Her allegations about prior decisions and her opponent require direct record review before adoption as fact.",
        "Which incentives can the county legally change, and what replaces the projected revenue or investment?",
        w(5),
      ),
    ],
  ),
  race(
    "clackamas-position-2",
    "Clackamas Commissioner · Position 2",
    "Clackamas",
    commissioner,
    "Land use, transportation, taxes, treatment and public safety.",
    "Both oppose tolling and stress affordability. Savas emphasizes current service and capital projects; Shull emphasizes limiting government and resisting Metro authority.",
    [
      c(
        "Paul Savas",
        "Incumbent county commissioner and former small-business owner.",
        "Emphasizes services and infrastructure while holding the line on taxes.",
        [
          "Support affordable housing and the recovery campus.",
          "Oppose I-205 tolling and protect sheriff funding.",
          "Support a data-center moratorium and senior property-tax deferral.",
        ],
        "His platform relies on delivering investments within fiscal constraints. The claimed project totals need independent completion and cost checks.",
        "What ongoing operating funds will support the new housing and treatment facilities?",
        k(17),
      ),
      c(
        "Mark Shull",
        "Former county commissioner, retired military officer and business owner.",
        "Runs on tax restraint, local control and state land-use reform.",
        [
          "Seek senior property-tax relief and oppose new taxes.",
          "Oppose I-205 tolls and Metro mandates.",
          "Change land-use rules to permit housing while protecting rural character.",
        ],
        "His housing agenda depends partly on Salem, not just the county board. The scope of proposed program cuts is not specified in the statement.",
        "Which programs would you cut, and which land-use changes require state legislation?",
        k(17),
      ),
    ],
  ),
  race(
    "clackamas-position-4",
    "Clackamas Commissioner · Position 4",
    "Clackamas",
    commissioner,
    "Housing supply, data-center development, county services and economic growth.",
    "Both support limits on large data centers. Helm describes a pause for rulemaking; Smith describes opposition to bringing large-scale data centers into the county.",
    [
      c(
        "Diana Helm",
        "County commissioner, business owner and former Damascus mayor.",
        "Emphasizes permitting reform, local jobs and a pause to evaluate large data centers.",
        [
          "Reduce unnecessary housing and permitting barriers.",
          "Use a data-center moratorium to study impacts and involve residents.",
          "Support shelter, recovery and related services.",
        ],
        "Her data-center position is a time-out, not necessarily a permanent ban. Housing reforms need specific standards to be assessed.",
        "What findings would justify allowing or rejecting data centers after the moratorium?",
        k(18),
      ),
      c(
        "R W Smith",
        "Environmental consultant with community-action and climate committee experience.",
        "Opposes large-scale data centers and emphasizes resource protection, affordability and transparent contracts.",
        [
          "Keep large-scale data centers out of the county.",
          "Protect electricity, water, farmland and taxpayers.",
          "Improve access to treatment with measurable outcomes.",
        ],
        "His position is more categorical than a temporary pause. His service goals still require a funded delivery plan.",
        "What development rules would implement your data-center position, and how would treatment access improve?",
        k(18),
      ),
    ],
  ),
  race(
    "clackamas-sheriff",
    "Clackamas County Sheriff",
    "Clackamas",
    "The sheriff runs county law enforcement and jail operations, subject to law and county appropriations.",
    "Patrol, investigations, jail services, staffing and leadership of the sheriff’s office.",
    "Both emphasize experience and fiscal responsibility. O’Neil stresses organizational accountability; Rhodes spells out traffic enforcement, property-crime follow-up and fentanyl investigations.",
    [
      c(
        "Brad O’Neil",
        "Undersheriff with patrol, investigations and search-and-rescue leadership experience.",
        "Emphasizes professional leadership, measurable performance and public trust.",
        [
          "Improve response, investigations, jail operations and frontline services.",
          "Allocate resources responsibly under budget pressure.",
          "Set expectations, report results and strengthen relationships.",
        ],
        "The core distinction in his statement is management and accountability. His comparative claims about qualifications require direct credential checks.",
        "Which performance measures and disciplinary disclosures would you publish?",
        k(16),
      ),
      c(
        "James Rhodes",
        "Appointed sheriff; former undersheriff and Wilsonville police chief.",
        "Prioritizes frontline operations, traffic enforcement and serious-crime investigations.",
        [
          "Protect patrol, jail and investigative services.",
          "Improve property-crime follow-up and restore traffic and DUII enforcement.",
          "Target fentanyl traffickers and coordinate with prosecutors.",
        ],
        "His statement identifies operational priorities more explicitly than their cost or staffing requirements.",
        "What staffing or spending would change to restore traffic enforcement?",
        k(16),
      ),
    ],
  ),
  race(
    "clackamas-clerk",
    "Clackamas County Clerk",
    "Clackamas",
    "The clerk administers elections and records, including marriage and property records, under state law.",
    "Election administration, ballot access, public confidence and reliable records.",
    "McMullen proposes continued professional administration and broader access. Reaksecker proposes replacing machine tabulation with hand counting. The factual basis for changing the counting system deserves scrutiny.",
    [
      c(
        "Catherine McMullen",
        "Incumbent clerk; elections administrator and former public librarian.",
        "Emphasizes election security, accessible services and transparent administration.",
        [
          "Maintain voter records and secure ballot processes.",
          "Expand voter education, access and public observation.",
          "Provide affordable and convenient records and marriage services.",
        ],
        "Her argument is continuity after administrative changes. Her pamphlet’s claims of improved performance remain subject to independent evaluation.",
        "What independent measures show accuracy, accessibility and timely results?",
        k(14),
      ),
      {
        ...c(
          "Mark Reaksecker",
          "Retired dentist and former dental-practice owner.",
          "Advocates hand counting ballots, local voter-roll checks and watermarked ballots.",
          [
            "Replace machine tabulation with hand counting.",
            "Verify voter rolls at the county level.",
            "Use watermarks to authenticate ballots.",
          ],
          "His argument implies machine-counted ballots lack a verifiable paper trail. Oregon uses paper ballots and post-election hand-count audits; the existence of voting equipment alone is not evidence of inaccurate results.",
          "What evidence supports replacing the current system, and what would staffing, accuracy testing and certification compliance cost?",
          k(14),
        ),
        record: [
          {
            text: "The Secretary of State describes Oregon’s paper-ballot system, isolated tabulation equipment, testing and post-election hand-count audits. This contradicts the premise that machine counting inherently eliminates a paper trail.",
            source: {
              label: "Oregon Secretary of State · Election Integrity",
              url: "https://sos.oregon.gov/elections/Pages/security.aspx",
              kind: "Public record",
              date: "Reviewed September 18, 2026",
            },
          },
        ],
      },
    ],
  ),
  race(
    "clackamas-treasurer",
    "Clackamas County Treasurer",
    "Clackamas",
    "The treasurer safeguards and invests county funds and manages treasury operations; the board determines appropriations.",
    "Cash security, liquidity, investment returns and financial controls.",
    "One named candidate appears on the checked list.",
    [
      c(
        "Brian T Nava",
        "Incumbent treasurer and former county and state auditor.",
        "Emphasizes prudent investment, cash controls and improvements to banking operations.",
        [
          "Keep funds safe and liquid while earning returns.",
          "Strengthen cash-control training.",
          "Improve convenience and efficiency of treasury operations.",
        ],
        "Investment return must be assessed alongside risk and liquidity, not as an isolated performance score.",
        "What benchmarks and risk measures will you publish for the investment portfolio?",
        k(15),
      ),
    ],
  ),
];
