"""Publish question answers and limitations as structured, reproducible findings."""
import json
from common import *

def run():
    s=json.loads((WORK/'summary.json').read_text())
    enrichment=json.loads((RESEARCH/'enrichment.json').read_text())
    details=json.loads((RESEARCH/'independent-spending.json').read_text())
    address=json.loads((ROOT/'src/lib/campaign-finance/district-address-data.json').read_text())
    total=lambda b:sum(r['amount_cents'] for r in s['bases'] if r['basis']==b)
    money=lambda c:f'${c/100:,.2f}'
    questions=[]
    def q(track,question,answer,method,evidence,status='qualified',limit='Current reported versions only; findings describe the fixed observation window, not complete election cycles.'):
        questions.append({'id':f'Q{len(questions)+1:03}','track':track,'question':question,'status':status,'answer':answer,'method':method,'evidence':evidence,'limitation':limit,'population':'ORESTAR snapshot, 2025-01-01 through 2026-09-27 unless explicitly narrowed','denominator':'As specified in the linked metric definition; dollar measures use Amount, not Aggregate Amount.','snapshot':SNAPSHOT,'reviewStatus':'calculation-reviewed; interpretive limitations retained'})
    def gap(track,question,reason,needed):q(track,question,reason,needed,[],status='currently unanswerable',limit=reason)
    q('Overall financial system','How much cash is reported as contributions?',money(total('cash_contribution')),'Sum Cash Contribution Amount in integer cents.',['financial-bases'],'answered')
    q('Overall financial system','How much is paid, supported in kind, borrowed or recorded as obligations?',f"Cash expenditures {money(total('cash_payment'))}; in-kind support {money(total('noncash_support'))}; loans received {money(total('loan_received'))}; new reported obligations {money(total('obligation'))}. These are separate bases.",'Explicit 24-subtype accounting map.',['financial-bases'],'answered')
    q('Overall financial system','How much money entered and left the observed network?','Boundary tables separate observed committees, committees outside the filer set, unidentified categories and counterparties with no committee ID. The last group is not automatically outside money.','Classify both sides by authoritative committee ID; do not sum reciprocal filings as economic inflows.',['network-boundary'])
    gap('Overall financial system','Where does money accumulate, and what is the complete closing balance?','Flows alone cannot establish reserves. Official account summaries must be reconciled by committee/year and carried into the balance ledger.','Verified opening balances, summary cash definitions, year roll-forward and unresolved differences.')
    q('Concentration and dependency','How concentrated are visible sources of cash contributions?',f"Across {s['concentration']['visible_source_groups_including_committees']['groups']:,} visible record groups, Gini is {s['concentration']['visible_source_groups_including_committees']['gini']:.6f}; the top ten provide {s['concentration']['visible_source_groups_including_committees']['top10_share']:.2%} of identified cash dollars.",'Gini, HHI, top-source shares and effective number, conditional on positive visible groups.',['donor-record-groups','dependency'])
    q('Concentration and dependency','Which committees depend most on a few visible sources?','The dependency table gives every committee’s top-one/top-ten shares, HHI, Gini, effective group count and unidentified share; small denominators remain visible.','Within-committee cumulative source amounts, with a separate total-cash denominator.',['dependency'])
    q('Concentration and dependency','How do transfers and unidentified money change the picture?',f"Strict reciprocal transfers total {money(s['transfers']['strict_circulation_cents'])}. Disclosure sensitivity reports a diffuse-source HHI infimum and an upper scenario attaching unidentified amounts to the largest visible source.",'Separate transfer basis; partial-identification scenarios, not estimated hidden identities.',['matched-transfers','dependency'])
    q('Small donors and participation','Do small gifts imply small cumulative contributors?','No. Gifts are accumulated by committee and conservative record group; visible cumulative totals can exceed any individual gift-size threshold. Prior unitemized gifts cannot be allocated back to people.','Compare gift-size bands with cumulative donor–committee totals.',['gift-sizes','donor-committee','dependency'])
    q('Small donors and participation','How common is repeat giving?','The donor–committee evidence contains gift counts, first/last dates and cumulative giving; the dependency table reports each committee’s repeat-group share. These are record-group cohorts, not verified person counts.','Repeat = more than one cash-contribution row in the observed interval.',['donor-committee','dependency'])
    gap('Small donors and participation','How many distinct people gave, including anonymous and miscellaneous activity?','Aggregate rows are not people. A total person count or retention rate covering those rows is not identifiable from this snapshot.','Itemized source identities and longitudinal resolution; do not impute people from transaction counts.')
    q('Businesses, labor, organizations and self-financing','What do reported contributor types show?','Separate totals are published for filer-classified individuals, business entities, labor organizations, candidate/family, political committees and unspecified types. These are reported classifications, not reviewed industries.','Address-book type totals on cash-contribution basis.',['reported-contributor-types'])
    gap('Businesses, labor, organizations and self-financing','Which industries, corporate families or documented affiliations fund which races?','A complete reviewed organizational-affiliation crosswalk has not been established. Similar names or employment fields are insufficient to assign industry ownership.','Official organizational records, effective dates and reviewed entity links.')
    gap('Businesses, labor, organizations and self-financing','Are employee contributions organizational contributions or evidence of coordination?','Employment fields alone do not establish direction, reimbursement or coordination; occupation/employer missingness is material.','Separate individual giving from organizational funds; source-based case review and alternative explanations.')
    q('Geography and representation','How much reported cash comes from Oregon, outside Oregon or an unknown state?','The geographic evidence retains all three categories and exact dollar totals; unknown locations are not silently excluded from the overall denominator.','Reported counterparty-state classification.',['geography','cities'])
    gap('Geography and representation','Which neighborhoods are underrepresented relative to population?','City strings do not identify neighborhoods or districts. No population-normalized neighborhood measure is published without an audited geographic crosswalk.','Official boundaries, Census denominators, validated geographic joins and missing-location sensitivity.')
    gap('Geography and representation','How much giving comes from outside a candidate’s district?','A reported city or postal location is not a verified district residence.','Effective district boundaries and reviewed geocoding; publish geographic summaries only.')
    q('Political funding networks','Which selected committees share visible individual donor groups?','All 435 pairs among the 30 committees with most visible individual groups are tested. The underlying graph has 31,543 groups and 32,107 distinct committee links.','Bipartite graph, Jaccard overlap, degree-preserving edge swaps, two fixed seeds, 398 null draws, Benjamini–Hochberg correction.',['shared-donor-tests'])
    q('Political funding networks','Are shared-source patterns more pronounced than popularity alone predicts?','The pair table reports observed overlap, null expectation, excess shared groups and adjusted exploratory p-values. The null preserves donor-group and committee degrees within the selected subgraph.','Conditional MCMC permutation test; no coordination inference.',['shared-donor-tests'])
    q('Political funding networks','Are detected communities stable or evidence of political coordination?','The two fixed-seed community partitions agreed on the selected projection. That diagnostic does not establish stability under entity-resolution changes, missing donors or different populations, and does not establish coordination.','Weighted projection and Louvain diagnostic; explicit scope limits.',['shared-donor-tests'])
    q('Committee transfers and intermediaries','Which transfers can be reconciled on both sides?',f"{s['transfers']['strict_pairs']:,} unique same-day reciprocal pairs, totaling {money(s['transfers']['strict_circulation_cents'])}; both filings retained.",'Reciprocal authoritative IDs, exact cents, same day and uniqueness within a seven-day candidate window.',['matched-transfers'],'answered')
    q('Committee transfers and intermediaries','Which plausible transfers remain ambiguous?',f"{s['transfers']['ambiguous_candidate_pairs']:,} candidate pairs fail strict same-day uniqueness; these are pair counts, not counts of distinct economic transfers.",'Seven-day candidate matching; no greedy one-to-one assignment.',['ambiguous-transfers'])
    gap('Committee transfers and intermediaries','Which donor’s dollar paid a particular vendor?','Commingled funds do not identify dollar-level provenance. Financial paths can be possible without being uniquely attributable.','Association-ledger review and bounded allocation scenarios; never present scenarios as tracing proof.')
    q('Campaign services economy','Who receives the largest cash payments and serves many committees?','The payee evidence ranks conservative noncommittee cash-payee groups and counts their filing-committee relationships. Payments are not necessarily vendor earnings.','Group cash payments; exclude authoritative committee counterparties and disclosure categories.',['payee-record-groups'])
    q('Campaign services economy','How is spending divided across advertising, management, staffing and other purposes?','Exact reported purpose-code bundles are tabulated. A multi-code payment is counted once in its bundle, not fully attributed to every category.','Mutually exclusive source-code combinations; no invented allocations.',['purpose-bundles'])
    gap('Campaign services economy','How much of each vendor’s receipts is profit, reimbursement or pass-through?','Campaign reports show committee payments, not the recipient’s cost structure or onward transfers.','Invoices, association details, reimbursement review and recipient financial records.')
    gap('Independent spending','Who spends to support or oppose each candidate or measure?','The CSV does not expose complete target allocations. Public transaction detail and support/oppose records are mapped separately; target coverage must be reconciled before statewide totals.','Acquire independent-expenditure detail, target amounts and support/oppose flags; reconcile multi-target totals.')
    gap('Independent spending','How much outside spending does each race receive relative to candidate-controlled spending?','This comparison requires complete target-to-race allocation and a reviewed candidate-committee crosswalk, not just expenditure names.','Separate candidate-controlled spending from independent support/oppose allocations.')
    q('Portland public financing','What is the official source for participation and matching funds?','Portland’s 2026 program page identifies certification status and distributed matching funds. These are separate source observations and must not be added again to ORESTAR receipts.','Archive City program records and reconcile payments by committee/date/amount.',['portland-public-financing'])
    gap('Portland public financing','Does participation cause broader local support?','Program participation is selected, not randomly assigned; the current matched race sample does not support a causal effect estimate.','Comparable-campaign descriptive comparisons, selection analysis, validated local-donor definitions.')
    q('Timing and campaign strategy','When do reported cash and noncash resources arrive?','Monthly transaction-date measures are available for each financial basis. September 2026 contains only days 1–27 and remains subject to later filing.','Inclusive monthly aggregation with basis separation.',['monthly'],'answered')
    q('Timing and campaign strategy','Are apparent surges transaction activity or filing delays?','Current-version filing lag and transaction-date activity are published separately. An amended row’s lag is not its original public-disclosure latency.','Stratify by Original versus Amended status; no causal event attribution.',['filing-lag','amendments','monthly'])
    gap('Timing and campaign strategy','Do statistically detected breaks reveal a campaign strategy?','A change point does not identify intention. Election alignment and sufficient comparable pre/post observations are needed before calling a change strategic.','Prespecified event windows, reporting-lag checks and campaign-source corroboration.')
    q('Financial resilience','What if a committee lost its largest observed source?','The dependency table subtracts the largest visible cash-source group from visible receipts. This is explicitly a forgone-receipts scenario, not a prediction of current liquidity.','Within-committee top-source exclusion, no beginning-balance assumption.',['dependency'])
    gap('Financial resilience','What are current debt, reserves and runway?','New loans and obligations are flows, not outstanding balances. Available account summaries and transaction associations require reconciliation before a statewide debt or runway claim.','Verified opening balances, repayment/forgiveness schedules, cancellations and operating-burn definitions.')
    gap('Elections and outcomes','Who will win the November 2026 election, and how did spending affect it?','The election has not happened at the September 27 cutoff. No outcome or causal analysis is possible.','No outcome model for pending elections.')
    gap('Elections and outcomes','Across completed elections, does fundraising or spending composition explain results?','A sufficiently complete certified-result and race crosswalk with pre-election finance windows has not yet been validated for this edition. A multilevel model without that foundation would be misleading.','Certified outcomes; race-appropriate single-seat versus multi-seat measures; grouped/temporal holdouts, regularization and uncertainty.')
    q('Disclosure and visibility','How many current rows are amendments and where are fields missing?','Amendment and missingness tables preserve counts by transaction family and field. Missingness is not automatically a violation: field requirements differ by record type.','Current-version status and explicit blank-field counts.',['amendments','missingness'],'answered')
    q('Disclosure and visibility','What does aggregate reporting conceal?',f"32,258 contribution-family rows total {money(sum(r['amount_cents'] for r in s['disclosure'] if r['family']=='Contribution'))}. They cannot establish distinct donors, cross-campaign ties or person-level giving histories.",'Committee-scoped disclosure buckets, excluded from identity graph.',['disclosure'],'answered')
    gap('Disclosure and visibility','What exactly could a voter know on an earlier date?','The current-version snapshot omits superseded amendments and deletions. Current Filed Date alone cannot reconstruct a past public view.','Historical version retrieval with original disclosure and amendment timestamps.')
    gap('Connections to governing','Do funders or vendors also lobby, hold public contracts or appear in policy proceedings?','Official lobbying/consultant disclosure sources are located, but complete dated and reviewed entity joins have not been established. Name-only coincidences are not published as connections.','Verified public-record joins, effective dates and case-specific source review.')
    gap('Connections to governing','Did a contribution cause a vote, contract or government decision?','The transaction ledger cannot establish motive or causation. Even verified overlap needs plausible alternative explanations and defensible comparisons.','Dated decision records, policy context and a credible identification strategy; otherwise descriptive case studies only.')
    q('Unusual patterns and counterexamples','Which large records deserve closer source review?','The 100 largest cash records are provided as magnitude-based leads, not a misconduct score. Legitimate committee transfers, media buys and aggregate records can be large.','Absolute magnitude ranking with accounting basis and source transaction IDs.',['largest-cash-records'])
    q('Unusual patterns and counterexamples','Could ordinary operations explain apparent anomalies?','Yes: a $1,208,352.82 PAC payment and next-day receipt are outside the strict same-day transfer match. Repeated names can be separate identities or address variants. Both counterexamples remain visible.','Review seven-day transfer candidates and same-name candidate groups rather than auto-merging.',['ambiguous-transfers','same-name-candidates'])
    gap('Unusual patterns and counterexamples','Do round amounts, synchronization or reciprocal ties establish misconduct?','No. Exploratory anomalies require peer comparisons, multiple-testing controls and original-source review; normal reporting conventions can generate them.','Robust within-peer methods plus investigation log and counterevidence; no automated allegation labels.')
    # Update questions whose required official evidence has now been acquired.
    updates={
        'Q004':('qualified',f"Official summaries cover {enrichment['coverage']['profiles']} selected committees and {enrichment['coverage']['account_years']} committee-years. {enrichment['accountAgreement']['agrees']} agree with snapshot cash flows; {enrichment['accountAgreement']['differences']} retain differences. This is not statewide balance coverage.",['account-summaries']),
        'Q028':('qualified',f"The City reports {money(enrichment['cityMatchingDistributedCents'])} distributed to 13 certified candidates; reviewed matching receipts in the snapshot total {money(enrichment['snapshotMatchingReportedCents'])}. These overlapping sources are not added. Differences remain visible by candidate.",['portland-public-financing','public-matching-receipts']),
        'Q034':('qualified','Selected committee profiles now show official opening/closing cash and reported outstanding debt, with source timestamps and snapshot reconciliation. Statewide coverage and runway estimates remain unavailable.',['account-summaries']),
    }
    for row in questions:
        if row['id'] in updates:
            row['status'],row['answer'],row['evidence']=updates[row['id']]
            row['limitation']='Targeted committee coverage only. Official summary observations are not independently audited bank statements. City disbursements and committee receipts are overlapping records, not additive funding.'
        if row['id']=='Q016':
            inside=sum(address['totals'][key]['cents'] for key in ('address_inside','zip_inside'))
            outside=sum(address['totals'][key]['cents'] for key in ('address_outside','state_outside','zip_outside'))
            uncertain=address['totals']['uncertain']['cents']
            row.update(status='qualified',
                answer=f"Across 17 reviewed Portland District 3/4 committees, reported nonmatching cash classifies as {money(inside)} from an address or whole ZIP area inside the candidate district, {money(outside)} outside, and {money(uncertain)} unresolved. The local City address-point join placed {address['geography']['locallyMatchedTransactions']} transactions exactly. City matching receipts stay separate.",
                method='Local exact street-address/ZIP join to public City address points and official council polygons; unmatched records use only whole-ZCTA inside/disjoint classifications; aggregate and boundary-crossing ZIPs stay uncertain.',
                evidence=['zip-map/candidate-district-address-summary'],
                limitation='A reported source address is not verified residence or eligibility. ZIP proxies are approximate. Only 17 reviewed committees are covered, and transaction counts are not unique people.',
                population='17 reviewed Portland District 3/4 candidate committees, 2025-01-01 through 2026-09-27',
                denominator='Gross nonmatching cash contribution transactions; reviewed City matching payments are reported separately.')
        if row['id']=='Q026':
            row.update(status='qualified',
                answer=f"{details['parsed_records']} of {details['searched_records']} records in the independent-checkbox search have parsed target details, yielding {details['allocation_rows']} allocation rows. {details['gap_records']} records remain gaps and {details['reconciliation_differences']} parsed records have allocation differences. Partial evidence is published; it is not a complete statewide total.",
                evidence=['independent-records','independent-allocations','detail-gaps'],
                method='Verify archived detail hashes and snapshot amounts; parse reported support/oppose labels and allocations; keep financial bases separate.',
                limitation='Target names are not reviewed race identities. Some records remain uncollected or fail validation. An allocation difference can reflect a partial expense allocation or another ordinary explanation; source review is required.')
        row['reviewStatus']='calculation checked; editorial and expanded source review pending'
    missing=[r for r in questions if r['status']=='currently unanswerable']
    gaps=[{'id':'G'+r['id'][1:],'questionId':r['id'],'track':r['track'],'description':r['limitation'],'requiredEvidence':r['method'],'status':'unresolved','notZero':True} for r in missing]
    publication={'version':'question-catalogue-v1','snapshot':SNAPSHOT,'questions':questions,'counts':{status:sum(r['status']==status for r in questions) for status in ['answered','qualified','currently unanswerable']}}
    for directory in [RESEARCH,PUBLIC,ROOT/'src/lib/campaign-finance']:
        write_json(directory/'questions.json',publication);write_json(directory/'gaps.json',gaps)
    print(publication['counts'])

if __name__=='__main__':run()
