import Link from "next/link";
import type { Metadata } from "next";
import FireEditorialShell from "@/components/oregon-fire/FireEditorialShell";
import { projectById } from "@/lib/oregon-fire/projects";
import { FIRE_AUTHORS, FIRE_URL } from "@/lib/oregon-fire/metadata";
const title = "Why burn this place?";
const description = "Follow a documented Oregon burn from its restoration objectives to the work, the observations, and the questions that remain.";
export const metadata: Metadata = { title: `${title} | Fire in Oregon`, description, alternates: { canonical: `${FIRE_URL}/stories/why-burn` }, authors: FIRE_AUTHORS.map((name) => ({ name })), openGraph: { title, description, url: `${FIRE_URL}/stories/why-burn`, type: "article" }, twitter: { card: "summary_large_image" } };
const chapters = [["changed", "What changed?"], ["matters", "What matters?"], ["choices", "What choices?"], ["happened", "What happened?"], ["helped", "Did it help?"]];
export default function Page() {
  const p = projectById("woodpecker")!;
  return <FireEditorialShell eyebrow="A field guide to a decision" title={title} intro="Start with the place. Follow the objective. Look for the evidence.">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: title, description, datePublished: "2026-09-26", dateModified: "2026-09-26", url: `${FIRE_URL}/stories/why-burn`, author: FIRE_AUTHORS.map((name) => ({ "@type": "Person", name })), citation: [p.evidence[0].url, "https://extension.oregonstate.edu/catalog/pub/em-9340-ecological-effects-fire"] }).replace(/</g, "\\u003c") }} />
    <nav className="fire-story-nav" aria-label="Story chapters">{chapters.map(([id, label], i) => <a key={id} href={`#${id}`}><span>0{i + 1}</span>{label}</a>)}</nav>
    <section id="changed" className="fire-dossier-section"><span className="fire-eyebrow">01 / Landscape history</span><h2>A place has more than one past.</h2>
      <p>Fire history differs among Oregon’s forests, prairies, and shrublands. Climate, weather, vegetation, land use, fire exclusion, and Indigenous stewardship all help explain the conditions we see today.</p>
      <div className="fire-story-diagram" role="img" aria-label="Landscape history and present conditions inform objectives, choices, work, and observations"><span>Landscape history</span><span>Present conditions</span><strong>A documented objective</strong><span>Choices & constraints</span><span>Work & observations</span></div>
      <p>Historical photographs show visible change at a particular viewpoint. They cannot establish its cause by themselves, or tell us that every place should return to the same condition.</p>
      <details><summary>Western forests have varied histories</summary><p>An Oakridge-area tree-ring study sampled 16 sites and found substantial variation in historical fire intervals. That is evidence for local interpretation, not a statewide burn schedule.</p><a href="https://news.oregonstate.edu/news/western-cascades-landscapes-oregon-historically-burned-more-often-previously-thought">Read the study summary ↗</a></details>
      <p className="fire-guide-note">Diagram explains a decision process; it is not a landscape reconstruction. Historical/repeat photographs are being evaluated for dates, viewpoints, and reuse rights.</p><a href="https://extension.oregonstate.edu/catalog/pub/em-9340-ecological-effects-fire">OSU: ecological effects of fire ↗</a>
    </section>
    <section id="matters" className="fire-dossier-section"><span className="fire-eyebrow">02 / Woodpecker, near Corvallis</span><h2>Two units. Two reasons.</h2><p>{p.selection}</p><div className="fire-objective-cards">{p.objectives.map((o) => <div key={o.id}><span className="fire-eyebrow">Reported objective</span><h3>{o.title}</h3><p>{o.text}</p></div>)}</div><p>Ask what a project is trying to sustain—and whose priorities its decision represents. Water, habitat, old trees, and nearby homes may call for different evidence. They are questions to investigate, not extra objectives to assign to this project.</p></section>
    <section id="choices" className="fire-dossier-section"><span className="fire-eyebrow">03 / Choices & constraints</span><h2>The objective comes before the tool.</h2><div className="fire-choice-grid"><div><h3>Prepare</h3><p>What prior work is documented? Thinning, harvest, and piling are separate activities; a treatment sequence matters.</p></div><div><h3>Choose a window</h3><p>Fuel moisture, weather, smoke dispersal, crews, and approvals affect implementation.</p></div><div><h3>Compare alternatives</h3><p>{p.alternatives}</p></div></div><a href="https://extension.oregonstate.edu/catalog/pub/em-9343-planning-prescribed-burn">Read OSU’s planning guide ↗</a></section>
    <section id="happened" className="fire-dossier-section"><span className="fire-eyebrow">04 / Follow the record</span><h2>A plan is not an accomplishment.</h2><ol className="fire-project-timeline">{p.activities.map((a) => <li key={a.id}><span>{a.date}</span><div><h3>{a.label}</h3><p>{a.text}</p></div></li>)}</ol><p className="fire-guide-note">{p.geometryMeaning}</p><Link className="fire-guide-primary" href="/oregon-fire/projects/woodpecker#timeline">See the project record →</Link></section>
    <section id="helped" className="fire-dossier-section"><span className="fire-eyebrow">05 / Evaluate</span><h2>Burned acres start the question.</h2><div className="fire-outcome-row"><div><span className="fire-eyebrow">Objective</span><h3>Support intended vegetation</h3></div><div><span className="fire-eyebrow">Observed</span><p>Implementation is described in the published account.</p></div><div><span className="fire-eyebrow">Still unknown</span><p>Repeated measurements, itemized costs, and verified boundaries remain unavailable.</p></div></div>
      <h3>What happened afterward?</h3><p>Look for dated monitoring and comparable observations. Satellite severity describes change; later greenness alone does not establish habitat quality or recovery of all forest attributes.</p>
      <div className="fire-choice-grid"><Link href="/oregon-fire?story=egley#fire-stories"><strong>Egley</strong><p>A separate field and satellite study of earlier treatments and wildfire.</p></Link><Link href="/oregon-fire?story=finley#fire-stories"><strong>Finley</strong><p>A separate prairie and oak habitat program.</p></Link><Link href="/oregon-fire?scarMode=severity&scarYears=1&scarEnd=2024#explore"><strong>Recent fire scars</strong><p>Explore patterns within fire boundaries and read their limits.</p></Link></div>
      <a href={p.evidence[0].url}>Source: OSU’s published Woodpecker account ↗</a><p className="fire-guide-note">Public-source editorial check: September 26, 2026. Independent ecological review pending.</p>
    </section>
    <section className="fire-story-ending"><span className="fire-eyebrow">Keep following the evidence</span><h2>Make the record better.</h2><Link href="/oregon-fire/projects/woodpecker#evidence">See the missing documents →</Link><Link href="/contact?topic=Data+correction&project=Oregon+Fire+Map&fireRecord=story:why-burn">Suggest a sourced correction →</Link></section>
  </FireEditorialShell>;
}
