/**
 * Regenerate research/pps-budget/sources.md from the registry + locks, and
 * lint the corpus for Maine-domain contamination.
 *
 *   npx tsx ingest/pps-budget/build.ts
 */

import fs from "node:fs";
import { DOCS, LOCK_PATH, ARCHIVE_LOCK_PATH, type Lock } from "./sources";

const MAINE = /portlandschools\.org|portlandk12\.org|portlandps\.org/;

function main() {
  const lock: Lock = fs.existsSync(LOCK_PATH)
    ? JSON.parse(fs.readFileSync(LOCK_PATH, "utf8"))
    : { lockedAt: "", files: {} };
  const archives: Record<string, { waybackUrl: string; waybackTs: string }> =
    fs.existsSync(ARCHIVE_LOCK_PATH) ? JSON.parse(fs.readFileSync(ARCHIVE_LOCK_PATH, "utf8")) : {};

  const maineHits = DOCS.filter((d) => MAINE.test(d.url) || MAINE.test(d.mirrorUrl ?? ""));
  if (maineHits.length) {
    console.error("MAINE CONTAMINATION in registry:", maineHits.map((d) => d.id));
    process.exit(1);
  }
  const doc = fs.readFileSync("research/pps-budget/document.md", "utf8");
  if (MAINE.test(doc.replace(/portlandschools\.org and portlandk12\.org belong to Portland, Maine[^.]*\./, ""))) {
    console.error("MAINE CONTAMINATION in document.md outside the reader warning");
    process.exit(1);
  }

  const bySeries = new Map<string, typeof DOCS>();
  for (const d of DOCS) {
    if (!bySeries.has(d.series)) bySeries.set(d.series, []);
    bySeries.get(d.series)!.push(d);
  }

  const lines: string[] = [
    "# PPS budget corpus: master source registry",
    "",
    "*Generated by `ingest/pps-budget/build.ts`. Do not hand-edit; the source of truth is `ingest/pps-budget/sources.ts`.*",
    "",
    `${DOCS.length} sources. "fetched" = downloaded and checksum-locked; "archived" = Wayback snapshot recorded.`,
    "",
  ];
  for (const [series, docs] of [...bySeries.entries()].sort()) {
    lines.push(`## ${series} (${docs.length})`, "", "| id | title | fy | status | link |", "|---|---|---|---|---|");
    for (const d of docs.sort((a, b) => a.id.localeCompare(b.id))) {
      const fetched = lock.files[d.id] ? "fetched" : d.kind === "page" ? "page" : "pending";
      const arch = archives[d.url]?.waybackTs && archives[d.url].waybackTs !== "FAILED" ? " · archived" : "";
      const wb = archives[d.url]?.waybackUrl;
      const link = `[live](${d.url})${wb && arch ? ` · [wayback](${wb})` : ""}`;
      lines.push(`| ${d.id} | ${d.title.replace(/\|/g, "/")} | ${d.fy ?? ""} | ${fetched}${arch} | ${link} |`);
    }
    lines.push("");
  }
  const fetchedCount = Object.keys(lock.files).length;
  const archivedCount = Object.values(archives).filter((a) => a.waybackTs !== "FAILED").length;
  lines.push(`---`, ``, `Totals: ${fetchedCount} fetched, ${archivedCount} archived, ${DOCS.length} registered. Lock date: ${lock.lockedAt}.`);
  fs.writeFileSync("research/pps-budget/sources.md", lines.join("\n") + "\n");
  console.log(`sources.md: ${DOCS.length} sources, ${fetchedCount} fetched, ${archivedCount} archived. Maine lint clean.`);
}

main();
