"use client";
import { useState } from "react";
import { ArrowDownToLine, ArrowRight, RotateCcw, SlidersHorizontal, MapPin } from "lucide-react";
import { dealMath, cashFlowCsv, DEFAULT_INPUTS, type DealInputs, type Ledger } from "@/lib/datacenters/engine";
import { DEAL_EXAMPLES } from "@/lib/datacenters/examples";
import { ReceiptBars, MoneyTimeline, money } from "./FiscalCharts";

type NumericKey = Exclude<keyof DealInputs, "paymentMode">;
const INPUT_LABELS: Record<NumericKey, string> = {
  taxableValueM: "Taxable value ($M)", taxRatePct: "Property tax rate (%)", abatementYears: "Years of tax break",
  feeM: "Annual payment ($M)", paymentSharePct: "Share of full tax (%)", minimumPaymentM: "Minimum annual payment ($M)",
  laterPaymentSharePct: "Later share of full tax (%)", paymentStepYear: "Higher share starts in year",
  upfrontM: "One-time deal payment ($M)", jobs: "Permanent jobs", wageK: "Annual wage ($K)", incomeTaxPct: "State income tax rate (%)",
  buildWithoutPct: "Chance it gets built without a break (%)", buildWithPct: "Chance it gets built with a deal (%)",
  horizonYears: "Years to compare", operatingYears: "Years the site operates", discountPct: "Discount rate (%)",
  baselineM: "Land taxes if nothing is built ($M)", serviceCostM: "Public costs per year ($M)",
  constructionLocalM: "Local taxes from construction ($M)", constructionStateM: "State taxes from construction ($M)"
};
const INPUT_HELP: Partial<Record<NumericKey, string>> = {
  taxableValueM: "The property value used to calculate taxes, which may differ from the construction cost or sale price.",
  taxRatePct: "The combined property tax rate that would apply without the break.",
  abatementYears: "How long the reduced tax payments last.",
  horizonYears: "How many years of payments and costs to include. Years after the break ends can change the result.",
  paymentSharePct: "The percentage of the full property tax bill paid during the break.",
  laterPaymentSharePct: "The percentage paid once the later payment rule begins.",
  paymentStepYear: "For example, enter 4 if the higher share begins in the fourth year.",
  buildWithPct: "Your estimate of the chance that construction happens if the company gets the deal.",
  operatingYears: "How long the facility stays open. After it closes, the model counts only the assumed land taxes.",
  discountPct: "How much less weight to give money received later. At 4%, $104 received next year counts as $100 today.",
  baselineM: "The annual property taxes the land would bring in if this project were not built. The model also uses this amount after closure.",
  constructionLocalM: "Local taxes generated by construction, counted once in year 1. Enter tax revenue, not total construction spending.",
  jobs: "Ongoing jobs at the operating facility, excluding temporary construction jobs.",
  wageK: "Average yearly pay per permanent employee. For example, 100 means $100,000.",
};
export default function DealCalculator() {
  const [exampleId, setExampleId] = useState(DEAL_EXAMPLES[0].id);
  const [inp, setInp] = useState<DealInputs>({ ...DEAL_EXAMPLES[0].inputs });
  const [ledger, setLedger] = useState<Ledger>("local");
  const example = DEAL_EXAMPLES.find(e => e.id === exampleId);
  const result = dealMath(inp, ledger);
  const threshold = result.breakEvenP;
  const inRange = threshold !== null && threshold >= 0 && threshold <= 1;
  const tied = Math.abs(result.net) < .000001;
  function change(key: NumericKey, value: number) { setInp(prev => ({ ...prev, [key]: value })); }
  function choose(id: string) {
    const chosen = DEAL_EXAMPLES.find(e => e.id === id);
    setExampleId(id); setInp({ ...(chosen?.inputs ?? DEFAULT_INPUTS) }); setLedger("local");
  }
  function provenance(key: keyof DealInputs) {
    if (example && inp[key] !== example.inputs[key]) return "Edited";
    return example?.documented.includes(key) ? "From source" : "Assumption";
  }
  function field(key: NumericKey, min: number, max: number, step: number, help?: string) {
    const kind = provenance(key);
    const explanation = help ?? INPUT_HELP[key];
    return <label className="dc-field" key={key}>
      <span className="dc-field-label">{INPUT_LABELS[key]}</span>
      <span className="dc-input-wrap"><input type="number" aria-label={INPUT_LABELS[key]} value={inp[key]} min={min} max={max} step={step}
        onChange={e => { const n = e.currentTarget.valueAsNumber; if (Number.isFinite(n)) change(key, Math.min(max, Math.max(min, step === 1 ? Math.round(n) : n))); }} /></span>
      <span className={"dc-input-source " + (kind === "From source" ? "is-sourced" : "")}>{kind}</span>
      {explanation && <span className="dc-input-help">{explanation}</span>}
    </label>;
  }
  function download() {
    const note = "# Example=" + (example?.title ?? "Custom") + "; example calculation, not verified tax collections\n";
    const url = URL.createObjectURL(new Blob([note + cashFlowCsv(inp, ledger)], { type: "text/csv;charset=utf-8" }));
    const a = document.createElement("a"); a.href = url; a.download = "data-center-fiscal-scenario.csv"; a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <div className="dc-calculator" data-testid="deal-calculator">
    <div className="dc-calc-start"><span className="dc-kicker">01 / Pick a starting point</span><p>Choose an example to fill in every value. Then change the assumptions to see when a tax break brings in more public money.</p></div>
    <div className="dc-examples" role="group" aria-label="Example agreements">
      {DEAL_EXAMPLES.map(e => <button key={e.id} type="button" onClick={() => choose(e.id)} aria-pressed={e.id === exampleId} data-testid={"example-" + e.id} className="dc-example">
        <span className="dc-example-place"><MapPin size={13} /> {e.place}<span className="dc-example-arrow"><ArrowRight size={18} /></span></span>
        <strong>{e.title}</strong><span>{e.short}</span><small>{e.tag}</small>
      </button>)}
    </div>
    <div className="dc-example-note"><span className="dc-note-marker">i</span><p>These examples show <strong>what could happen under stated assumptions.</strong> The Dalles examples use a signed agreement, and Hillsboro uses published program rules. They do not show verified amounts collected from those projects. Values we do not know are labeled “Assumption.”</p></div>

    <div className="dc-calc-grid">
      <div className="dc-calc-controls" id="dc-assumptions">
        <div className="dc-step-heading"><span className="dc-kicker">02 / Test the big unknown</span><button type="button" className="dc-text-button" onClick={() => choose("custom")}>Enter my own values</button></div>
        <h3>Would it be built anyway?</h3>
        <p className="dc-small">The more likely the project is without a tax break, the harder the break is to justify.</p>
        <div className="dc-probability">
          <div><label htmlFor="dc-build-chance">Chance of building without a break</label><output htmlFor="dc-build-chance">{inp.buildWithoutPct.toLocaleString("en-US", { maximumFractionDigits: 1 })}<span>%</span></output></div>
          <input id="dc-build-chance" type="range" min="0" max="100" step="1" value={inp.buildWithoutPct} aria-label={INPUT_LABELS.buildWithoutPct} onChange={e => change("buildWithoutPct", Number(e.target.value))} />
          <div className="dc-range-labels"><span>Needs the deal</span><span>Would build anyway</span></div>
          <div className="dc-probability-options">{[[25, "Unlikely"], [50, "50 / 50"], [100, "Certain"]].map(([n, label]) => <button type="button" key={n} aria-pressed={inp.buildWithoutPct === n} onClick={() => change("buildWithoutPct", Number(n))}>{label}</button>)}</div>
          <p className="dc-fine">This is your estimate, not a measured chance for any of these sites. For example, 50% means you think building without the break is as likely as not building.</p>
        </div>
        <a className="dc-mobile-jump" href="#dc-comparison">See the comparison <ArrowRight size={15}/></a>
        <p className="dc-fine">Dollar amounts marked M are millions; K means thousands. For example, 600 in a $M field means $600 million.</p>
        <div className="dc-main-inputs">
          {field("taxableValueM", 0, 20000, 10)}
          {field("taxRatePct", 0, 5, .05)}
          {field("abatementYears", 0, 30, 1)}
          {field("horizonYears", 1, 50, 1)}
        </div>
        <details className="dc-disclosure">
          <summary><SlidersHorizontal size={16} /> Payments, jobs and other assumptions</summary>
          <div className="dc-detail-body">
            <div className="dc-main-inputs">
              <label className="dc-field"><span className="dc-field-label">Payment rule</span><select aria-label="Payment rule" value={inp.paymentMode} onChange={e => setInp(prev => ({ ...prev, paymentMode: e.target.value as DealInputs["paymentMode"] }))}><option value="fixed">Fixed annual payment</option><option value="share">Share of full property tax</option><option value="stepped-share">Share that changes later</option></select><span className="dc-input-source">{provenance("paymentMode")}</span></label>
              {inp.paymentMode === "fixed" ? field("feeM", 0, 100, .1, "Enter the total annual taxes and fees paid during the break. Count each payment once.") : field("paymentSharePct", 0, 100, 1)}
              {inp.paymentMode === "stepped-share" && <>{field("laterPaymentSharePct", 0, 100, 1)}{field("paymentStepYear", 1, 50, 1)}</>}
              {inp.paymentMode !== "fixed" && field("minimumPaymentM", 0, 100, .1, "The company pays at least this much each year. This is a minimum total payment, not a fee added on top.")}
              {field("upfrontM", 0, 1000, .1, "A payment made once, in the first year, if the project is built.")}
              {field("buildWithPct", 0, 100, 1)}
              {field("operatingYears", 0, 50, 1)}
              {field("discountPct", 0, 15, .5)}
              {field("baselineM", 0, 100, .01)}
              {field("serviceCostM", 0, 100, .1, "Include added public-service costs, such as roads or emergency response. Enter local costs for the local view and local plus state costs for the Oregon view. Zero means no estimate has been included.")}
              {field("constructionLocalM", 0, 1000, .1)}
              {field("constructionStateM", 0, 1000, .1, "State tax revenue from construction is counted once in year 1, in the Local + Oregon view.")}
              {field("jobs", 0, 10000, 1)}
              {field("wageK", 0, 1000, 1)}
              {field("incomeTaxPct", 0, 100, .5, "Use the average share of wages paid in state income tax, rather than the highest tax bracket. Jobs, wages and this rate affect only the Local + Oregon view.")}
            </div>
          </div>
        </details>
        <details className="dc-disclosure"><summary>Where these example numbers come from</summary><div className="dc-detail-body dc-small">
          {example ? <><p>{example.basis}</p><p>{example.assumptions}</p><a href={example.source}>Read the original source ↗</a></> : <p>The custom starting values are examples. Replace them with estimates for the project you want to examine.</p>}
          <p>Each example assumes a 50% chance of construction without a break and a 100% chance with a deal. It also assumes 30 years of operation and $50,000 a year in land taxes if nothing is built. A 4% discount rate gives future payments less weight than money received today. Jobs, wages and state income-tax rates are examples, too. Public costs and construction tax revenue start at zero because we do not have estimates for them.</p>
        </div></details>
        <div className="dc-calc-tools"><button type="button" onClick={() => choose(exampleId)}><RotateCcw size={15} /> Reset example</button><button type="button" onClick={download}><ArrowDownToLine size={15} /> Download spreadsheet (CSV)</button></div>
      </div>

      <div className="dc-calc-results" id="dc-comparison">
        <div className="dc-result-sticky">
          <div className="dc-step-heading"><span className="dc-kicker">03 / Compare the outcomes</span><span className="dc-view-years">{inp.horizonYears} years</span></div>
          <div className="dc-ledger-switch" role="group" aria-label="Which governments to include">
            <button type="button" aria-pressed={ledger === "local"} onClick={() => setLedger("local")}>Local public money</button>
            <button type="button" aria-pressed={ledger === "statewide"} onClick={() => setLedger("statewide")}>Local + Oregon</button>
          </div>
          <p className="dc-fine">{ledger === "local" ? "Counts money received by governments and public districts in the area. It does not calculate changes in state school aid." : "Adds estimated state income tax from permanent jobs and state taxes from construction. It still does not calculate changes in school aid."}</p>
          <div className={"dc-verdict " + (result.net < -.000001 ? "is-negative" : "")} aria-live="polite" aria-atomic="true">
            <span className="dc-verdict-label">{tied ? "The options break even" : result.net > 0 ? "The deal comes out ahead" : "No tax break comes out ahead"}</span>
            <strong data-testid="net-result">{money(result.net)}</strong>
            <p>{tied ? "The calculation gives both options the same amount of public money." : "The deal brings in " + money(Math.abs(result.net)) + (result.net > 0 ? " more" : " less") + " than offering no break."} <span>This result uses your assumptions and subtracts the public costs you entered.</span></p>
          </div>
          <p className="dc-fine">Amounts are in millions of today’s dollars. They combine the chances of building and not building, rather than showing a guaranteed payment.</p>
          <ReceiptBars result={result} />
          <div className="dc-tipping-point">
            <div><span>The break-even point</span><strong data-testid="break-even">{inRange ? (threshold! * 100).toFixed(1) + "%" : "Outside this range"}</strong></div>
            {inRange ? <>
              <div className="dc-threshold-track" aria-hidden="true"><span style={{ width: threshold! * 100 + "%" }} /><i style={{ left: threshold! * 100 + "%" }} /><b style={{ left: inp.buildWithoutPct + "%" }} /></div>
              <div className="dc-range-labels"><span>Deal ahead</span><span>No break ahead</span></div>
              <p>If the chance of building without a break is below <strong>{(threshold! * 100).toFixed(1)}%</strong>, offering the deal brings in more money in this calculation. Above that chance, offering no break brings in more. The dot marks the chance you entered.</p>
              <button type="button" className="dc-text-button" onClick={() => change("buildWithoutPct", threshold! * 100)}>Set to break-even <ArrowRight size={14} /></button>
            </> : <p>{threshold === null ? "There is no usual break-even point here. With the costs you entered, even a project paying full tax brings in no more money than leaving the land as it is." : threshold! > 1 ? "With these values, the deal brings in more money at every chance of building without it, from 0% to 100%." : "With these values, the deal brings in less money at every chance of building without it, from 0% to 100%."}</p>}
          </div>
          <MoneyTimeline result={result} abatementYears={inp.abatementYears} />
          <a className="dc-mobile-jump" href="#dc-assumptions">Change the assumptions ↑</a>
          <p className="dc-fine dc-model-limit">This calculator compares public money, not every effect of a project. Water use, pollution, cleanup costs and other possible uses of the land need their own review. A zero in a cost field means the cost has not been estimated; it does not mean the project has no such cost.</p>
        </div>
      </div>
    </div>
    <details className="dc-disclosure dc-calc-method"><summary>See the full numbers and calculation</summary><div className="dc-detail-body dc-method-grid">
      <dl>{[["Estimated money with the deal", result.evSign], ["Estimated money without a break", result.evHold], ["Full property tax if the project is built", result.pvFullTax], ["Taxes and deal payments if built", result.pvDealProperty], ["Included property tax after the break ends", result.pvPostAbatement], ["Included state income tax if built", result.pvIncomeTax], ["Included taxes from construction if built", result.pvConstruction], ["Entered public costs if built", result.pvCosts]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{money(value as number)}</dd></div>)}</dl>
      <div className="dc-small"><p>Both options assume the same facility, start year and years of operation. The property value used to calculate taxes stays the same throughout. Multiplying that value by the tax rate gives the full annual property tax. During the break, the deal follows the payment rule you choose. After the break, it charges full tax.</p>
      <p>The calculator subtracts the public costs you enter. Taxes from construction and the one-time deal payment are counted in year 1. Future money receives less weight: each year’s amount is divided by (1 + discount rate) raised to that year’s number. At 4%, for example, $104 received one year from now counts as $100 today.</p>
      <p>The calculator combines the possible outcomes using the chances you enter. At a 50% chance of building, it counts half the value if the project is built and half the land taxes if it is not. This is an average of possible outcomes, not a promise of payment. After the site closes, only the assumed land taxes remain.</p><p>To find the break-even chance, it subtracts the value of leaving the land undeveloped from the deal’s estimated value. It divides that difference by the extra value of a project paying full tax. This calculation applies when a fully taxed project brings in more than leaving the land undeveloped.</p>
      <p>The Local + Oregon view estimates annual state income tax by multiplying permanent jobs, annual wages and the average tax rate entered. It does not account for workers leaving other taxable jobs or for tax credits. The model also leaves out changes in school aid, changes in property tax values, corporate taxes, and fees utilities pay local governments. It does not calculate the effects of another development on the site or environmental damage.</p></div>
    </div></details>
  </div>;
}
