"""Companion audit registers. Run after build-deliverables.py."""
import csv,json
from pathlib import Path
R=Path(__file__).resolve().parent.parent
def out(name,rows):
 with (R/name).open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=rows[0]);w.writeheader();w.writerows(rows)
sources={x['id']:x for x in csv.DictReader((R/'sources.csv').open())}
def links(ids):return ';'.join(sources[x]['url'] for x in ids.split(';'))
rule_data='''
R01|Critical|Six approval paths|Only six slugs eligible; generic trades have no scope classifier|Trade electrical/mechanical/plumbing approve as a class without verified no-plan-review eligibility|Split by actual scope and applicable adopted specialty code; maintain explicit allowlist with exclusions and unknown-to-review|C08;O01;O08;O09|PLUMB-MEDICAL;MECH-COMMERCIAL;ELECTRIC-LICENSE
R02|Critical|Fence material/location|Height thresholds exist but material key differs from UI; front/corner/historic checks incomplete|Masonry 6ft and adverse locations can receive approved flag|Canonical field keys and geometry/overlay checks; separate no-building-permit conclusion from issued permit|C08;O05|FENCE-MATERIAL;FENCE-FRONT;FENCE-CORNER;FENCE-HISTORIC
R03|Critical|Solar|Size limit exists; mount key mismatch; required engine docs absent from UI|Default UI is blocked by document keys; manually supplied engine docs reveal unsafe ground/engineered eligibility|Correct document contract; structural worksheet and prescriptive eligibility; electrical branch and unknown handling|C07;C08;O07|BASE-solar-permit;SOLAR-ADVERSE
R04|Critical|FIR|Valuation and structural-field mismatches; no registry lookup|500000 estimatedCost and false registration attestation still approve|Verify participant/scope against actual FIR process; route inspector consultation and field review|C08;O06|FIR-COST;FIR-ATTESTATION
R05|Critical|Server completeness/types|Presence tests; false and malformed values accepted; no authoritative server schema parse|False certifications and malformed email pass direct action pipeline|Validate enum/type/range/address/signature semantics server-side with same conditional contract as UI|C03;C04;C06|CERT-FALSE;BAD-EMAIL
R06|High|Upload contract|Renderer produces objects; Zod expects string IDs|105 of 119 upload-containing forms reproduce type failure with uploader-shaped data|Server-issued document IDs; normalized client shape; conditional required-doc tests across catalog|C04;C05|catalog-verification.json
R07|High|Required documents|Six slugs use engine snake-case keys different from catalog; ADU/solar lack upload fields|False incompleteness and inability to submit expected plans through normal form|One source of document requirements keyed by project path and revision|C01;C07|catalog-verification.json
R08|Critical|Substantive plan validation|MIME/name/size only|One-byte declared PDFs pass; content, seals and geometry uninspected|Retrieve bytes; secure parsing; signed-plan/geometry checks; human validation of uncertain extraction|C07|DOC-CONTENT;DOC-EMPTY;DOC-MIME
R09|High|Zoning input wiring|Public lookup is separate; pipeline reads cache by text and omits developmentStandards|Address objects/missing keys prevent reliable property join; height/FAR/setback checks generally lack standards in submit path|Canonical parcel ID, authoritative geometry, timestamp/versioned evidence; pass full standards and facts into decisions|C09;C11;C23;C25|source review
R10|Critical|Missing site/overlay evidence|Overlay errors converted to empty/false; routing deletes reviews based on missing site flags|Unknown may be treated as no hazard; warnings can survive automatic approval while disciplines disappear|Explicit verified-clear/triggered/unknown states; no omission of required discipline from missing data|C10;C12;C24|GIS-OUTAGE;OVERLAY-DROPPED
R11|High|Code suspensions|General seismic/site messages and broad deletion of tree/frontage routing; no date gate|Relief can appear for ineligible/new projects or beyond effective period|Encode section/scope/date/vesting and prior-condition exceptions, not blanket bureau deletion|C09;C10;O12;O13;O14|source review
R12|High|Fees|Calculator effective July 1 2025; no persisted authoritative assessment linked to checkout|Current July 10 2026 schedules and project-specific charges not proven|Version fee schedules and estimate/assessment distinction; reconcile exact cents with City|C14;C26;O15|PAYMENT-AMOUNT
R13|High|Housing SDC relief|New-multi-family omitted from residential classification; ADU treated as automatically permanently exempt|Incorrect eligibility/charges possible; conditions and recapture not operationally enforced|New-unit count/use and issued-date eligibility; separate ADU waiver; acknowledgement and 12-month milestone/guarantee/recapture ledger|C26;O16|source review
R14|High|Portfolio routing|18 explicit slugs; 15 produce nonempty default routing under empty form inputs|165 entries have no default discipline including three intentionally empty trades; 162 unmapped|Program owner and verified workflow for each enabled service; fallback staffed triage with alert|C10;C30|JOURNEY-sewer-lateral-connection;catalog-verification.json
R15|High|Parks condition shape|Eight legacy condition schemas incompatible with evaluator|Conditional evaluation throws; first public form page can still render|Migrate and validate catalog at build time; exercise each conditional branch|C01;C04;C06|catalog-verification.json
R16|Critical|Decision validity|No revision-bound approvals; empty review set satisfies every; unresolved blockers ignored at completion|Approved records can be changed or approved with missing required review evidence|Immutable revisions and dependency-aware approval predicates; reject nonexistent review actions|C03;C13|EDIT-AFTER-APPROVAL;REVIEW-BLOCKER;REVIEW-NO-ROWS
R17|High|Corrections|UI sends message; apply route only loads draft; resubmit duplicates work|Correction message does not replace plans or resolve findings; approved data not safely versioned|Amendment workspace, replace/supersede documents, re-review affected disciplines and reconcile findings|C03;C12;C32;C33|CORRECTION-RESUME;CORRECTION-REVIEW-REPLAY
R18|High|Land-use and demolition clocks|Generic SLA dates not full legal process state|No reliable notice/service/appeal/hold/finality implementation; stage advance completes all app deadlines; business-day helper excludes weekends only|Versioned legal clock rules/calendar and stage-specific deadlines, service evidence, hearing/appeal/condition records|C11;C22;C37;O17;O18;O19|source review
R19|High|Portable signs|Catalog retains registration|Requirement removed July 25 2026|Retire obsolete application and fees; preserve placement/size compliance guidance|C01;O31;O32|production catalog + source review
R20|High|Inspection/final/occupancy|No dedicated operational inspection or occupancy record workflow|Issued status cannot prove safe completed work or authority for occupancy|Inspection schedules/results/reinspection/special tests and dependency-controlled final/CO interface|C22;O03;O09|schema review
R21|Medium|AI role|Pipeline pre-review uses templates/heuristics; separate optional Anthropic advisor processes form JSON|No demonstrated AI plan understanding; recommendations not approvals|Document-bound extraction with evidence coordinates and confidence; human correction; deterministic decision layer|C27;C28|source review
R22|High|Jurisdiction and service authority|Catalog mixes city/county/state/private services|Department cannot complete DMV/OLCC/county licenses from local records|Explicit authority and handoff acknowledgements; retire invalid product names; measure City-controlled endpoint separately|C01;O40;O41;O43;O44|catalog-matrix.csv
'''
rules=[]
for line in rule_data.strip().splitlines():
 id,severity,scope,implemented,gap,needed,ids,test=line.split('|')
 rules.append(dict(id=id,priority=severity,scope=scope,implemented=implemented,gap=gap,required_rule_or_programming=needed,source_ids=ids,source_urls=links(ids),reproduction=test,confidence='High code evidence; legal applicability must be approved by responsible bureau for live decisions'))
out('rules-coverage.csv',rules)

integration_data='''
I01|Official permitting case system|Missing|Local applications and PDX reference numbers; no DevHub/AMANDA write adapter found|Create/read/update canonical City permit and stable idempotent IDs; reconcile legacy records|All official case completion|C03;C22;O01
I02|Production database|Implemented but unverified|DATABASE_URL uses postgres; missing env falls back to local PGlite even in production|Fail startup without production DB; schema migrations, backups/restore and retention evidence|Durability and shared state|C21;C22
I03|WorkOS/staff identity|Partial; production configuration unknown|Role checks exist; dev cookie personas default enabled unless env explicitly disables|Production-only auth enforcement, MFA/staff scope, remove dev routes, consistent roles|Real applicant/staff access|C17;C18
I04|Document storage|Partial; production configuration unknown|Supabase service role or public local disk fallback; upload/download route lacks ownership gate|Private storage, authorizations, validated upload receipts, quarantine, revision/hash/signature|Safe submission and approved plan set|C19;C20
I05|ArcGIS/property evidence|Implemented read integration; tested public lookup failed; decision wiring partial|Public City-building address returned not found; isolated failed overlay requests return clear-looking result; submit does not consume full result|Parcel geometry/jurisdiction, authoritative freshness and unknown states, prior conditions|Site eligibility and zoning|C23;C24;C11
I06|CCB/BCD/professional license registry|Missing|Credential fields are collected but not verified|Status, license class, expiry, authorized scope and identity matching|Trade/engineered path eligibility|C08;O01
I07|FIR membership and inspectors|Missing|Checkbox attestations and generic records|Participant registry, assigned inspector, consultation and field decisions|FIR operating path|C08;O06
I08|City fee engine and receivables|Missing|Standalone estimate; checkout trusts caller amount|Versioned assessment/invoice, exemptions, adjustments and finance posting|Correct charges and settlement|C14;C26;O15
I09|Stripe|Implemented but unverified live; isolated contract defects|Session/PaymentIntent metadata mismatch, no dedup, issuance ungated|Event inbox, assessed amount and payer match, state machine, retries, refunds and reconciliation|Reliable payment; City acceptance still required|C14;C15
I10|Official issuance and approved documents|Missing|Print HTML application and status flag only|Official record/number, authorized issuer, immutable approved plans, permit conditions/inspection card|Valid issued permit|C16;O03
I11|Inspections/special inspections/CO|Missing|No operational tables/actions for these milestones|Scheduling capacity, visit/result/reinspection, special-test evidence, final and CO dependencies|Full construction lifecycle|C22;O09
I12|Email/SMS/required service|Missing from inspected notification path|In-app notification rows; no demonstrated delivery/retry/receipt or statutory notice service|Outbox/provider, consent/channel, deliverability and legally sufficient service evidence|Applicant notifications and legal notices|C29
I13|Cross-bureau coordination|Partial|Address grouping of at most 500 local applications; text-based department inference|Shared project/parcel IDs, external approvals and blocking dependency graph|Parallel bureau completion|C30
I14|Trade bundling|Partial|Generates local child drafts with parent ID in JSON; no full required-permit graph|Typed parent-child IDs, scope/credentials, issue/final dependencies, no duplicate charging|Complete project scope|C31
I15|Legal notices/hearings/appeals|Missing|Generic SLA and appeal forms, not authoritative service and adjudication workflow|Calendar/time rules, recipients/proof, hearing record and independent decision route|Land use/demo/appeal finality|C22;C37;O17
I16|Revenue/utility/311/parks systems|Missing|Generic local intake; no confirmed account change, tax filing, credit, work order or reservation|Program-specific adapters with acknowledgement, capacity/account constraints, reconciliation|Non-permit service outcomes|C01;C22;O44;O45
I17|County/state/utility owner systems|Missing|Forms span non-City authorities|Authenticated handoff and external status/result, correct endpoint definitions|Food licensing, OLCC, DMV, DEQ and utility tickets|O40;O41;O43
I18|Operations and recovery|Partial/missing|Local histories/logs but no transactional event ledger or durable worker/recovery design found|Idempotent jobs/outbox, monitoring, failed-case triage, replay and restore drills|Reliable workload at scale|C03;C11;C15;C21
'''
ints=[]
for line in integration_data.strip().splitlines():
 id,system,status,current,needed,endpoint,ids=line.split('|');ints.append(dict(id=id,system=system,status=status,current_evidence=current,needed_interface_or_control=needed,endpoint_unblocked=endpoint,source_ids=ids,source_urls=links(ids),production_connection='Not verified except public deployment/page availability; do not infer secrets/configuration from source'))
out('integration-gaps.csv',ints)

path_data='''
T1|Electrical no-plan-review|electrical-permit;commercial-electrical-permit|Only explicitly eligible minor/residential/commercial classes; verified owner/contractor and complete evidence|M1|Conditional 100% issuance for accepted eligible case class|0 if required inspector work is included|Existing DevHub can already sell eligible permits; incremental gain must be measured|O01
T2|Electrical plan-review|electrical-permit;commercial-electrical-permit|Engineered/service/special occupancy/scope requiring drawings; confirm exact triggers with BCD/city|M2;M3|Unknown; do not apply T1 percentage|0 when inspections/review judgment required|Plan preparation, professional review and field tests remain|O02;O09
T3|Mechanical no-plan-review|mechanical-permit;commercial-mechanical-permit|Enumerated eligible equipment replacements/minor work; include current July 2026 conditions|M1|Conditional 100% issuance after verified inputs and City adapter|0 including inspection|Potential reduced incomplete orders; compare DevHub baseline|O01;O08
T4|Mechanical engineered/hood/commercial|mechanical-permit;commercial-mechanical-permit|Nonqualifying equipment, hood, ventilation or other plan-required work|M2;M3|Unknown|0 where inspection/technical decision required|Equipment code and site design review, installation/inspection remain|O08;O09
T5|Plumbing no-plan-review|plumbing-permit|Enumerated eligible fixture/minor work, valid applicant and complete scope|M1|Conditional 100% issuance after verified inputs and City adapter|0 including inspection|Do not include medical gas or other review-required projects|O01;O09
T6|Plumbing plans/medical gas|plumbing-permit|Medical gas and other required-plan classes|M2;M3|Unknown|0 including tests/inspection|The deployed generic auto path is unsafe for this class|O09
F1|Fence building-permit-exempt|fence-permit|Verified materials/heights and no pool barrier; zoning/visibility/site requirements independently checked|unknown|Not applicable: exemption determination, not issuance|Unknown; construction/compliance remains|Automate correct no-building-permit guidance, not phantom permit counts|O05
F2|Fence requiring permit/site review|fence-permit|Above exemption thresholds, pool barrier or other required technical/site review|M2|Unknown; objective checks can be extensive after structured site evidence|0 when inspection required|Height alone does not capture whole case|O05
S1|Solar prescriptive roof|solar-permit|Complete signed structural worksheet, approved roof/system inputs, no excluded condition, electrical linkage|M2|Unknown; high administrative automation; no verified authority for blanket <=25kW issuance|0 including inspections|Could approach zero-touch issue only for a bureau-accepted existing prescriptive class with all evidence|O07
S2|Solar engineered/ground/other|solar-permit|Structural engineering or site-specific route required|M3|Unknown|0 including engineering judgment/inspection|Collect and cross-check engineering; retain responsible approvals|O07
FI1|Existing FIR member eligible remodel|field-issuance-remodel|Actual member, accepted work scope, assigned FIR inspector|M3|0 where inspector preissuance review required|0|Faster scheduling/records possible; field model is retained|O06
FI2|Nonmember/out-of-scope FIR|field-issuance-remodel|New participant or ineligible project|unknown|0 through FIR unless accepted under existing program rules|0|Route ordinary building process; app cannot override closed enrollment|O06
R1|New detached/townhouse residential|residential-building-permit|Correct residential-code applicability, site and complete plans|M3|Unknown; no blanket zero-touch case claim|0 including inspections|Plan, site and construction dependencies remain|O02;O11
R2|Addition|residential-building-permit;major-residential-alteration|Area/height/site changes and potential new units; distinguish eligible code suspension|M3|Unknown|0 including inspections|Not the same as interior remodel; exterior/site review can dominate|O14
R3|Interior alteration/simple residential|residential-building-permit;storm-damage-repair|Within legal existing use, no excluded structural/site/safety trigger|M2;M3|Unknown; potential bounded objective subcases|0 if permit inspections required|Cosmetic exempt work should be routed out, not issued|O02
R4|Conversion without new unit|attic-basement-garage-conversion|Legal habitable-room conversion with verified existing conditions|M3|Unknown|0|Ceiling/egress/energy/structural and trade work remain|O02;O10
A1|Detached new ADU|adu-permit|New structure, zoning/site/utilities; separate ADU SDC waiver|M3|Unknown|0|Repeatable designs can reduce plan review but not site/field verification|O10;O16
A2|Attached/conversion ADU|adu-permit;attic-basement-garage-conversion|New independent dwelling in/attached to existing structure|M3|Unknown|0|Existing-building legality, fire separation, utilities and waiver conditions|O10;O16
R5|Small accessory construction|deck-permit;retaining-wall-permit;stairs-construction-permit;reroof-permit|Exempt maintenance/low structures versus required structural/surcharge/height review|M2|Unknown for permitted subset; exemption has no issuance endpoint|0 if inspected|Each exemption and permit class needs its own rules; no common height-only shortcut|O02
C1|Simple commercial TI|tenant-improvement;commercial-building-permit|No occupancy change, excluded structural work or unusual hazards; verify full scope|M2;M3|Unknown|0|Template plans and repeatable checks help; fire/accessibility and inspections remain|O09
C2|Complex TI/change of occupancy|tenant-improvement;change-of-use-permit|Use/occupant load/system/structural changes|M3;M4|Unknown|0|Do not auto-waive seismic/fire/accessibility based on generic suspension text|O09;O12;O14
C3|New commercial/nonresidential|commercial-building-permit|Complete engineered site/building/utility design|M4|Unknown|0|Professional review, bureau capacity and field acceptance remain|O09;O11
C4|Multifamily/mixed-use|commercial-building-permit|Correct structural code/occupancy, housing and nonhousing areas, utilities and public works|M4|Unknown|0|Housing exemption and mixed-use allocations require conditional treatment|O11;O16
D1|Residential demolition with applicable delay|demolition-permit|Qualifying structure, age/historic/deconstruction criteria and notice obligations|M3|0 if required agency determinations remain; all-case share unknown|0|Automate notice preparation and clocks; do not erase legal delay|O19;O20
D2|Demolition exempt from delay/other buildings|demolition-permit|Documented exception or different legal class; environmental and site duties retained|M3|Unknown|0|No public waiting period in a specific exception does not mean no inspections/clearances|O19;O20
L1|Objective administrative land-use checks|land-use-review|Only determinate standards, correct review type and no discretionary findings|M2|Unknown; technical eligibility may automate but legal decision/notice still applies|Unknown; conditions/appeal determine endpoint|Keep notice/appeal clocks and finality separate from technical pass|O17;O18
L2|Discretionary land use/hearings|land-use-review;land-use-appeal|Conditional uses/design/environmental/adjustments or hearing/appeal paths|M4|0 for cases requiring human merits decision|0|Software assists records/checks/scheduling; public process and decision remain|O17;O18
TR1|Ordinary exempt private tree work|tree-pruning-private;tree-removal-permit|Verified exempt work, tree/site status and no protected conditions|unknown|Not applicable for exempt work|Unknown|Deliver scope-specific guidance; no fictitious permit issuance|O21;O23
TR2|Routine street-tree pruning|tree-pruning-street|Limited authorized pruning scope with verified tree/ownership/contractor/site evidence|M2|Unknown; potential highly automated administrative subset|0 if field evaluation required; otherwise unknown|Separate larger limbs/heritage/hazard work|O24
TR3|Tree removal Type A|tree-removal-permit|All adopted Type A objective conditions, replacement/fees and site evidence|M2;M3|Unknown|0 when field verification/replanting staff work required|Species/diameter/ownership are facts to verify, not arbitrary accepted text|O22;O23
TR4|Tree Type B/heritage/waiver/programmatic|tree-removal-permit;heritage-tree-permit;replanting-waiver;programmatic-tree-permit|Discretionary tree condition/site/mitigation paths|M4|0 for required human decision|0|Arborist findings, notice and protection/replanting monitoring remain|O22
FR1|Simple recurring fire operating permit|fire-code-permit;portable-propane-permit;welding-hot-work-permit|Approved narrow activity with unchanged premises/credentials and current inspection status|M2;M3|Unknown; renewal automation conditional on actual policy|0 if inspection required|General form does not establish this eligible class|O28;O29
FR2|Fire event/special hazard|public-assembly-fire-permit;pyrotechnic-permit;outdoor-tent-permit;fire-art-performer-permit;laser-permit;ceremonial-bonfire-permit|Event/site/hazard-specific review and safety conditions|M3|0 where required inspection/officer decision precedes permission|0|Site safety, crowd/event conditions and staffing remain|O28;O29
FS1|Minor fire-system alteration|fire-alarm-alteration;sprinkler-system-minor|Exact existing affidavit/minor-modification path accepted by fire authority|M2|Unknown|0 including required acceptance testing|Do not equate affidavit receipt with system approval|O30
FS2|New/major fire system|fire-alarm-installation;sprinkler-system-permit|Professional design/engineering and full acceptance requirements|M3|Unknown|0|Functional and hydraulic tests are physical evidence|O30;O09
SI1|Portable sign compliant placement|portable-sign-registration|Post-July 25 2026 scope; size/location compliance|unknown|Not applicable: no registration required|Unknown|Retire obsolete transaction; guidance only|O31;O32
SI2|Temporary banner registration|temporary-sign-permit;sign-permit|Applicable registration type, duration/area/site criteria|M2|Unknown; potential objective administration|Unknown; display/removal and enforcement remain|Separate other exempt temporary signs|O31
SI3|Permanent sign/awning|permanent-sign-permit;sign-permit;fabric-awning-permit|Sign inventory, dimensions, attachments/structure/illumination and land-use conditions|M2;M3|Unknown|0 when inspection required|Engineering, electrical permits and geometry beyond text fields|O31
RW1|Simple temporary parking/space use|right-of-way-permit;portable-storage-permit;parking-day-permit|Known space/time, no traffic/access conflict or site exception|M2|Unknown; potential high administrative automation|Unknown; setup/removal/enforcement remain|Live space calendar and current street restrictions are necessary|O25;O26
RW2|Lane/sidewalk closure/event|street-closure-permit;special-event-permit;right-of-way-permit|Traffic-control/ADA/emergency/transit conflicts or special event|M3|Unknown; required staff engineering judgment remains|0 if inspections/staff field review|Static rules alone cannot know conflicting bookings or emergencies|O25;O26
RW3|ROW construction/encroachment|driveway-approach-permit;encroachment-permit;bike-rack-street;bike-rack-sidewalk|Civil geometry, utilities, insurance/bonds and restoration requirements|M3|Unknown|0|Physical construction and site/asset acceptance remain|O27;O33
W1|UC/UR sewer connection/repair|sewer-lateral-connection;sewer-lateral-repair|Verified property/scope/contractor/insurance/bond and linked private plumbing|M3|Unknown; release administration could be substantially automated|0|Target repeated documents, payment notification and issue handoff|O33;O34
W2|Meter/backflow/service work|residential-water-meter;commercial-water-meter;backflow-prevention|Demand/capacity/device and qualified tester requirements|M3|Unknown|0|Physical installation/test and billing/asset activation required|O35
W3|Industrial discharge/septic/environmental|industrial-wastewater-permit;stormwater-npdes-permit;septic-permit-new;septic-permit-repair|Correct agency/program and environmental/site evidence|unknown|Unknown; no numeric estimate supported|0 where site/lab/agency decision required|Different state/city programs; dedicated legal/rule audit still needed|O35;O36
AS1|ASTR Type A|accessory-str-permit;short-term-rental|Verified residency/legal bedrooms/notice and certification; exclude selected inspections/exception cases|M2|Unknown; 10% inspection sample is not evidence that other 90% are automatically issuable|Unknown due renewal/enforcement and sampling|Confirm bureau application of ENB-13.02 before designing live selection logic|O37;O38
AS2|ASTR Type B|accessory-str-permit;short-term-rental|Conditional-use scope and applicable conditions|M4|0 for required discretionary decision|0|Local permit and tax registration remain distinct|O37
HO1|Home business Type A/B|home-occupation-permit|Type A no-permit guidance; Type B conditions/notice; exceptions separately routed|M2|Unknown for Type B; not applicable for exempt Type A|Unknown|Verify updated limits and current process, do not trust legacy field labels|O39
'''
paths=[]
for line in path_data.strip().splitlines():
 id,name,slugs,eligible,models,zero,full,limit,ids=line.split('|')
 paths.append(dict(id=id,path=name,catalog_slugs=slugs,eligible_case_definition=eligible,as_deployed_staff_effort='Unknown measured',as_deployed_zero_touch_issue='0 demonstrated authoritative completions',as_deployed_zero_touch_full='0 demonstrated authoritative completions',tomorrow_staff_effort='Unknown; supervised comparison/assistance only',tomorrow_zero_touch_issue='0 through app alone',tomorrow_zero_touch_full='0 through app alone',software_staff_models=models,software_zero_touch_issue=zero,software_zero_touch_full=full,software_elapsed='Unknown measured; possible administrative queue/correction reduction; statutory and external time retained',conditions_and_limits=limit,confidence='High on identified implementation gaps; medium authority/process; low quantitative forecast',source_ids=ids,source_urls=links(ids)))
out('automation-paths.csv',paths)

backlog_data='''
B01|0|Correctness prerequisite|Lock down consequential actions and records|Remove production dev personas; authorize pipeline/PDF/upload/download; scope staff rights and applicant ownership; fail closed on missing auth/DB/storage config|WorkOS principal and role/department; application/document ownership; deployment environment|C17;C18;C19;C20;C11;C16|No other work required to reproduce; deployment config verification needed|Anonymous/other-user/forged-persona access denied; intended staff allowed; all deployed routes checked with synthetic data|All enabled real records; no direct hours claim|1-2 engineer-weeks; low-confidence sizing|High
B02|1|Correctness prerequisite|One validated form/document/eligibility contract|Normalize all schemas and condition shapes; enum/type/range and true attestations server-side; server-owned upload IDs; canonical material/mount/cost fields; unknown-to-review; split exemption from issue|Versioned schema; validated parcel and scope; private document receipt/hash; code-rule source IDs|C03;C04;C05;C06;C07;C08;O05;O07;O06|B01; bureau-reviewed rule pack|180 schemas compile; every conditional branch tested; six-path adverse/boundary cases block or route; missing/false/unknown facts never auto-pass|Broad intake leverage; 105 upload failures and 8 condition exceptions fixed|2-4 engineer-weeks for contract; additional rule-pack work separate|High
B03|2|Correctness prerequisite|Revision-bound workflow and durable processing|Explicit states and required-review graph; immutable revisions; block unresolved findings; edits invalidate affected approvals; idempotent submit/review/event writes; staffed exception queue|Revision hash, required reviews, owner/assignee, findings, events/outbox|C03;C11;C12;C13;C37|B01; B02 canonical data|Duplicate submit produces one revision and one work set; nonexistent review rejected; pending/blocker prevents approval; outage resumes; correction reopens correct case|All approval/review workflows; enables reliable labor measurement|3-5 engineer-weeks; low-confidence sizing|High
B04|3|Missing operating capability|Authoritative assessment, payment and issuance|Persist city-approved exact-cent assessment; checkout by invoice ID; dedup event inbox; verify amount/status; resolve checkout/intent correlation; reconcile ledger; issue official record and approved documents only after all gates|City case/invoice API or controlled import; Stripe transaction ID; approved revision; exemptions/conditions; official permit number|C14;C15;C16;C26;O03;O15;O16|B01-B03; City finance/issuing interfaces and approvals|Wrong amount or stale/duplicate/out-of-order payment never issues; failed payment leaves eligible unpaid state; single issuance after confirmed City record; refund/cancel/recovery tested|Shared preissuance bundle; use impact-sensitivity.csv, not advertised 22-day saving|4-8 engineer-weeks after interface access; external lead time unknown|High defect evidence; medium architecture
B05|4|Missing operating capability|Measure actual work and compare against DevHub|Define eligible cohort and endpoints; log staff active minutes, queues, corrections, payment delay, inspections and exceptions; matched historical/live comparison|City case IDs, event timestamps, staff time study, channel and scope flags; reviewer decision ground truth|C34;C35;C36;O01;O47;O48|Read-only data access; works in parallel with B01-B04|Reproducible cohort query; medians calculated per case with business calendar; exclude duplicates and distinguish issued vs approved-to-issue; all forecasts labeled|Required to rank annual ROI; no speculative saving assigned|1-3 analyst/engineer-weeks; access unknown|High need; outcome unknown
B06|5|Missing operating capability|Shared intake/correction and review workspace|Complete package rules and secure approved-plan revisions; assignments with required disciplines and fallback triage; accessible applicant correction/resubmit; cross-bureau condition tracking|Parcel/project IDs, plan index, revision diff, reviewer load/skills, deadlines, official case synchronization|C07;C10;C30;C32;C33;O02;O04|B01-B03; city document/review adapters|ADU/residential/commercial/demo/land-use/ROW cases route to actual owner; correction replaces correct revision; remaining reviews block release; applicant sees actionable reasons|Broad building workload; annualized proxy 7254 applications, not additive to B04 savings|4-8 engineer-weeks for bounded families; wider rollout additional|Medium
B07|6|Expansion/pilot|Bounded no-plan-review trade path|Select one exact equipment/fixture scope already eligible for no-plan-review issuance; verify license/jurisdiction; use current fees; approved issuing connector; exclusions and human exception path|Accepted scope list, owner/CCB/BCD status, parcel, invoice/payment, official permit and inspection requirements|O01;O08;O09;C08|B01-B06 minimum gates; regulator confirms existing authority|Replay six-path adversarial tests; true eligible set accepted; engineered/medical-gas/invalid-license/unknown-site diverted; compare existing DevHub user and staff minutes|Good pilot tractability; per1000 cases only until incremental baseline and volume verified|2-4 engineer-weeks per narrow rule pack after shared foundation|Medium; savings uncertain against DevHub
B08|7|Missing operating capability|Inspection administration and final closeout|Connect requests to real inspector capacity; record signed results/photos and reinspection; dependency-controlled final/CO; track expiration/extensions and exemption recapture|City inspection/work-order/CO API; discipline and trade dependencies; calendars and site outcomes; SDC milestone obligations|C22;O03;O09;O16;O33|B03-B04; inspector/bureau system access|Cannot final with failed/missing inspection or condition; failed visit creates reinspection; canceled/revised work recalculates; SDC deadline alerts and finance recapture|Large distinct workload: historical 85927 visits in eight months; automate admin minutes only|6-12 engineer-weeks for first integrated family; interface lead time unknown|Medium
B09|8|Expansion|UC/UR release coordination|Collect/validate reusable insurance and bond; separate public/private scope; sync paid status and remove manual email release handoff; inspection link|PBOT/BES/PP&D cases, insurance/bond records, City payment and ROW geometry|O33;O34;O35|B01-B04; B08 for full lifecycle|Expired insurance holds release; duplicate payment notification harmless; public/private work linked; restoration and inspection closeout enforced|Promising bounded manual handoff; per1000 cases model until volume verified|3-6 engineer-weeks after adapters|Medium
B10|9|Expansion|Versioned zoning and prescriptive plan checks|Use authoritative parcel geometry, prior decisions and code versions; validate height/FAR/coverage/setback facts from structured plans; enforce unknown states and narrow suspensions|GIS geometry/evidence timestamps, plan-derived typed facts, rule source/date and exception registry|C09;C10;C23;C24;C25;O11;O12;O14|B02; bureau validation set; rights/access for standards|Outage never returns clear; adjacent parcel/mismatched address rejected; boundary/vested-code cases; new-build never gets inapplicable alteration relief|Reusable across building cases; technical-review savings unknown until validation|4-8 engineer-weeks first narrow rule pack; comprehensive coverage much larger|Medium
B11|10|Correctness/maintenance|Update fee and service catalog currency|July2026 schedules; conditional SDC programs and recapture; remove portable-sign registration; reconcile duplicates and external authorities; responsible owner per service|Adopted fee tables, effective dates, product/authority registry and deprecation mapping|O15;O16;O31;O32;O40;O41;O44|B02 contract; ongoing rule owner|Before/after effective-date tests; multifamily/ADU/alteration classifications; obsolete registration no longer offered; canonical overlapping service paths|Prevents wrong charges and unnecessary applications; not a new permitting saving|1-3 engineer/analyst-weeks initial sweep plus recurring maintenance|High
B12|11|Expansion|Land-use/demo notice and legal-clock workflow|Compute exact recipients and service, holds/extensions, hearing/appeal and finality; record conditions and external clearances|Adopted process rules, calendars, mailing/geospatial service, evidence and hearing records|O17;O18;O19;O20|B03; legal/bureau rule approval and notice systems|Notice failure/holiday/appeal/extension does not silently expire; statutory waiting periods preserved; replacement construction gates demo final|Administrative time and missed-deadline risk; not elimination of hearings or delays|4-8 engineer-weeks first process family|Medium
B13|12|Expansion|Tree/sign/routine objective subpaths|Build separate exempt/routine/discretionary products; typed tree or sign/site evidence; connect conditions and inspections|Current Title11/32, tree inventory/sign geometry, ownership, prior approvals, bureau interfaces|O21;O22;O23;O24;O31;O32|B01-B06; route-specific staff validation|Protected tree or land-use condition diverts; replanting/inspection blocks final; no registration created for portable sign|After measured core workflow; volume unknown by subtype|2-6 engineer-weeks per bounded subpath|Medium
B14|13|Expansion|Evidence-based AI assistance|Extract facts with document/page/region provenance; reviewer verifies uncertainties; propose corrections, never authority by free-form answer|Private revisioned files, accepted extraction set, confidence and correction audit, provider data controls|C27;C28|B01-B03; secure document pipeline; quantitative evaluation|Contradictory/missing plans produce unknown; prompt injection cannot issue permit; every decision input traceable; reviewer-time benefit measured|Potential technical-review support; currently no demonstrated plan interpretation|3-6 engineer-weeks bounded extraction pilot; broad plan comprehension unknown|Low quantitative confidence
B15|14|Portfolio scope|Connect civic services only when owning agency is ready|Prioritize canonical referrals and official-system acknowledgements; actual parks booking, tax filing, utility credit or311 ticket has its own endpoint|Agency-specific account/inventory/finance/work-order APIs and current program rules|C01;C22;O40;O41;O44;O45;O46|Named owner and actual adoption case for each service|Submission creates real acknowledged record exactly once; no local approved flag presented as external license/award/repair|Benefit belongs to each service owner; not part of building-permit ROI|Unknown until agency/scope/interface chosen|Low
'''
backlog=[]
for l in backlog_data.strip().splitlines():
 id,rank,kind,name,behavior,inputs,ids,deps,tests,impact,effort,confidence=l.split('|')
 backlog.append(dict(id=id,rank=int(rank),work_class=kind,title=name,behavior_to_build=behavior,required_inputs_interfaces=inputs,rule_source_ids=ids,rule_source_urls=links(ids),dependencies=deps,acceptance_tests=tests,expected_impact=impact,implementation_effort=effort,confidence=confidence,ranking_note='Original operational roadmap; immediate sequence superseded by compliance-backlog.csv under user direction September 9, 2026. Payments and government integrations deferred. No summed ROI credit for overlapping shared-stage work.'))
priority_order=['B01','B02','B03','B11','B05','B04','B06','B07','B08','B09','B10','B12','B13','B14','B15']
for row in backlog:row['rank']=priority_order.index(row['id'])
backlog.sort(key=lambda r:r['rank'])
out('engineering-backlog.csv',backlog)

impact=[]
for name,count,coverage,lo,mid,hi,boundary in [
 ('Building-and-other application administration',4836,[(.25,15),(.5,45),(.8,90)],0,0,0,'Shared intake/correction/issuance bundle only; count each case once; does not include all trades or all civic services'),
 ('Inspection administration',85927,[(.25,2),(.5,4),(.75,6)],0,0,0,'Scheduling/result-entry/final records only; no field/travel/inspection elimination; visits are not permits'),
 ('Land-use case administration',220,[(.25,30),(.5,60),(.75,120)],0,0,0,'Separate illustrative workload; do not add to building cohort without deduplication; no merits/hearing elimination')]:
 for scenario,(share,mins) in zip(['low','middle','high'],coverage):
  annual=count*12/8
  impact.append(dict(workload=name,scenario=scenario,observed_count=count,observed_period='2024-07-01 to 2025-02-28',observed_months=8,annualized_proxy=annual,assumed_covered_share=share,assumed_minutes_saved=mins,modeled_hours_in_observed_period=round(count*share*mins/60,1),modeled_annual_hours=round(annual*share*mins/60,1),boundary=boundary,source='O47',source_url=sources['O47']['url'],confidence='Historical count visually verified; coverage/minutes/annualization are unmeasured scenarios, not forecast or actual saving'))
out('impact-sensitivity.csv',impact)

claim_data='''
CL01|175 form types|Contradicted by catalog|180 JSON schemas and catalog/registry entries; 14 categories|Derive display count and distinguish permits from other services|C01;C38
CL02|Six instant approval paths|Implemented flag; not valid end-to-end issuance|Five baseline fixtures autoapprove; solar blocked; adverse cases pass unsafe eligibility|Claim only specific demonstrated feature and eligible rule coverage after fixes|C07;C08
CL03|Trades ~100% time reduction / 11 days to same day|Unvalidated and unfair baseline for eligible no-review purchases|Current DevHub already supports qualifying purchases; app cannot issue authoritative permit|Measure incremental matched-scope staff and applicant time versus DevHub|C34;C35;O01
CL04|Fence/solar/FIR ~95-100% reduction|Unsupported blanket grouping|Fence exemption differs from issue; solar docs/eligibility incomplete; FIR requires actual field workflow|Separate paths and endpoints; no current savings percentage|C08;O05;O06;O07
CL05|52-100% overall timeline reductions|Modeled projection, not observed outcome|Hardcoded durations; no paired real cases or staffing/capacity model|Publish as explicitly conditional hypotheses with actual cohort/clock definition|C34;C35;C36
CL06|48,590 permits / 5.9M activities support predictions|Historical provenance incomplete for causal claim|Strategy cites these totals; underlying fixed snapshot and exact reproducible cohort not bundled with target app|Archive snapshot/hash and query; separate rows, permits, rounds and elapsed days|C35
CL07|73.8% corrections / 2.58 rounds; future 1-1.5|Not independently reproduced; future unsupported|Round/event definition, denominator and applicant hold overlaps unclear|Deduplicate rounds per revision and publish sample/period; prospective validation|C35
CL08|28 zones automatically checked at submission|Partial standalone rules; decision wiring incomplete|Development standards omitted in submit action; cache/address mismatch; site geometry and exceptions missing|State exactly which checks ran with verified evidence; unknown blocks auto route|C09;C11;C23;C25
CL09|Incomplete applications rejected before queue|Contradicted in isolated tests|Server accepts false/type-invalid data; empty case can persist in_review without assigned reviews|Gate submission or create explicit actionable incomplete/triage state|C03;C06;C11
CL10|AI pre-review understands application/plans|Misleading if describing pipeline stage|Pipeline uses heuristics; separate optional advisor sees form JSON; no substantive plan document analysis|Label deterministic templates versus optional AI assistance and evidence limits|C27;C28
CL11|Instant fee/payment/permit generation|Partial and incorrect end-to-end|Stale estimate disconnected from caller-priced checkout; event defects; print route is application HTML|Assess/pay/reconcile/authorize/issue approved package as separate verified states|C14;C15;C16;C26
CL12|~20 days saved at issuance from 22-day median|Unsubstantiated causal attribution|Elapsed stage may include payment/applicant/other holds; not 22 days staff work|Time-study the issuance gate and measure queue versus customer/system wait|C35;O03;O04
CL13|Parallel reviews eliminate sequential review delay|Potential coordination benefit; baseline already parallel|Own strategy says reviews already parallel; app has local review records rather than bureau integration|Credit only actual handoff/rework reduction and critical-path savings|C30;C35
CL14|147 calendar days consistent with ~121 business days|Unsupported conversion/cohort equivalence|Different clocks and cohort mix cannot be reconciled by assertion; naive 121 weekdays is about169 calendar days before holidays|Use actual dates and business calendar for identical cases|C35
CL15|ADUs permanently exempt / all housing relief automatic|Overbroad|ADU waiver is separate; temporary relief has date/use/acknowledgement/milestone conditions|Conditional finance workflow and recapture, not just zeroed fee|C26;O16
CL16|Pilot-ready flows|UI demonstration only; adoption prerequisites unmet|Source/test evidence shows security, schema, decision/payment/records gaps|Use supervised comparison stage until acceptance gates pass|C03;C08;C13;C14;C15;C17
'''
claims=[]
for l in claim_data.strip().splitlines():
 id,claim,verdict,evidence,replace,ids=l.split('|');claims.append(dict(id=id,claim=claim,verdict=verdict,evidence=evidence,recommended_replacement=replace,source_ids=ids,source_urls=links(ids)))
out('claims-verdicts.csv',claims)

# Human-readable source directory; cited descriptions intentionally brief.
md=['# Sources and code evidence','', 'Accessed September 9, 2026. Official pages can change; effective dates below are distinguished from access dates. Code links are pinned to the deployed commit and may require repository access. Numerical source-derived material is kept narrow; full permit-specific legal implementation remains future work.','']
for kind in ['official','source-code']:
 md+=['## '+('Official requirements and workload' if kind=='official' else 'Immutable implementation evidence'),'','| ID | Source | Date/version | Used for |','|---|---|---|---|']
 for x in sources.values():
  if x['kind']==kind:md.append(f"| {x['id']} | [{x['title']}]({x['url']}) | {x['version_or_date']} | {x['evidence_scope']} |")
 md.append('')
(R/'sources.md').write_text('\n'.join(md)+'\n')
print(json.dumps({'rules':len(rules),'integrations':len(ints),'paths':len(paths),'backlog':len(backlog),'claims':len(claims),'impact_scenarios':len(impact)}))
