import Link from 'next/link';
import { BASE, money } from '@/lib/campaign-finance/filters';
import type { Transaction } from '@/lib/campaign-finance/query';
import styles from './finance.module.css';
import active from '@/lib/campaign-finance/active-publication.json';
export { styles };
export function Shell({children}:{children:React.ReactNode}) {return <article className={styles.page}><div className={styles.wrap}>{children}</div></article>;}
export function Notice({children}:{children?:React.ReactNode}){return <aside className={styles.notice}>Active transaction ledger: {active.start}–{active.end}. The manual export is provisional and may omit older-dated late filings, removals or superseding amendments. November–December 2024 is missing; these are not full election-cycle totals. Historical research below retains its separately stated dates. Federal campaign fundraising is outside these ORESTAR totals.{children&&<p style={{margin:'8px 0 0'}}>{children}</p>}</aside>;}
export function Records({rows}:{rows:Transaction[]}) {return <div className={styles.tableScroll} role="region" aria-label="Transaction evidence, horizontally scrollable" tabIndex={0}><table><thead><tr><th>Date / record</th><th>Filing committee</th><th>Reported counterparty</th><th>Accounting basis</th><th className={styles.numeric}>Amount</th><th>Reported place</th></tr></thead><tbody>{rows.map(row=><tr key={row.transaction_id}><td>{row.transaction_date}<br/><span className={styles.muted}>#{row.transaction_id}<br/>Filed {row.filed_date||'unknown'} · {row.status}</span></td><td><Link href={`${BASE}/entities/committee:${row.committee_id}`}>{row.committee_name}</Link><br/><span className={styles.muted}>ORESTAR {row.committee_id}</span></td><td>{row.identity_status==='disclosure_category'||row.identity_status==='unknown'?<><span>{row.entity_name||'Not identified'}</span><br/><span className={styles.tag}>Disclosure category / unknown</span></>:<><Link href={`${BASE}/entities/${row.entity_id}`}>{row.entity_name}</Link><br/><span className={styles.muted}>{row.identity_status==='authoritative_committee_id'?'Committee ID':'Provisional record group'}</span></>}</td><td>{row.subtype}<br/><span className={styles.muted}>{row.direction} · {row.basis.replaceAll('_',' ')}</span></td><td className={styles.numeric}>{money(row.amount_cents)}</td><td>{[row.city,row.state].filter(Boolean).join(', ')||'Not disclosed'}</td></tr>)}</tbody></table></div>;}
export function Bars({rows,label}:{rows:{label:string;value:number;href?:string}[];label:string}) {const max=Math.max(...rows.map(r=>r.value),1);return <figure className={styles.bars} aria-label={label}><figcaption className={styles.muted}>{label}</figcaption>{rows.map((r,i)=><div className={styles.barRow} key={`${r.label}-${i}`}><div className={styles.barLabel}><span>{r.href?<Link href={r.href}>{r.label}</Link>:r.label}</span><strong>{money(r.value)}</strong></div><div className={styles.track} aria-hidden="true"><div className={styles.bar} style={{width:`${r.value/max*100}%`}}/></div></div>)}</figure>;}
