/**
 * Headline figures for the FY 2026-27 City of Portland budget.
 *
 * GENERATED by ingest/budget/build-dataset.ts — do not edit by hand.
 * Every number the site states as fact reads from here, so a changed headline
 * always shows up as a small, reviewable diff.
 *
 * Source: FY 2026-27 Adopted Budget, Portland City Budget Office.
 * Reconciliation: 18/18 checks passed,
 * 0 errors.
 */

export const BUDGET_FY = "2026-27" as const;
export const BUDGET_DOC = "FY 2026-27 Adopted Budget";
export const BUDGET_PUBLISHER = "Portland City Budget Office";
export const EXTRACTED_AT = "2026-08-10";

/** The City's own total, which counts internal transactions more than once. */
export const GROSS_TOTAL = 8546060062;
export const GROSS_TOTAL_PRIOR = 9039269833;
export const YOY_CHANGE = -493209771;
export const YOY_PCT = -5.456301007847124;

/** Money genuinely arriving from outside the City this year. */
export const EXTERNAL_REVENUE = 4205720797;
/** Carried over from prior years — not new money. */
export const BEGINNING_BALANCE = 2264623032;
/** Moved between City funds; counted on both sides of the gross total. */
export const FUND_TRANSFERS = 1554659457;
/** One City bureau billing another; also counted twice. */
export const INTERAGENCY = 521056776;

/** What bureaus actually spend running programs. */
export const BUREAU_EXPENSE = 4484113529;
export const DEBT_SERVICE = 526887376;
export const CONTINGENCY = 1599035219;
export const ENDING_BALANCE = 275674885;
export const RESERVED_FUTURE = 86401101;
export const DEBT_RESERVES = 19288495;

export const PROGRAM_COUNT = 286;
export const BUREAU_COUNT = 34;
export const FUND_COUNT = 83;
export const SERVICE_AREA_COUNT = 8;
export const TOTAL_FTE = 5830.77;

export const SOURCE_DOCS = [
  {
    "volume": 1,
    "title": "FY 2026-27 Adopted Budget, Volume 1 — City Summaries and Fund Detail",
    "url": "https://www.portland.gov/budget/2026-2027-budget/documents/fy-26-27-adopted-budget-book-volume-1-0/download",
    "sha256": "30127f3948a6771e33ed5ac0af2ab758648778856ee9c63413c9182ca4f2b2b2",
    "pages": 388
  },
  {
    "volume": 2,
    "title": "FY 2026-27 Adopted Budget, Volume 2 — Bureau and Program Detail",
    "url": "https://www.portland.gov/budget/2026-2027-budget/documents/fy-26-27-adopted-budget-book-volume-2/download",
    "sha256": "3b50ad08a2a31c732fd4921a72cd9d3f706c3b24990041d261a837dccf1a6846",
    "pages": 1090
  }
] as const;
