/**
 * Shapes for the City of Portland budget dataset.
 * The data itself is generated by ingest/budget/build-dataset.ts.
 */

export const YEARS = ["2023-24", "2024-25", "2025-26", "2026-27"] as const;
export type FiscalYear = (typeof YEARS)[number];
/** Positionally aligned to YEARS. null means the cell was absent, not zero. */
export type Values = [number | null, number | null, number | null, number | null];

export const YEAR_LABEL: Record<FiscalYear, string> = {
  "2023-24": "FY 2023-24 actual",
  "2024-25": "FY 2024-25 actual",
  "2025-26": "FY 2025-26 revised",
  "2026-27": "FY 2026-27 adopted",
};

export interface Line {
  label: string;
  depth: number;
  class: string | null;
  isTotal: boolean;
  values: Values;
  page?: number;
}

export interface Fund {
  slug: string;
  name: string;
  serviceArea: string;
  pages: number[];
  summaryOnly: boolean;
  revenues: Line[];
  expenses: Line[];
  revenueGrandTotal: Values;
  expenseGrandTotal: Values;
}

export interface FundingEdge {
  fundName: string;
  gfSplit: "discretionary" | "overhead" | null;
  class: string | null;
  label: string;
  values: Values;
}

export interface Program {
  slug: string;
  name: string;
  serviceArea: string;
  bureau: string;
  bureauSlug: string;
  pages: number[];
  description: string | null;
  expenses: Line[];
  total: Values;
  fte: Values;
  funding: FundingEdge[];
}

export interface Bureau {
  slug: string;
  name: string;
  serviceArea: string;
  values: Values;
  fte: Values;
  programCount: number;
}

export interface CitywideRow {
  label: string;
  depth: number;
  isTotal: boolean;
  prior: number | null;
  current: number | null;
}

export interface CitywideFigure {
  figure: string;
  title: string;
  page: number;
  rows: CitywideRow[];
  grandTotal: { prior: number | null; current: number | null } | null;
}

export interface Finding {
  id: string;
  severity: "error" | "warn" | "info";
  title: string;
  expected?: string;
  actual?: string;
  delta?: string;
  passed: boolean;
  detail?: string;
}

export interface SourceDoc {
  volume: number | null;
  title: string;
  url: string;
  sha256: string | null;
  pages: number | null;
}

export interface BudgetDataset {
  fy: string;
  documentTitle: string;
  publisher: string;
  years: readonly string[];
  extractedAt: string;
  sources: SourceDoc[];
  citywide: { requirements: CitywideFigure | null; resources: CitywideFigure | null };
  /** Citywide totals by object for all four years, from the fund detail. */
  yearlyObjects: { revenues: Record<string, Values>; expenses: Record<string, Values> };
  funds: Fund[];
  programs: Program[];
  bureaus: Bureau[];
  classTotals: Record<string, Values>;
  serviceAreaSummaries: unknown[];
  reconciliation: Finding[];
}

/** Human labels for the budget's major-object vocabulary. */
export const CLASS_LABEL: Record<string, string> = {
  personnel: "Personnel",
  "external-materials-services": "External materials & services",
  "internal-materials-services": "Internal materials & services",
  "capital-outlay": "Capital outlay",
  "debt-service": "Debt service",
  contingency: "Contingency",
  "fund-transfers-expense": "Fund transfers out",
  "ending-fund-balance": "Ending fund balance",
  "reserved-future": "Reserved for future",
  "external.taxes": "Taxes",
  "external.licenses-permits": "Licenses & permits",
  "external.charges-for-services": "Charges for services",
  "external.intergovernmental": "Intergovernmental",
  "external.bond-loan-proceeds": "Bond & note proceeds",
  "external.misc": "Miscellaneous",
  "internal.beginning-fund-balance": "Beginning fund balance",
  "internal.fund-transfers-revenue": "Fund transfers in",
  "internal.interagency": "Interagency revenue",
  "internal.general-fund-discretionary": "General Fund discretionary",
  "internal.general-fund-overhead": "General Fund overhead",
};

export const fmtMoney = (n: number): string => {
  const a = Math.abs(n);
  if (a >= 1e9) return `$${(n / 1e9).toFixed(2)}B`;
  if (a >= 1e6) return `$${(n / 1e6).toFixed(1)}M`;
  if (a >= 1e3) return `$${(n / 1e3).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
};

export const fmtExact = (n: number): string => `$${Math.round(n).toLocaleString("en-US")}`;
