// Per-bureau finance: operating (all-funds) total + program/department budget breakdown.
// Operating totals from the budget per-bureau "Bureau Overview"; departments extracted
// from the budget "Bureau Programs" charts (workflow), with pct RECOMPUTED as a share of
// the operating total for a consistent denominator. NOTE: this is TOTAL program budget
// (all funds: capital, debt, grants, pass-throughs like PCEF) — a different, much larger
// denominator than the personnel/salary cost in org-personnel.ts. `shownPct` is the share
// of the bureau covered by the listed (top) programs; the remainder is smaller programs.
// Generated by ingest/build-org-finance.py.

export const FINANCE_FY = "FY2025-26 Adopted";
export const FINANCE_SOURCE =
  "https://www.portland.gov/budget/documents/fy-2025-26-city-portland-adopted-budget-vol-1-city-summaries-and-bureau-budgets/download";

export interface Department { name: string; budget: number; pct: number; }
export interface BureauFinance { operatingTotal: number; shownPct: number; departments: Department[]; }

export const BUREAU_FINANCE: Record<string, BureauFinance> = {
  "bes": { operatingTotal: 1431010465, shownPct: 34.3, departments: [
    { name: "Capital Program Mgmt and Controls", budget: 244137785, pct: 17.1 },
    { name: "Other", budget: 55740484, pct: 3.9 },
    { name: "OandM - Treatment", budget: 46225054, pct: 3.2 },
    { name: "Business Support", budget: 44027513, pct: 3.1 },
    { name: "OandM - Collection System", budget: 43637106, pct: 3.0 },
    { name: "Strategy", budget: 22975733, pct: 1.6 },
    { name: "Funds Management", budget: 22135821, pct: 1.5 },
    { name: "OandM - Watershed", budget: 12712054, pct: 0.9 },
  ] },
  "bff": { operatingTotal: 288899941, shownPct: 60.0, departments: [
    { name: "Maintenance and Repair", budget: 63285196, pct: 21.9 },
    { name: "New and Replacement Acqs", budget: 61687295, pct: 21.4 },
    { name: "Operations and Maintenance", budget: 21477098, pct: 7.4 },
    { name: "Project Management", budget: 19726461, pct: 6.8 },
    { name: "Planning and Portfolio Management", budget: 7171904, pct: 2.5 },
  ] },
  "bhr": { operatingTotal: 218896003, shownPct: 94.0, departments: [
    { name: "Total Rewards", budget: 184347382, pct: 84.2 },
    { name: "Operations and Strategic Support", budget: 8309756, pct: 3.8 },
    { name: "Employee and Labor Relations", budget: 5142902, pct: 2.3 },
    { name: "Workforce Recruitment Training", budget: 3731152, pct: 1.7 },
    { name: "Classification,Compensation and Pay Equity", budget: 2078683, pct: 0.9 },
    { name: "People and Culture", budget: 1671857, pct: 0.8 },
    { name: "Well-Being and Occupational Health", budget: 689094, pct: 0.3 },
  ] },
  "boec": { operatingTotal: 39394224, shownPct: 94.4, departments: [
    { name: "9-1-1 Operations", budget: 32092423, pct: 81.5 },
    { name: "Technology Systems", budget: 3443961, pct: 8.7 },
    { name: "Administration and Support", budget: 1672317, pct: 4.2 },
  ] },
  "bps": { operatingTotal: 843956566, shownPct: 88.1, departments: [
    { name: "PDX Clean Energy Fund", budget: 685425130, pct: 81.2 },
    { name: "Other", budget: 26685391, pct: 3.2 },
    { name: "Waste Reduction and Recycling", budget: 18711568, pct: 2.2 },
    { name: "Inclusive Entrepreneurship", budget: 3575064, pct: 0.4 },
    { name: "Business Advancement", budget: 2638867, pct: 0.3 },
    { name: "Small Biz and Middle Income Hsg Fin Assist", budget: 2022545, pct: 0.2 },
    { name: "Reimagine Oregon", budget: 2014593, pct: 0.2 },
    { name: "Neighborhood Business Development", budget: 1363461, pct: 0.2 },
    { name: "Office of Events and Film", budget: 1203279, pct: 0.1 },
    { name: "Office of Small Business", budget: 1083580, pct: 0.1 },
  ] },
  "bts": { operatingTotal: 146406086, shownPct: 46.4, departments: [
    { name: "Communications", budget: 16432194, pct: 11.2 },
    { name: "Business Solutions", budget: 16230456, pct: 11.1 },
    { name: "Enterprise Business Solution", budget: 10878394, pct: 7.4 },
    { name: "Production Services", budget: 8479912, pct: 5.8 },
    { name: "Printing and Distribution", budget: 5416741, pct: 3.7 },
    { name: "Information Security", budget: 4154515, pct: 2.8 },
    { name: "Office of the CTO", budget: 3826132, pct: 2.6 },
    { name: "Project Management", budget: 2563064, pct: 1.8 },
  ] },
  "cbo": { operatingTotal: 4437127, shownPct: 100.0, departments: [
    { name: "Budget and Economics", budget: 4020419, pct: 90.6 },
    { name: "Public Utility Board Support", budget: 416708, pct: 9.4 },
  ] },
  "cfo-office": { operatingTotal: 274977555, shownPct: 54.1, departments: [
    { name: "Revenue Collections", budget: 96023700, pct: 34.9 },
    { name: "Liability", budget: 30680659, pct: 11.2 },
    { name: "Workers Comp", budget: 8706793, pct: 3.2 },
    { name: "CAOs Office", budget: 6008680, pct: 2.2 },
    { name: "Accounting", budget: 3578496, pct: 1.3 },
    { name: "Treasury", budget: 2185058, pct: 0.8 },
    { name: "Debt Management", budget: 1475448, pct: 0.5 },
  ] },
  "childrens-levy": { operatingTotal: 29157997, shownPct: 93.1, departments: [
    { name: "Investing in Children", budget: 26213342, pct: 89.9 },
    { name: "Administration and Support", budget: 924040, pct: 3.2 },
  ] },
  "city-attorney": { operatingTotal: 22300219, shownPct: 100.0, departments: [
    { name: "Legal Services", budget: 22300219, pct: 100.0 },
  ] },
  "city-auditor": { operatingTotal: 14185501, shownPct: 96.4, departments: [
    { name: "Administration and Support", budget: 3657817, pct: 25.8 },
    { name: "Archives and Records Management", budget: 3351236, pct: 23.6 },
    { name: "Audit Services", budget: 2639429, pct: 18.6 },
    { name: "Council Clerk and Contracts", budget: 1491561, pct: 10.5 },
    { name: "Elections", budget: 1391200, pct: 9.8 },
    { name: "Hearings Office", budget: 1151821, pct: 8.1 },
  ] },
  "city-council": { operatingTotal: 19548454, shownPct: 100.0, departments: [
    { name: "Commissioners Office", budget: 16310087, pct: 83.4 },
    { name: "Council Operations", budget: 3238367, pct: 16.6 },
  ] },
  "civic-life": { operatingTotal: 5068855, shownPct: 100.0, departments: [
    { name: "Neighborhood Outreach and Support", budget: 2593120, pct: 51.2 },
    { name: "Administration and Support", budget: 1193895, pct: 23.6 },
    { name: "Adapt to Impact", budget: 395765, pct: 7.8 },
    { name: "Youth Outreach", budget: 365211, pct: 7.2 },
    { name: "Immigrant and Refugee", budget: 315986, pct: 6.2 },
    { name: "Diversity Civic Leaders", budget: 204878, pct: 4.0 },
  ] },
  "community-safety": { operatingTotal: 30899669, shownPct: 100.0, departments: [
    { name: "CAO Public Safety", budget: 17372180, pct: 56.2 },
    { name: "Portland Street Response", budget: 10100639, pct: 32.7 },
    { name: "Office of Violence Prevention (OVP)", budget: 2847290, pct: 9.2 },
    { name: "Special Appropriations COCL/PCCEP", budget: 579560, pct: 1.9 },
  ] },
  "fpdr": { operatingTotal: 310269063, shownPct: 80.3, departments: [
    { name: "FPDR Pension Benefits", budget: 168309992, pct: 54.2 },
    { name: "Disability and Death Benefits", budget: 58370000, pct: 18.8 },
    { name: "Sworn PERS Contributions", budget: 10658296, pct: 3.4 },
    { name: "Other", budget: 3675335, pct: 1.2 },
    { name: "Special Appropriations External Ongoing", budget: 2908435, pct: 0.9 },
    { name: "Special Appropriations - Community Development", budget: 1699996, pct: 0.5 },
    { name: "Special Appropriation - City Support Services", budget: 1206637, pct: 0.4 },
    { name: "Portland Metro Levee", budget: 1185276, pct: 0.4 },
    { name: "Special Appropriations COCL/PCCEP", budget: 1138230, pct: 0.4 },
    { name: "Special Appropriations E Portland Action Plan", budget: 331575, pct: 0.1 },
  ] },
  "mayor": { operatingTotal: 3496592, shownPct: 100.0, departments: [
    { name: "Administration and Support", budget: 3496592, pct: 100.0 },
  ] },
  "ocpa": { operatingTotal: 2104114, shownPct: 0, departments: [
  ] },
  "office-ced": { operatingTotal: 71819077, shownPct: 77.7, departments: [
    { name: "Spectator Facilities", budget: 44227772, pct: 61.6 },
    { name: "Special Appropriations-City Arts Program", budget: 9595558, pct: 13.4 },
    { name: "CAOs Office", budget: 1949393, pct: 2.7 },
  ] },
  "office-city-administrator": { operatingTotal: 95342565, shownPct: 95.5, departments: [
    { name: "Alternative Shelter", budget: 39151087, pct: 41.1 },
    { name: "Overnight Shelter", budget: 26224751, pct: 27.5 },
    { name: "Impact Reduction Program", budget: 16671013, pct: 17.5 },
    { name: "Portland Environmental Management Office", budget: 5605499, pct: 5.9 },
    { name: "Administration and Support", budget: 1368205, pct: 1.4 },
    { name: "Portland Solutions Operations", budget: 1218997, pct: 1.3 },
    { name: "Assistant City Administrator", budget: 743582, pct: 0.8 },
  ] },
  "office-city-operations": { operatingTotal: 49715513, shownPct: 76.0, departments: [
    { name: "Procurement Services", budget: 12929481, pct: 26.0 },
    { name: "Security", budget: 8846890, pct: 17.8 },
    { name: "Information and Referral-CAO", budget: 6489501, pct: 13.1 },
    { name: "Grants Management", budget: 3669587, pct: 7.4 },
    { name: "Independent Review", budget: 3470234, pct: 7.0 },
    { name: "Unified Communications", budget: 1185739, pct: 2.4 },
    { name: "CAOs Office", budget: 1095378, pct: 2.2 },
    { name: "NA", budget: 52145, pct: 0.1 },
  ] },
  "office-equity": { operatingTotal: 3242998, shownPct: 105.3, departments: [
    { name: "Administration", budget: 1448166, pct: 44.7 },
    { name: "ADA Title II and Disability Equity Program", budget: 786593, pct: 24.3 },
    { name: "Title VI Compliance", budget: 574203, pct: 17.7 },
    { name: "LGBTQIA2S+ Program", budget: 224698, pct: 6.9 },
    { name: "Citywide Language Access Program", budget: 215617, pct: 6.6 },
    { name: "Tech Support and Consulting", budget: 164499, pct: 5.1 },
  ] },
  "office-government-relations": { operatingTotal: 3029890, shownPct: 100.4, departments: [
    { name: "State Relations", budget: 1099616, pct: 36.3 },
    { name: "Tribal Relations", budget: 606104, pct: 20.0 },
    { name: "Federal Relations", budget: 605483, pct: 20.0 },
    { name: "International Relations", budget: 447757, pct: 14.8 },
    { name: "Regional Relations", budget: 280356, pct: 9.3 },
  ] },
  "office-public-works": { operatingTotal: 2603945, shownPct: 100.0, departments: [
    { name: "CAOs Office", budget: 2604051, pct: 100.0 },
  ] },
  "parks": { operatingTotal: 541392393, shownPct: 38.5, departments: [
    { name: "Capital Development", budget: 79583482, pct: 14.7 },
    { name: "Natural Area Maint", budget: 56693408, pct: 10.5 },
    { name: "Facility/Amenity Maint", budget: 19383014, pct: 3.6 },
    { name: "Community and Socialization", budget: 17790118, pct: 3.3 },
    { name: "Aquatics", budget: 17184918, pct: 3.2 },
    { name: "Other", budget: 9775773, pct: 1.8 },
    { name: "Business Services", budget: 7568399, pct: 1.4 },
  ] },
  "pbem": { operatingTotal: 9394805, shownPct: 100.0, departments: [
    { name: "Regionl Disaster Prep Org", budget: 3964225, pct: 42.2 },
    { name: "Administration and Support", budget: 2382710, pct: 25.4 },
    { name: "Emergency Operations", budget: 2196856, pct: 23.4 },
    { name: "Planning and Mitigation", budget: 650373, pct: 6.9 },
    { name: "Community Programs", budget: 200641, pct: 2.1 },
  ] },
  "pbot": { operatingTotal: 610757226, shownPct: 49.5, departments: [
    { name: "Environmental System Maintenance", budget: 223197445, pct: 36.5 },
    { name: "Asset Management", budget: 34774385, pct: 5.7 },
    { name: "Active Transportation and On-Street Parking", budget: 18332026, pct: 3.0 },
    { name: "Safety", budget: 17910565, pct: 2.9 },
    { name: "Engineering", budget: 8486456, pct: 1.4 },
  ] },
  "pfr": { operatingTotal: 206281687, shownPct: 89.9, departments: [
    { name: "Emergency Operations", budget: 137069790, pct: 66.4 },
    { name: "Logistics", budget: 18191519, pct: 8.8 },
    { name: "Management Services", budget: 12945459, pct: 6.3 },
    { name: "Community Health Division", budget: 11923284, pct: 5.8 },
    { name: "Prevention", budget: 4499266, pct: 2.2 },
    { name: "Other", budget: 916086, pct: 0.4 },
  ] },
  "phb": { operatingTotal: 244215819, shownPct: 88.9, departments: [
    { name: "Affordable Multifamily Development", budget: 166385883, pct: 68.1 },
    { name: "Rental Srvcs Pol and Plan", budget: 19181655, pct: 7.9 },
    { name: "Homeowner Access and Retention", budget: 13173685, pct: 5.4 },
    { name: "Administration and Support", budget: 9031095, pct: 3.7 },
    { name: "Homelessness Diversion", budget: 5374900, pct: 2.2 },
    { name: "Other", budget: 3987545, pct: 1.6 },
  ] },
  "ppb": { operatingTotal: 316692335, shownPct: 74.5, departments: [
    { name: "Precinct Patrol", budget: 119473842, pct: 37.7 },
    { name: "Other", budget: 37415598, pct: 11.8 },
    { name: "Person Crimes Investigation", budget: 23897692, pct: 7.5 },
    { name: "Records", budget: 15798037, pct: 5.0 },
    { name: "Tactical Emergency Response", budget: 15464829, pct: 4.9 },
    { name: "Information Technology", budget: 11525080, pct: 3.6 },
    { name: "Neighborhood Response", budget: 6341482, pct: 2.0 },
    { name: "Standards and Accountability", budget: 6338713, pct: 2.0 },
  ] },
  "ppd": { operatingTotal: 97732402, shownPct: 59.4, departments: [
    { name: "Administration and Support", budget: 25611745, pct: 26.2 },
    { name: "Combination Inspections", budget: 7514203, pct: 7.7 },
    { name: "Land Use Services", budget: 6654745, pct: 6.8 },
    { name: "Development Services", budget: 6389067, pct: 6.5 },
    { name: "Commercial Inspections", budget: 5650227, pct: 5.8 },
    { name: "Compliance Services", budget: 4025471, pct: 4.1 },
    { name: "Neighborhood Inspections", budget: 2272182, pct: 2.3 },
  ] },
  "water": { operatingTotal: 2183344599, shownPct: 37.5, departments: [
    { name: "Water Program Treatment", budget: 517057225, pct: 23.7 },
    { name: "Other", budget: 114279993, pct: 5.2 },
    { name: "Conduits/Transmission", budget: 104413137, pct: 4.8 },
    { name: "Distribution Mains", budget: 42570720, pct: 1.9 },
    { name: "Customer Services", budget: 42124898, pct: 1.9 },
  ] },
};
